### ISSUE TITLE
Create wallet - Implement the "Terms of use" screen.

### ISSUE THREAD

**Issue by Denis-Asipenko** [BeamMW/android-wallet#100]
https://app.zeplin.io/project/5ba9be48f029d520c456f395/screen/5c24d6b0cdb0832449c1f63e
![screenshot_8](https://user-images.githubusercontent.com/45556620/52619071-c6265200-2eb1-11e9-8f8e-493416e14556.png)

**Comment by sasha-abramovich** [comment]
won't implement
