### ISSUE TITLE
Add dialogue box which caution the wallet can't connect to the node.

### ISSUE THREAD

**Issue by Denis-Asipenko** [BeamMW/android-wallet#103]
https://app.zeplin.io/project/5ba9be48f029d520c456f395/screen/5c0fa62d638b1baf0485b0c5
![screenshot_10](https://user-images.githubusercontent.com/45556620/52622467-f7efe680-2eba-11e9-9a88-be5145445950.png)

**Comment by kaminskyelina** [comment]
Related to Restore

**Comment by sasha-abramovich** [comment]
mission unclear. halt.
