### ISSUE TITLE
Change/add a name "testnet" (google play,app,website,documentation)

### ISSUE THREAD

**Issue by Denis-Asipenko** [BeamMW/android-wallet#118]

**Comment by kaminskyelina** [comment]
@sasha-abramovich  
Need something very clear and bold (May be red color in the wallet) that says "Tentnet - play money" or something, same in the website

**Comment by sasha-abramovich** [comment]
@alexandrashelenkova please prepare design screen - there are too many people trying to send beams from desktop (mainnet) to mobile (testnet).

**Comment by alexandrashelenkova** [comment]
Added testnet next to online indicator, updated screen is here zpl.io/a75gYZK

**Comment by kaminskyelina** [comment]
Done
the one only thing is APK name - new task will be opened on it
