### ISSUE TITLE
Sending transaction to own expired address crashes the app.

### ISSUE THREAD

**Issue by Denis-Asipenko** [BeamMW/android-wallet#129]
Steps to reproduce the behaviour:
1. Go to Receive screen.
2. Create new address.
3. Go to address book and choice this address
4. Edit address: switch "expire address now"
5. Go to Send screen.
2. Sending transaction to myself.
Expected: transaction not pass.
Actual: Crash app.

**Comment by roman-strilets** [comment]
fixed crash on android with expired address.
Please implement onCantSendToExpired

**Comment by Denis-Asipenko** [comment]
checked
