### ISSUE TITLE
Add dialogue window when sending transaction to own expired address.

### ISSUE THREAD

**Issue by Denis-Asipenko** [BeamMW/android-wallet#130]
Please add dialogue window when sending transaction to own expired address.
Similar to this:
![screenshot_36](https://user-images.githubusercontent.com/45556620/53950363-09ed2f80-40dd-11e9-917c-6bf8c0851921.png)

**Comment by sasha-abramovich** [comment]
seriously, guys - don't we have enough dialog boxes in our UX already to take the example from? @kaminskyelina

**Comment by Denis-Asipenko** [comment]
checked
