### ISSUE TITLE
Testnet and Mainnet Release Notes

### ISSUE THREAD

**Issue by kaminskyelina** [BeamMW/android-wallet#131]

**Comment by sasha-abramovich** [comment]
https://docs.google.com/document/d/1V1BhNKueVmUOk01Lx_7fL29RUbXksn7KUoZwt8DPw14/edit

**Comment by sasha-abramovich** [comment]
@kaminskyelina wrote whatever we know now. Assigned to you to fill the gaps.

**Comment by kaminskyelina** [comment]
Sasha, since we release Testnet first- please update or create new RN for testnet

**Comment by sasha-abramovich** [comment]
https://docs.google.com/document/d/1OhyPrHRV55vW1UrANIQbZxrlcGbs_wajcG-QpxkgoMY/edit#
