### ISSUE TITLE
Align create password screen UX with the spec

### ISSUE THREAD

**Issue by vain-onnellinen** [BeamMW/android-wallet#14]
https://app.zeplin.io/project/5ba9be48f029d520c456f395/screen/5bc7bad3b3930253e443f19a

**Comment by vain-onnellinen** [comment]
@sasha-abramovich you need to give me "pretty-looking" text to describe password strength. I need it to finish this screen. The same question is in zeplin.
Requirements for pass:
strong pass should have 10 and more symbols. 
at least one must be a number, at least one capital letter, at least one small letter

**Comment by sasha-abramovich** [comment]
@alexandrashelenkova can you please provide the screen for that?

**Comment by alexandrashelenkova** [comment]
done zpl.io/Vql6koY

**Comment by Denis-Asipenko** [comment]
checked
