### ISSUE TITLE
Scan QR code design for Android

### ISSUE THREAD

**Issue by kaminskyelina** [BeamMW/android-wallet#140]

**Comment by alexandrashelenkova** [comment]
Screens are here
zpl.io/bz1gAG8
zpl.io/29OQ5JB

Camera access permission should be asked when user first tries to scan the code. 
Dialog text: "Beam Wallet needs access to camera". Buttons Cancel/OK
If user chooses OK - open this screen zpl.io/29OQ5JB, if user chooses Cancel - back to that screen zpl.io/bz1gAG8

**Comment by Denis-Asipenko** [comment]
checked
