### ISSUE TITLE
Adjust masternet colors for the wallet

### ISSUE THREAD

**Issue by sasha-abramovich** [BeamMW/android-wallet#144]
the design is here

https://app.zeplin.io/project/5ba9be48f029d520c456f395?seid=5c88ed40b18b6538304b0209

**Comment by sasha-abramovich** [comment]
@gingervik do we have masternet for mobile wallets?

**Comment by gingervik** [comment]
@sasha-abramovich yes, we have

**Comment by vain-onnellinen** [comment]
it is already done, guys

**Comment by gingervik** [comment]
@Denis-Asipenko please, close this issue if it's done

**Comment by Denis-Asipenko** [comment]
checked
