### ISSUE TITLE
Add status  "updating" to wallet when it's listening a lib

### ISSUE THREAD

**Issue by Denis-Asipenko** [BeamMW/android-wallet#149]
![image](https://user-images.githubusercontent.com/45556620/54601273-ae616100-4a4f-11e9-8b3d-9996d2239304.png)

**Comment by kaminskyelina** [comment]
Please sync with iOS, I think they use "Connecting"

**Comment by vain-onnellinen** [comment]
@kaminskyelina nope, they are using both: updating(when updating wallet status) and connecting(when checking internet status).

**Comment by vain-onnellinen** [comment]
we added updating status, but can't add connecting status as ios did.
we can't differ user surfing between screens from user recovering app from tray, so status "connecting" can't be implemented in the way it supposed to be.

**Comment by Denis-Asipenko** [comment]
checked
