### ISSUE TITLE
Payment proof for Android

### ISSUE THREAD

**Issue by kaminskyelina** [BeamMW/android-wallet#155]
Design is needed

**Comment by alexandrashelenkova** [comment]
@kaminskyelina can you tell me please in which project that issue is? How urgent is it?

**Comment by kaminskyelina** [comment]
@alexandrashelenkova it is ready in Desktop already
@sasha-abramovich  please decide about priority

Thank you

**Comment by dariatarakanova** [comment]
Please find screens here https://app.zeplin.io/project/5ba9be48f029d520c456f395/dashboard?seid=5c9cdeb9eb413e0ab96f31c2 

And LMK if you have any questions

**Comment by Denis-Asipenko** [comment]
checked
