### ISSUE TITLE
Transaction becomes Receiving after deletion 

### ISSUE THREAD

**Issue by kaminskyelina** [BeamMW/android-wallet#156]
**Describe the bug**
Transaction becomes Receiving after deletion 

**To Reproduce**
Steps to reproduce the behaviour:
1. Delete Received transaction
2. Restart the wallet
3. Login again 

**Expected behaviour**
Deleted transaction should not appear

**Actual behaviour**
Transaction becomes Receiving 

[wallet_19_03_24_11_06_24.log](https://github.com/BeamMW/android-wallet/files/3000361/wallet_19_03_24_11_06_24.log)

Device model: Android Redmi 6A 
OS: 8.1.0 011019
Model: M1804C3CG

Beam Wallet version 1.0.16

**Comment by kaminskyelina** [comment]
[2019-03-24 (2).crash.zip](https://github.com/BeamMW/android-wallet/files/3000522/2019-03-24.2.crash.zip)

**Comment by Denis-Asipenko** [comment]
checked
