### ISSUE TITLE
Make scroll screen for whole screen 

### ISSUE THREAD

**Issue by kaminskyelina** [BeamMW/android-wallet#157]
**Subject**
Make scroll screen for whole screen

**Details**
Now only transactions section is scrolled. 
Freeze of Send/Receive, Balance, and Progress is not necessary 

@alexandrashelenkova  - this is not mentioned in design, and implemented differently in iOS and Android.  scrolling for full screen is preferred

**Comment by kaminskyelina** [comment]
[Archive.zip](https://github.com/BeamMW/android-wallet/files/3000394/Archive.zip)

**Comment by alexandrashelenkova** [comment]
All right, scroll should be for whole screen

**Comment by Denis-Asipenko** [comment]
checked
