### ISSUE TITLE
Issue with Paste function

### ISSUE THREAD

**Issue by kaminskyelina** [BeamMW/android-wallet#159]
**Describe the bug**
When I copy and paste to address, text that includes unnecessary  string - it is not shown after I paste 

**To Reproduce**
Steps to reproduce the behaviour:
1. Copy address and send via Telegram
2. Copy Address from Telegram and paste in Android wallet address to send

When I copy from Telegram, also Sender's name is copied, but it is not shown after I paste in the wallet. 
What happens is that the beginning of the string is changed

Example:
Copied text - 
"Alex Romanov:
84e46a6547c7240484dd0a6efb3690d9d593382acf49839c42a57759898cfb3b2d" 

After I paste it I see-
"Aea84e46a6547c7240484dd0a6efb3690d9d593382acf49839c42a57759898cfb3b2d"

**Setup**
Device model: Redmi 6A
OS: 8.1.0 011019

See attached files
[wallet_19_03_24_14_19_18 (1).log](https://github.com/BeamMW/android-wallet/files/3000448/wallet_19_03_24_14_19_18.1.log)

[20190324_154826.mp4.zip](https://github.com/BeamMW/android-wallet/files/3000451/20190324_154826.mp4.zip)

**Comment by sasha-abramovich** [comment]
@alexandrashelenkova should we somehow indicate that multiline content was pasted and that's an error?

**Comment by vain-onnellinen** [comment]
@sasha-abramovich error is not in multiline text (such text is allowed). Error in incorrect symbols and what to do with it

**Comment by alexandrashelenkova** [comment]
I guess we can just show an error that address is invalid?

**Comment by sasha-abramovich** [comment]
Don't show anything in the pasted line, below the line let's have the comment: "Can't paste an invalid address".

**Comment by Denis-Asipenko** [comment]
checked
