### ISSUE TITLE
Settings completion- implement lock screen for Android

### ISSUE THREAD

**Issue by kaminskyelina** [BeamMW/android-wallet#161]
https://zpl.io/aRWMexN

**Comment by Denis-Asipenko** [comment]
@alexandrashelenkova I propose to make "Lock screen":
- After 15 seconds
- After 30 seconds
- After 1 minute
I think 5,10,30 minutes not actual for mobile wallet.

**Comment by alexandrashelenkova** [comment]
@Denis-Asipenko yes, let's change it that way

**Comment by Denis-Asipenko** [comment]
When selected "After 15 seconds" screen doesn't lock for the selected time.

**Comment by Denis-Asipenko** [comment]
checked
