### ISSUE TITLE
Encode the object type / protocol into QR code

### ISSUE THREAD

**Issue by sasha-abramovich** [BeamMW/android-wallet#163]
So that our users:

* Will get an error when trying to scan this code from another app
* Will open Beam Wallet automatically (if installed) when OS-level scanning will happen

**Comment by kaminskyelina** [comment]
New format:
beam:12d1a5d6dc54af1792dc67325aeb274c38c36e005c730b964e978f0d3afdfddbc26?amount=12.102

Must: read old formats

**Comment by gingervik** [comment]
about design: just add field "Transaction amount" above field "Comment" (like in desktop version)
![image](https://user-images.githubusercontent.com/28015224/56898137-f2a53f80-6a98-11e9-8588-67f2e7024d86.png)

**Comment by gingervik** [comment]
- mobile wallet scan new QR with amount generated by desktop
- mobile wallet scan new QR without amount generated by desktop
- scan old QR generated by desktop
- scan old QR generated by mobile

old mobile waletts do mnot encode new QR - it's ok

**Comment by gingervik** [comment]
Bug:
- in desktop wallet click on receive
- enter amount 1 000 000
- scan QR with mobile
Actual: Transaction amount field is empty
Expected: all amounts <=262,800,000 should be readable by phone qr scan

**Comment by gingervik** [comment]
Bug 2
On receive screen ax Transaction amount which user can enter should be <=262,800,000

**Comment by gingervik** [comment]
Bug 1 is still reproduce
try to scan this code
![image](https://user-images.githubusercontent.com/28015224/57123076-1adaba00-6d89-11e9-9ad6-d1b8f372aeb3.png)

Bug 2
for now max amount = 99 999 999

**Comment by Denis-Asipenko** [comment]
Bug 1 is still reproduce
try to scan this code
![image](https://user-images.githubusercontent.com/45556620/57135776-4ecad500-6db3-11e9-97dc-2456b1dbff4f.png)

**Comment by gingervik** [comment]
waiting for fix https://github.com/BeamMW/beam/issues/617

**Comment by gingervik** [comment]
checked
