### ISSUE TITLE
Add info in the log file.

### ISSUE THREAD

**Issue by Denis-Asipenko** [BeamMW/android-wallet#164]
We need to add the following info to the logs:
- app version.
- lib version.
Actual:
![image](https://user-images.githubusercontent.com/45556620/55009254-4d0f3400-4ff3-11e9-896f-5100c04b8460.png)

**Comment by kaminskyelina** [comment]
In each product we should print each components build number

**Comment by sasha-abramovich** [comment]
Unassigned myself, no action item for me AFAIK

**Comment by Denis-Asipenko** [comment]
checked

**Comment by Denis-Asipenko** [comment]
@roman-strilets We need to add the lib version to the logs.

**Comment by Denis-Asipenko** [comment]
checked
