### ISSUE TITLE
Cannot login in Flight Mode

### ISSUE THREAD

**Issue by kaminskyelina** [BeamMW/android-wallet#168]
Cannot login to the Beam wallet when the device in Flight Mode

**Scenario**
1. Turn Flight Mode on
2. Open Beam wallet and login

**Result**
The wallet stacks in "Loading wallet" state

**Expected result**
Login in offline mode 

Note: After I disable Flight Mode, I cannot login, I need to reopen Beam wallet application

**Comment by kaminskyelina** [comment]
Should be same behaviour for iOS, Android and Desktop.

**Comment by kaminskyelina** [comment]
Hi , sorry for confusing
no need to login - just show error msg "no internet connection"

**Comment by vain-onnellinen** [comment]
why? desktop guys said that user should have possibility to login without internet too. Was something changed?

**Comment by kaminskyelina** [comment]
right - no need, only error

**Comment by Denis-Asipenko** [comment]
The message "Error.no internet connection" doesn't display within three minutes.

**Comment by sasha-abramovich** [comment]
a message like "Incorrect node name or no Internet connection" should be displayed.

**Comment by Denis-Asipenko** [comment]
On IOS wallet displaying a message "Error.no internet connection". Can we leave the same message for Android? @sasha-abramovich what do you think?

**Comment by roman-strilets** [comment]
fixed in SHA-1: 4f5f9180a20da69ddd9297f7b936623cafd07850

**Comment by Denis-Asipenko** [comment]
checked
