### ISSUE TITLE
Finger Print for Android

### ISSUE THREAD

**Issue by kaminskyelina** [BeamMW/android-wallet#170]

**Comment by alexandrashelenkova** [comment]
Added enable fingerprint in settings zpl.io/bJ7ALpx, removed fingerprint icon from password screen cause in android it's not required.

**Comment by Denis-Asipenko** [comment]
Need to add the possibility of confirmation send transactions using a fingerprint.

**Comment by gingervik** [comment]
1. enter with fingerprint - checked
2. settings - checked
3. confirmation send transaction with fingerprint - checked
