### ISSUE TITLE
Translation-pt-br

### ISSUE THREAD

**Issue by hanelore** [BeamMW/android-wallet#171]
Hi.

What would be the best way to start the translation?

Thanks.

**Comment by vain-onnellinen** [comment]
Hello.

All text resources are collected here:
https://github.com/BeamMW/android-wallet/blob/master/app/src/main/res/values/strings.xml

So, to translate app into other language you need to create additional resource folder with the same file (like above) inside. The explanation is here: 
https://developer.android.com/training/basics/supporting-devices/languages

Then you should change all values (not keys) in your new file according language you want to implement. For example:
was:
 <string name="nav_wallet">Wallet</string>

become:
 <string name="nav_wallet">Billetera</string>

Then just build and run the app. New language will be automatically applied if you mobile phone has it installed like currently using.

**Comment by hanelore** [comment]
Thanks @vain-onnellinen I will translate. Thanks.

**Comment by hanelore** [comment]
Finally PR sent: https://github.com/BeamMW/android-wallet/pull/199

Thanks again.
