### ISSUE TITLE
Handle application on background and screen off and handle incoming transactions when the app is not active

### ISSUE THREAD

**Issue by kaminskyelina** [BeamMW/android-wallet#172]
**Description**
Today, few minutes in background or screen off - the process goes down
The user should be with Application active till transaction is completed 

**Describe the solution you'd like**
Wake up every 30 min, and send pop - up once transaction received
(to be same as in iOS)

**Comment by Denis-Asipenko** [comment]
in this case, when you click on all notifications, we need to transfer the user to the screen with transactions(wallet screen)
![image](https://user-images.githubusercontent.com/45556620/58800310-2fbc9e80-8610-11e9-95d5-4e16568c76ac.png)
if a user clicks on a specific notification, we transfer it to the screen with the details of that transaction.
![image](https://user-images.githubusercontent.com/45556620/58800473-9f328e00-8610-11e9-99d4-4ee8462760ea.png)

**Comment by Denis-Asipenko** [comment]
checked
