### ISSUE TITLE
Alert for user that he should stay online and active when send/receive Beam

### ISSUE THREAD

**Issue by kaminskyelina** [BeamMW/android-wallet#178]
**Description**
In mobile wallets, once the application goes to the background or in screen off - the process goes sleep. In this case transactions cannot handled

Awake once in 30 min and pop-up messages is not a guarantee, since after some time in screen off also the internet disconnects

Sasha suggests to design user alert in the wallet that ask to stay online

**Comment by alexandrashelenkova** [comment]
Duplicate of that task https://github.com/BeamMW/android-wallet/issues/191
