### ISSUE TITLE
Export transactions history to the file

### ISSUE THREAD

**Issue by kaminskyelina** [BeamMW/android-wallet#186]
Export in CSV format, according to the order that in the wallet
Share via share menu
Save file (Open question for Android about permissions)

**Comment by Denis-Asipenko** [comment]
The export file should look like this
![image](https://user-images.githubusercontent.com/45556620/56500855-1e627b80-6515-11e9-9241-393364f41c9b.png)
Actual:
![image](https://user-images.githubusercontent.com/45556620/56500909-5d90cc80-6515-11e9-9586-f18d56ddeb24.png)

**Comment by Denis-Asipenko** [comment]
Сolumns "transaction fee" and "transaction ID" not true.
![image](https://user-images.githubusercontent.com/45556620/56895316-722f1080-6a91-11e9-8f18-bdda28cbc121.png)
![image](https://user-images.githubusercontent.com/45556620/56895399-b6baac00-6a91-11e9-8387-798153594657.png)

**Comment by Denis-Asipenko** [comment]
![image](https://user-images.githubusercontent.com/45556620/57083700-a6106d00-6d01-11e9-91bd-d3f50accc439.png)

**Comment by Denis-Asipenko** [comment]
checked
