### ISSUE TITLE
Hide amounts when sending money face-2-face

### ISSUE THREAD

**Issue by kaminskyelina** [BeamMW/android-wallet#188]
Use case: Hide amounts when sending money face-2-face

Use case: Hide amounts when sending money face-2-face

Default is unlocked
Enable/Disable in any time in screen that shows balance (Main and Send)
Hide balance only everywhere
Аfter button toggle - back to regular view
After wallet reset - back to default (unlocked)

**Comment by alexandrashelenkova** [comment]
Screens are here zpl.io/blDpMY1
zpl.io/V1lmB4X
zpl.io/25JqpD3
zpl.io/VOmQmXr

**Comment by alexandrashelenkova** [comment]
Decided with Sasha that secret mode won't affect utxo screen by now, links on screens are above

**Comment by Denis-Asipenko** [comment]
when activated, security mode in the line  "in progress"  incorrectly displayed of elements.
![image](https://user-images.githubusercontent.com/45556620/57086956-c80cee00-6d07-11e9-9715-5c21e8c0fb54.png)

**Comment by Denis-Asipenko** [comment]
checked
