### ISSUE TITLE
Autocompletion of seed phrase

### ISSUE THREAD

**Issue by kaminskyelina** [BeamMW/android-wallet#189]
1. Once user started to print and the word suggest completion
2. When user tap on suggestion, complete and jump to the next word
3. On the last word the cursor doesn't jump
4. If user doesn't tap on suggested word , the cursor will not jump, he will need to move to next tab manually

**Comment by kaminskyelina** [comment]
what happens with short words (3-4 chars) ?

**Comment by vain-onnellinen** [comment]
almost all  keyboards have autocomplete feature (suggesting a word by user input), why do we need to implement it manually?

**Comment by alexandrashelenkova** [comment]
It was explained today

**Comment by Denis-Asipenko** [comment]
checked
