### ISSUE TITLE
Connect to specific node from mobile wallet

### ISSUE THREAD

**Issue by kaminskyelina** [BeamMW/android-wallet#190]

**Comment by Denis-Asipenko** [comment]
Bug 1: When you tap on the switcher, the node address editing window appears.
Bug 2: It is forbidden to enter characters other than numbers after the colon in the port number. Allow input from 1 to 65535 .0 and everything greater than 65535 to make invalid.

**Comment by Denis-Asipenko** [comment]
Please make so as it is implemented on desktop wallet.
![image](https://user-images.githubusercontent.com/45556620/58621980-493dad80-82d3-11e9-9ccc-dcb7bf8f2e40.png)
![image](https://user-images.githubusercontent.com/45556620/58622003-55c20600-82d3-11e9-8457-546f9be4ea07.png)

**Comment by Denis-Asipenko** [comment]
checked
