### ISSUE TITLE
Notification to stay online on mobile (or on receive screen)

### ISSUE THREAD

**Issue by kaminskyelina** [BeamMW/android-wallet#191]

**Comment by dariatarakanova** [comment]
Send screen https://zpl.io/agQzqQO
Receive screen https://zpl.io/aX3PdqP

**Comment by Denis-Asipenko** [comment]
Will be checked later.
[Handle application on background and screen off and handle incoming transactions when the app is not active](https://github.com/BeamMW/android-wallet/issues/172)

**Comment by Denis-Asipenko** [comment]
invalid
