### ISSUE TITLE
Categories for addresses and transactions

### ISSUE THREAD

**Issue by kaminskyelina** [BeamMW/android-wallet#192]

**Comment by alexandrashelenkova** [comment]
Added categories screens in addresses and settings sections:
https://app.zeplin.io/project/5ba9be48f029d520c456f395/dashboard?seid=5c518b1f5420114200108193
https://app.zeplin.io/project/5ba9be48f029d520c456f395/dashboard?seid=5c0fd3b3a15cd3246e93927e

**Comment by alexandrashelenkova** [comment]
@Miolin please add confirmation for deleting categories (screen is here https://zpl.io/VQv3OQm) and "None" category in the list (https://zpl.io/a8p3OoJ)

**Comment by Denis-Asipenko** [comment]
![image](https://user-images.githubusercontent.com/45556620/58623008-a6d2f980-82d5-11e9-907d-40761ec4aa43.png)
![image](https://user-images.githubusercontent.com/45556620/58623036-b5211580-82d5-11e9-9f99-6db9d386082e.png)

**Comment by Denis-Asipenko** [comment]
![image](https://user-images.githubusercontent.com/45556620/59035416-ebcad300-8875-11e9-9379-26168675def7.png)
![image](https://user-images.githubusercontent.com/45556620/59035425-ef5e5a00-8875-11e9-8473-41c0c630e3b6.png)

**Comment by Denis-Asipenko** [comment]
![image](https://user-images.githubusercontent.com/45556620/60892071-29e95700-a267-11e9-815f-197cfe14cec2.png)

**Comment by Denis-Asipenko** [comment]
When a new category is created, the user is taken to the "Edit category" screen
![image](https://user-images.githubusercontent.com/45556620/61048598-f2a3b300-a3ea-11e9-8492-ea78f641be90.png)
a should go to the "Create category" screen.
![image](https://user-images.githubusercontent.com/45556620/61048653-19fa8000-a3eb-11e9-81d1-77724b497d9d.png)
https://app.zeplin.io/project/5ba9be48f029d520c456f395/screen/5d0b3dcec56a6c70d9465e48

**Comment by Denis-Asipenko** [comment]
when you create a category, the default color is red, and we want the color to be chosen randomly each time we create a category.

**Comment by Denis-Asipenko** [comment]
checked
