### ISSUE TITLE
Send "all" when sending Beam (to avoid coindust)

### ISSUE THREAD

**Issue by kaminskyelina** [BeamMW/android-wallet#193]

**Comment by alexandrashelenkova** [comment]
Design is here zpl.io/VOmQmXr
When user choose "send all" the amount and fee fields should be autocompleted. If user changes fee, the amount should change accordingly

**Comment by Denis-Asipenko** [comment]
@Miolin  When changes fee, the amount doesn't change.

**Comment by Denis-Asipenko** [comment]
Bug: amount changes only when the fee becomes larger.

**Comment by Denis-Asipenko** [comment]
checked
