### ISSUE TITLE
Clear data screen-Delete all addresses,all contacts,all transaction.

### ISSUE THREAD

**Issue by kaminskyelina** [BeamMW/android-wallet#195]

**Comment by alexandrashelenkova** [comment]
Added that in settings (discussed with Sasha yesterday)
zpl.io/blDpEe1
zpl.io/bJ7ALpx

**Comment by Denis-Asipenko** [comment]
@alexandrashelenkova Please add this window in design for Android wallet. Change text from "Are you sure you want to delete all addresses and contacts from your device?" to "Are you sure you want to delete all addresses and contacts from your wallet?" and for IOS wallet design.https://app.zeplin.io/project/5c73dc8aa74b4b4085a86a91/screen/5cb6a194d86e673994b0cfcc
![image](https://user-images.githubusercontent.com/45556620/57793192-6c038a00-7749-11e9-9234-e5b3c8dcef8d.png)
@Miolin Please implement after changes.

**Comment by Denis-Asipenko** [comment]
checked
