### ISSUE TITLE
Link to transactions in blockchain explorer (including switch that allows to "click out" of the app)

### ISSUE THREAD

**Issue by kaminskyelina** [BeamMW/android-wallet#196]

**Comment by dariatarakanova** [comment]
Design with link to Block Explorer https://zpl.io/2pv4NXy
When user clicks on link (Open in Block Explorer) display popup https://zpl.io/2yqOMew and only after clock "Open" Block Explorer opens in browser.

**Comment by Denis-Asipenko** [comment]
doesn't display popup https://zpl.io/2yqOMew
![image](https://user-images.githubusercontent.com/45556620/57914406-3ec4f200-7897-11e9-92d5-92b7cf82a049.png)

**Comment by Denis-Asipenko** [comment]
@iscander01 When tapping on a link make redirects to the kernel ID

**Comment by iscander01** [comment]
@Denis-Asipenko done

**Comment by Denis-Asipenko** [comment]
сhecked on testnet. 
version:2.1.6
