### ISSUE TITLE
All UI elements must be adapted to Zoomed Display View

### ISSUE THREAD

**Issue by Denis-Asipenko** [BeamMW/android-wallet#200]
Description
When Display View is set to Zoomed, the UI elements do not appear in the appliacation. We need all UI elements adapted to Zoomed Display View.
Steps:
1. Go to Android Settings > Display>Advanced
2. Set Front size = Large
3. Set Display size = Large
Actual:
![image](https://user-images.githubusercontent.com/45556620/56363628-5dcb5800-61f5-11e9-96ed-c94c6af9cb44.png)
![image](https://user-images.githubusercontent.com/45556620/56363664-6de33780-61f5-11e9-9782-22f20273d7b7.png)
![image](https://user-images.githubusercontent.com/45556620/56363690-789dcc80-61f5-11e9-8e0e-1d7fa082d30c.png)
![image](https://user-images.githubusercontent.com/45556620/56364057-5bb5c900-61f6-11e9-9c9c-2fbe97ce79dd.png)
![image](https://user-images.githubusercontent.com/45556620/56364419-2bbaf580-61f7-11e9-9b42-0c28e23c8bdb.png)
![image](https://user-images.githubusercontent.com/45556620/56364456-3ffef280-61f7-11e9-83e6-0d3f1f3a305c.png)

**Comment by Denis-Asipenko** [comment]
![image](https://user-images.githubusercontent.com/45556620/56568725-42c76200-65c0-11e9-959f-e229cbd3a892.png)
![image](https://user-images.githubusercontent.com/45556620/56568752-5246ab00-65c0-11e9-8993-a333026745a1.png)
![image](https://user-images.githubusercontent.com/45556620/56568785-62f72100-65c0-11e9-82d3-20bb13a1c9fe.png)
![image](https://user-images.githubusercontent.com/45556620/56568827-76a28780-65c0-11e9-9f3b-2e675f6e7700.png)
![image](https://user-images.githubusercontent.com/45556620/56568859-88842a80-65c0-11e9-9f73-e7e5f754bbe2.png)
When you turn on the zoom mode it is necessary to align centrally screen.
![image](https://user-images.githubusercontent.com/45556620/56568908-a0f44500-65c0-11e9-9805-614f23472ee8.png)
![image](https://user-images.githubusercontent.com/45556620/56568940-b0738e00-65c0-11e9-9daa-983b8e264355.png)
![image](https://user-images.githubusercontent.com/45556620/56568981-c5502180-65c0-11e9-8607-f1df32e37d5d.png)

**Comment by jurijakimuk** [comment]
A couple things left to fix in the zoom mode:
1) Fit the word "CANCEL"
![image](https://user-images.githubusercontent.com/41323026/57088451-f93aed80-6d0a-11e9-90c9-77a3d2d4f9eb.png)

2) Fit the amounts
![image](https://user-images.githubusercontent.com/41323026/57088480-11127180-6d0b-11e9-8f25-84abb768f112.png)

**Comment by Denis-Asipenko** [comment]
![image](https://user-images.githubusercontent.com/45556620/57125955-06e88580-6d94-11e9-84fa-6aef006743cc.png)

**Comment by Denis-Asipenko** [comment]
![image](https://user-images.githubusercontent.com/45556620/57515571-a620f600-731b-11e9-9b1e-b7dab086666c.png)
![image](https://user-images.githubusercontent.com/45556620/57515586-ab7e4080-731b-11e9-9c3d-8f3f1698d14d.png)
![image](https://user-images.githubusercontent.com/45556620/57515909-5e4e9e80-731c-11e9-84c8-87d79e6d8488.png)
![image](https://user-images.githubusercontent.com/45556620/57515929-673f7000-731c-11e9-8bff-178580b058fc.png)

**Comment by Denis-Asipenko** [comment]
![image](https://user-images.githubusercontent.com/45556620/57527308-fefe8780-7337-11e9-992c-1a4052b7343d.png)
![image](https://user-images.githubusercontent.com/45556620/57527348-18073880-7338-11e9-855a-ce764cd46e93.png)

**Comment by Denis-Asipenko** [comment]
![image](https://user-images.githubusercontent.com/45556620/58692728-e82bdd80-8397-11e9-86cc-8b732daa18f3.png)
![image](https://user-images.githubusercontent.com/45556620/58692890-41940c80-8398-11e9-804f-07fec310eb8b.png)
![image](https://user-images.githubusercontent.com/45556620/58692943-5d97ae00-8398-11e9-9976-baaf95d96f5d.png)

**Comment by Denis-Asipenko** [comment]
checked
