### ISSUE TITLE
Login to another wallet -Make a button on the main screen for return to the authorizations screen.

### ISSUE THREAD

**Issue by Denis-Asipenko** [BeamMW/android-wallet#203]
Description:
For the user, it would be intuitive to find a button on the main screen to return to the screen with authorization, and not click the arrow "back" at the device.
Steps to reproduce the behaviour:
Wallet is instaled and closed.
1. Go to wallet
2. Click a button "login to another wallet" at authorizations screen. 
3. In the dialogue window click"Change wallet"
4. Return to the authorizations screen with the help clicking the arrow "back" at the device.
![image](https://user-images.githubusercontent.com/45556620/56425132-a8170c80-62bb-11e9-95c3-cba325ad2012.png)

**Comment by dariatarakanova** [comment]
android https://zpl.io/beAWXON

**Comment by sasha-abramovich** [comment]
related to #36, will be implemented altogether with #36
