### ISSUE TITLE
Show Kernel ID and not Transaction ID in UTXO details

### ISSUE THREAD

**Issue by kaminskyelina** [BeamMW/android-wallet#204]
It was decided by Sasha to show Kerner ID and not Transaction ID in UTXO screen

@alexandrashelenkova  please change also in the design, so it will not confuse in future

**Comment by vain-onnellinen** [comment]
do we need to show kernelId of transaction in which UTXO was created or spent?

**Comment by dariatarakanova** [comment]
Design here: https://zpl.io/29wO7Zd

**Comment by Denis-Asipenko** [comment]
checked
