### ISSUE TITLE
Settings screen - doesn't request the password when disables function.

### ISSUE THREAD

**Issue by Denis-Asipenko** [BeamMW/android-wallet#206]
When the user disables the   "Ask for password on every send" and "Enable fingerprint unlock" need to request a password.

**Comment by gingervik** [comment]
Please, rename  Password **should** not be empty to Password **can not** be empty

**Comment by gingervik** [comment]
checked

**Comment by gingervik** [comment]
Please, also change tha same line in confirmation transaction dialog
![image](https://user-images.githubusercontent.com/28015224/57125132-dfdc8480-6d90-11e9-81f5-ab59ff7eb55a.png)

**Comment by Denis-Asipenko** [comment]
Please, also change that same line in change password.Also, please review all the screens where you need to enter a password and change this line.
![image](https://user-images.githubusercontent.com/45556620/57135465-2db5b480-6db2-11e9-85fb-e7e2ffa0c37a.png)
![image](https://user-images.githubusercontent.com/45556620/57135475-360def80-6db2-11e9-9e17-959b0f8d6d57.png)

**Comment by Denis-Asipenko** [comment]
At "Change password" screen.
![image](https://user-images.githubusercontent.com/45556620/57516504-8559a000-731d-11e9-8f91-d932aeb85d30.png)

**Comment by Denis-Asipenko** [comment]
checked
