### ISSUE TITLE
It is impossible to take a screenshot on the screens.

### ISSUE THREAD

**Issue by Denis-Asipenko** [BeamMW/android-wallet#209]
Description:
Only on the" start phrase " screen the ability to take a screenshot should be disabled. On all other screens, the user can take a screenshot.
Steps to behaviour to reproduce:
Precondition: app installed.
1. Go to wallet.
2. Tap button "create new wallet"
3. Go to the screen "seed phrase" and try to make screenshot. Screenshot can't be done.
4. Go back to the previous screen and take a screenshot.
Expected: Screenshot can be done.
Actual: Screenshot can't be done.

**Comment by gingervik** [comment]
Only on Seed phrase screen screenshot should be forbiden
For now it's also forbiden on Confirm seed phrase screen

**Comment by gingervik** [comment]
Checked
