### ISSUE TITLE
Limit maximum amount of Beams to send

### ISSUE THREAD

**Issue by jurijakimuk** [BeamMW/android-wallet#211]
**Describe the bug**
Currently there's no limitation of how many Beams user can enter in the **Receive** screen in the Android mobile wallet, e.g. one can enter "545444888799797999996669699999990000000000008888888882555555555555553333333333333338888888888880000000002222222" Beams.
When QR code is generated this enormous amount is not displayed on the sender's side.
Please, limit the amount to 262,800,000 Beams. 
Also make sure the maximum amount must be reduced accordingly to how many groths are entered in the Fee field.
![image](https://user-images.githubusercontent.com/41323026/57085847-b75b7880-6d05-11e9-8f61-a6cf9391e8c3.png)

Please, apply the same logic to the **Send** screen.
It's not possible to send 262 800 000 Beams, there're different limitation rules applied. 
![image](https://user-images.githubusercontent.com/41323026/57086041-15885b80-6d06-11e9-97e8-63071b7e3675.png)

**Comment by Denis-Asipenko** [comment]
checked
