### ISSUE TITLE
Login / restore screen updates

### ISSUE THREAD

**Issue by alexandrashelenkova** [BeamMW/android-wallet#218]
On following screens change restore button to a link:
https://zpl.io/aXkM95M
https://zpl.io/brllDmr

Text fixes
https://zpl.io/Vqllp6l
https://zpl.io/aX3w0AE

Rename button:
https://zpl.io/Vql6koY

**Comment by Denis-Asipenko** [comment]
> Rename button:
https://zpl.io/Vql6koY

>
done
The rest applies to the recovery of the purse. Will be implemented in Bright Boson 2.3

**Comment by Denis-Asipenko** [comment]
design:
https://app.zeplin.io/project/5ba9be48f029d520c456f395/screen/5bcf91bc6ab2640ac579cfe9
![image](https://user-images.githubusercontent.com/45556620/63260898-d701b700-c28a-11e9-8b2a-b5b7a192f4fa.png)
https://app.zeplin.io/project/5ba9be48f029d520c456f395/screen/5bccd401df29ce0aa9cc2515
![image](https://user-images.githubusercontent.com/45556620/63261083-3fe92f00-c28b-11e9-82ba-0a75846feab4.png)
actual:
![image](https://user-images.githubusercontent.com/45556620/63261004-17f9cb80-c28b-11e9-8e0f-853bd6bd134c.png)
![image](https://user-images.githubusercontent.com/45556620/63261194-82ab0700-c28b-11e9-8ebf-c746f1bd0720.png)

**Comment by Denis-Asipenko** [comment]
checked
