### ISSUE TITLE
Language settings

### ISSUE THREAD

**Issue by alexandrashelenkova** [BeamMW/android-wallet#220]
zpl.io/bPxyrEx
zpl.io/bJ7ALpx
English language should always be on top of the list (even if not selected). By default app should use device language (if supported), if not supported - english.

**Comment by sasha-abramovich** [comment]
before starting this one - let's discuss with @anatolse - to sync the language engine across the platforms

**Comment by sasha-abramovich** [comment]
@Miolin in case only 1 language is installed the languages switch should not be presented in the Settings

**Comment by Denis-Asipenko** [comment]
irrelevant
