### ISSUE TITLE
Send screen - snackbar for UNDO send tx 

### ISSUE THREAD

**Issue by dariatarakanova** [BeamMW/android-wallet#224]

**Comment by dariatarakanova** [comment]
https://zpl.io/VQvL70P

**Comment by Denis-Asipenko** [comment]
![image](https://user-images.githubusercontent.com/45556620/59034598-fe440d00-8873-11e9-9b29-949c65528df2.png)
![image](https://user-images.githubusercontent.com/45556620/59034589-f8e6c280-8873-11e9-9c90-db424f30335b.png)

**Comment by Denis-Asipenko** [comment]
progress bar doesn't decrease when the timer expires in snackbar.

**Comment by Denis-Asipenko** [comment]
checked
