### ISSUE TITLE
Owner's key

### ISSUE THREAD

**Issue by alexandrashelenkova** [BeamMW/android-wallet#225]
Add ability to see and copy/share owner's key in settings. Ask password or fingerprint/face id before showing it. Add alert that showing that key will show all your transactions on other devices where it will be implemented.

**Comment by dariatarakanova** [comment]
Owner key
https://app.zeplin.io/project/5ba9be48f029d520c456f395/dashboard?seid=5ced30bf7955401e2f10f7d8

**Comment by Denis-Asipenko** [comment]
Change text when entering the wrong password: " The old password you have entered is incorrect" on "Current password is incorrect"
![image](https://user-images.githubusercontent.com/45556620/60886773-7890f400-a25b-11e9-9e53-5eebe2d81420.png)

**Comment by Denis-Asipenko** [comment]
checked
