### ISSUE TITLE
Default confirmation

### ISSUE THREAD

**Issue by alexandrashelenkova** [BeamMW/android-wallet#227]
Please find the design below in the comments

**Comment by sasha-abramovich** [comment]
In transaction details we need to display the number of confirmations anyways. 
also, 10 is just an example. 

@RaFuN what is the usual confirmations number from exchanges?

**Comment by sasha-abramovich** [comment]
just talked to @RaFuN he said that 6 is a good default (albeit some exchanges have it up to 60). In general, if someone tries to send the money that involve unconfirmed UTXO he should get a warning. For that we also need a dialog.

**Comment by sasha-abramovich** [comment]
as a part of this task let's also display the actual confirmations number in transaction details
also, when trying to send a transaction that uses UTXO with less confirmations than the threshold user should receive a warning

**Comment by dariatarakanova** [comment]
https://app.zeplin.io/project/5ba9be48f029d520c456f395/dashboard?seid=5cf1193a156b3d1dd4f28fc0

+warning (need to design)

**Comment by Denis-Asipenko** [comment]
@dariatarakanova I think it would be more correct for android to show like this
![image](https://user-images.githubusercontent.com/45556620/136029210-2cc72879-efba-4316-8a81-0d625ede0f3f.png)

> 7. "Minimum confirmations" popup https://zpl.io/aRx3ORz
>    ![image](https://user-images.githubusercontent.com/47353570/132688737-77de090f-5e44-4689-8680-089996c5fd7f.png)

**Comment by dariatarakanova** [comment]
@Denis-Asipenko yes, you are correct. I am sorry, there is the wrong link. Here is the correct link for android https://zpl.io/agWYeoR
![image](https://user-images.githubusercontent.com/47353570/136186483-b996c114-615d-4769-a393-4e1379a9fff8.png)

**Comment by KatsiarynaV** [comment]
1. Status "confirming (x/x)" should be displayed when confirmation is in process. First transaction is "in progress" status, then "confirming (x/x)", and then "received"
![10](https://user-images.githubusercontent.com/68267190/139650107-ba75c347-2b22-4565-b728-0c5d7713c1af.jpg)

Now there is no "in progress" status, transaction appears with "cofirming(x/x)" status and then changes to "received"

https://user-images.githubusercontent.com/68267190/139649687-bffbe711-a075-4758-804d-5bcca490f66a.mp4

2. For sender there shouldn't be  "confirming (x/x)" status, just "in progress" and "sent"
![sending](https://user-images.githubusercontent.com/68267190/139650840-66d04a1e-c1c8-4566-bfda-90596c92b3a3.jpg)

**Comment by KatsiarynaV** [comment]
Checked
