### ISSUE TITLE
Share transaction details

### ISSUE THREAD

**Issue by dariatarakanova** [BeamMW/android-wallet#229]
Think about what details we can share and what - we can't

**Comment by dariatarakanova** [comment]
https://zpl.io/a3l75RW
https://zpl.io/2jMwm36 - this screen should be an image. 

Flow:
1) user clicks on "share details" https://zpl.io/a3l75RW
2) generate img the same as on design https://zpl.io/2jMwm36 with transaction details
3) img can be sent in telegram, mail etc

**Comment by Denis-Asipenko** [comment]
- The ability to share transaction details should be available in the following statuses(transaction stages):

https://app.zeplin.io/project/5b379c2c38cb39e73e5f8889/screen/5d0caf09627ac8566a69540a
![image](https://user-images.githubusercontent.com/45556620/63330573-b72acb80-c33c-11e9-81a9-02a9886f8598.png)
Actual:
![image](https://user-images.githubusercontent.com/45556620/63330972-65cf0c00-c33d-11e9-82cb-504c68b7feb7.png)
![image](https://user-images.githubusercontent.com/45556620/63331677-d9254d80-c33e-11e9-8c96-a3be4097098d.png)
![image](https://user-images.githubusercontent.com/45556620/63331566-9f544700-c33e-11e9-92a3-5fc5b1b4fb42.png)

- At the moment we can not correctly specify this information so it should not be displayed. the color background of the picture is supposed to be according to the network(masternet,testnet,mainnet)

![image](https://user-images.githubusercontent.com/45556620/63331805-1f7aac80-c33f-11e9-91a5-94da2d52102a.png)

**Comment by Denis-Asipenko** [comment]
![image](https://user-images.githubusercontent.com/45556620/63424261-b36b7780-c416-11e9-9a5b-67fdfefd0c1e.png)

**Comment by Denis-Asipenko** [comment]
checked
