### ISSUE TITLE
send / receive screens redesign

### ISSUE THREAD

**Issue by alexandrashelenkova** [BeamMW/android-wallet#231]
New version of send/receive screes are here:
send https://app.zeplin.io/project/5ba9be48f029d520c456f395/dashboard?seid=5cee6dd12f02be1d5003768c

receive https://app.zeplin.io/project/5ba9be48f029d520c456f395/dashboard?seid=5cee7c2d4c7fea1d62dc3144

**Comment by Denis-Asipenko** [comment]
need change the text in receive and send screen
![image](https://user-images.githubusercontent.com/45556620/60812985-6485bd80-a19b-11e9-8215-c2b4aa54bafe.png)
![image](https://user-images.githubusercontent.com/45556620/60812998-6a7b9e80-a19b-11e9-9eb1-b48e027a2447.png)

**Comment by Denis-Asipenko** [comment]
checked
