### ISSUE TITLE
Transaction search

### ISSUE THREAD

**Issue by alexandrashelenkova** [BeamMW/android-wallet#233]
https://zpl.io/2GOg03E
https://zpl.io/boMkRYv
https://zpl.io/bJGNzO3

**Comment by Denis-Asipenko** [comment]
@Miolin make changes according to the design
https://app.zeplin.io/project/5ba9be48f029d520c456f395/screen/5cc2c67bd3744f2de5428dfc
![image](https://user-images.githubusercontent.com/45556620/63573673-9bb6ff00-c58e-11e9-8317-80d88d9c6a90.png)

**Comment by Denis-Asipenko** [comment]
@Miolin Transaction search should search for the first 6 characters in the address

**Comment by Denis-Asipenko** [comment]
- **Doesn't search by contact name**
![image](https://user-images.githubusercontent.com/45556620/63840613-06e74380-c98a-11e9-8eba-1626ea7355f3.png)
![image](https://user-images.githubusercontent.com/45556620/63840635-149cc900-c98a-11e9-8361-13aa441481e3.png)

- **Design:**

![image](https://user-images.githubusercontent.com/45556620/63840922-837a2200-c98a-11e9-8686-d70fc25a4f52.png)
  Actual:
![image](https://user-images.githubusercontent.com/45556620/63840758-43b33a80-c98a-11e9-84d3-939374152a53.png)

- **Transaction ID and addresses are displayed with a transaction comment icon**
![image](https://user-images.githubusercontent.com/45556620/63841943-62b2cc00-c98c-11e9-8be4-fe980e634fff.png)
![image](https://user-images.githubusercontent.com/45556620/63842108-b1606600-c98c-11e9-9e41-7914d0cd2c68.png)

- **To forbid to enter multiple rows(a column)**
![image](https://user-images.githubusercontent.com/45556620/63842265-f5536b00-c98c-11e9-8fc1-703de7ca1d73.png)

**Comment by Denis-Asipenko** [comment]
Must separate the search string and the transaction string by changing the color alternation. For example, the search string is gray, and the first line with the transaction was black.
![image](https://user-images.githubusercontent.com/45556620/64009802-367c8400-cb21-11e9-8eec-0b9f0bc2cead.png)

**Comment by Denis-Asipenko** [comment]
@Miolin please apply this design to the masternet and testnet.
https://app.zeplin.io/project/5ba9be48f029d520c456f395/screen/5d6d265639bbe3139a1203e2
![image](https://user-images.githubusercontent.com/45556620/64121584-e531f600-cda7-11e9-99ba-e9d03ff6e1f1.png)
https://app.zeplin.io/project/5ba9be48f029d520c456f395/screen/5d6d265450db6d73805e9cdf
![image](https://user-images.githubusercontent.com/45556620/64121678-38a44400-cda8-11e9-8e8c-0673a56cf74c.png)

**Comment by Denis-Asipenko** [comment]
- Make it so that when you open the focus was on the line "Search"
- Please increase the area of tapping "x"

**Comment by Denis-Asipenko** [comment]
checked
