### ISSUE TITLE
Settings screen - doesn't request the password when disables function.

### ISSUE THREAD

**Issue by alexandrashelenkova** [BeamMW/android-wallet#236]
When the user disables the "Ask for password on every sending transaction" need to request a password.

**Comment by Denis-Asipenko** [comment]
https://github.com/BeamMW/android-wallet/issues/206

**Comment by dariatarakanova** [comment]
Please just change text "Enter your current password" to "Enter your current password to proceed changes in settings" on screen with password (Settings -> Ask for password on every Send -> Password).

**Comment by Denis-Asipenko** [comment]
checked
