### ISSUE TITLE
The numbers on the seed phrase should be more contrast as they are not very visible in the dark

### ISSUE THREAD

**Issue by alexandrashelenkova** [BeamMW/android-wallet#239]
Updated screens here
https://zpl.io/aXkWmlg
https://zpl.io/bA4GDPq
https://zpl.io/aREN9nz

**Comment by Denis-Asipenko** [comment]
on the confirmation screen, make the numbers more contrast 
![image](https://user-images.githubusercontent.com/45556620/60887778-df171180-a25d-11e9-95d9-b0b345d25655.png)
how it's done here
![image](https://user-images.githubusercontent.com/45556620/60887848-fce47680-a25d-11e9-9863-00b5e64524ce.png)

**Comment by sasha-abramovich** [comment]
![image](https://user-images.githubusercontent.com/44961099/60894759-8495a980-a28d-11e9-8fce-83cdcaec11cd.png)
@alexandrashelenkova in the next version let's see if  we can do  something so that only one word won't be left on the new line.

**Comment by alexandrashelenkova** [comment]
@sasha-abramovich I think just move "в поля" to the last line too.

**Comment by Denis-Asipenko** [comment]
Please, make the numbers more contrast all the time, not only when the user enters the phrase. It will be more convenient for the user when the screen backlight is minimal.
![image](https://user-images.githubusercontent.com/45556620/61062763-74a1d500-a407-11e9-8d28-4459716b56cc.png)

**Comment by Denis-Asipenko** [comment]
checked
