### ISSUE TITLE
When "Send all" is pressed, the amount is still less than the balance

### ISSUE THREAD

**Issue by alexandrashelenkova** [BeamMW/android-wallet#242]
Added hint under the amount field here https://zpl.io/2pMvWqy
By now it would be just transaction fee, after we add exchange rate, transaction fee would be shown in breaks.

**Comment by Denis-Asipenko** [comment]
If transaction fee=0 the need to remove "+"
Example: 0 GROTH transaction fee
![image](https://user-images.githubusercontent.com/45556620/60872573-92bbd980-a23d-11e9-931a-cdc9912c33dd.png)

**Comment by Denis-Asipenko** [comment]
If transaction fee=0 the need to remove "+"
Example: 0 GROTH transaction fee
![image](https://user-images.githubusercontent.com/45556620/61207957-0444cd80-a6ff-11e9-8593-4029d2fe7133.png)

**Comment by Denis-Asipenko** [comment]
when you change the transaction fee, the changes are not displayed(amount and hint)
[video.zip](https://github.com/BeamMW/android-wallet/files/3402743/video.zip)

**Comment by Denis-Asipenko** [comment]
checked
