### ISSUE TITLE
There should be an easier way to create the first category

### ISSUE THREAD

**Issue by alexandrashelenkova** [BeamMW/android-wallet#243]
If categories list is empty drop down should looks like that https://zpl.io/a89egL6
Add note under categories field (only if categories list isn't empty already) https://zpl.io/agzO4oZ

**Comment by Denis-Asipenko** [comment]
![image](https://user-images.githubusercontent.com/45556620/60893819-4470ff80-a26a-11e9-9701-d7ee4679d9aa.png)

**Comment by Denis-Asipenko** [comment]
Steps to reproduce the behaviour:
1. go to "Send" screen.
2. Select "Advanced".
3. Select "Edit address".
4. In "Category" select "Add new category"
5. On the "create category" screen, tap the back arrow.
6. Repeat step 4 again.
Actual: after tapping on "add new category", the "Create category" screen does not open. Opens only after tapping again.

**Comment by Denis-Asipenko** [comment]
checked
