### ISSUE TITLE
Receive screen

### ISSUE THREAD

**Issue by alexandrashelenkova** [BeamMW/android-wallet#248]
- Transaction comment is missing
- address field should have "ADDRESS"/"ADDRESS (autogenerated)" header
- None category (in edit address section) shouldn't have empty circle on the left of "None"
- "Optional" is missing in "Request an amount" header
- when focus is on any field, screen should scroll so that field would be visible (not hidden behind keyboard)
- share icon is bigger than QR icon (they should be same, please look at the design)
- "BEAM" currency next to amount field should be same font size as on Send screen
- amount font should be Roboto Light
- "auto-generated" in address header shouldn't be in capital letters
- add "No name" hint in Name field in edit address section (if no name entered)
- on QR screen address field should have "ADDRESS"/"ADDRESS (auto-generated)" header, QR should be in capital letters
- when Change addresses screen is open, existing addresses should be shown right away, not after input anything in the input field
- addresses without name should have "No name" name
- input fields should have same paddings, headers and status should be all aligned to same vertical line on the left, drop down arrows should be aligned to same vertical line on the right as input fields (screenshot attached)

**Comment by alexandrashelenkova** [comment]
<img width="455" alt="Screenshot 2019-07-08 at 21 35 51" src="https://user-images.githubusercontent.com/7249484/60815647-aa0daf00-a1ca-11e9-8cef-ef6171bf861d.png">

**Comment by Denis-Asipenko** [comment]
Must be one color-white
![image](https://user-images.githubusercontent.com/45556620/61209212-c4cbb080-a701-11e9-83e3-c6b794b447e6.png)

**Comment by Denis-Asipenko** [comment]
Transaction comment is missing
![image](https://user-images.githubusercontent.com/45556620/61443952-233b9d80-a953-11e9-9cd5-cb26d0951f01.png)

**Comment by Denis-Asipenko** [comment]
checked
