### ISSUE TITLE
Send screen

### ISSUE THREAD

**Issue by alexandrashelenkova** [BeamMW/android-wallet#249]
- "+... GROTH" hint should appear under amount field only if some amount inputed
- amount font should be Roboto Light
- "TRANSACTION COMMENT" header should be in capital letters
- when tap "Send all" button with 0 balance, show alert "Amount field can't be empty" right away, not after tapping "Next" button
- amount font should be Roboto Light
- add "No name" hint in Name field in edit address section (if no name entered)
- in transactions fee popup input field and header should be all aligned to same vertical line on the left, close icon should be smaller (24x24 dp)
- first and last 6 digits of address should be highlighted 
- when address field is in focus, "Search by address, category or name" hint should be shown
- input fields should have same paddings, headers and status should be all aligned to same vertical line on the left, drop down arrows, eye icon should be aligned to same vertical line on the right as input fields (screenshot attached)
- when Change addresses screen is open, existing addresses should be shown right away, not after input anything in the input field
- change text on send confirmation screen before "send" button on "FoR the transaction to complete, the recipient must get online within the next 12 hours and you should get online within 2 hours afterwards."

**Comment by alexandrashelenkova** [comment]
<img width="304" alt="Screenshot 2019-07-08 at 21 52 08" src="https://user-images.githubusercontent.com/7249484/60815839-0b358280-a1cb-11e9-9c72-e2a8eb5c6162.png">

**Comment by Denis-Asipenko** [comment]
display the error immediately after entering the amount, if it more the amount balance. error: Insufficient funds: you would need ... beams to complete the transaction.

**Comment by Denis-Asipenko** [comment]
![image](https://user-images.githubusercontent.com/45556620/61445736-9db9ec80-a956-11e9-8f5a-8796eef7e8e8.png)

**Comment by Denis-Asipenko** [comment]
checked
