### ISSUE TITLE
Highlight word on seed phrase keyboard

### ISSUE THREAD

**Issue by dariatarakanova** [BeamMW/android-wallet#250]
![image](https://user-images.githubusercontent.com/47353570/60870626-e6c4bf00-a239-11e9-9fbe-5a9e2831e7e3.png)

**Comment by alexandrashelenkova** [comment]
1. Make autosuggestion background wider and more noticeable colour, suggested word bigger and medium font https://zpl.io/V4omEJX
2. Add animation of appearing autosuggestion background and word from keyboard.
3. Do not show autosuggestion background if there's no suggested word.
<img width="669" alt="Screenshot 2019-09-18 at 21 16 03" src="https://user-images.githubusercontent.com/7249484/65152070-d874f980-da59-11e9-96e5-98dbcb94d76e.png">

**Comment by Denis-Asipenko** [comment]
checked
