### ISSUE TITLE
Selected expiration should be highlighted

### ISSUE THREAD

**Issue by alexandrashelenkova** [BeamMW/android-wallet#253]
Currently selected item in drop down list isn't highlighted. Correct version of the screen is here https://zpl.io/2pMvWqy

**Comment by alexandrashelenkova** [comment]
<img width="363" alt="Screenshot 2019-08-15 at 12 16 02" src="https://user-images.githubusercontent.com/7249484/63072456-773ba100-bf56-11e9-9449-f6af0eb427d3.png">

**Comment by alexandrashelenkova** [comment]
By now drop-down list might be not under input field, but higher. Please let's fix it later.

**Comment by Denis-Asipenko** [comment]
checked
