### ISSUE TITLE
Adding contact flow

### ISSUE THREAD

**Issue by alexandrashelenkova** [BeamMW/android-wallet#259]
Add + icon on addresses screen https://zpl.io/bWdkA91
Adding contact screen https://zpl.io/aMR9MZK

**Comment by Denis-Asipenko** [comment]
- Add error when QR code does not contain beam address

Example:
![image](https://user-images.githubusercontent.com/45556620/63585873-c57d1f80-c5a8-11e9-9cc0-a857a725d9fd.png)
Actual:
![image](https://user-images.githubusercontent.com/45556620/63585921-da59b300-c5a8-11e9-866c-2e5b3f4d26d2.png)

- Prevent invalid characters from being entered in the contact's address
![image](https://user-images.githubusercontent.com/45556620/63586001-0d03ab80-c5a9-11e9-9ff6-8aaf949b8594.png)

**Comment by Denis-Asipenko** [comment]
Cannot enter some valid characters in an address to create a contact
[video_2019-08-29_15-57-50.zip](https://github.com/BeamMW/android-wallet/files/3559012/video_2019-08-29_15-57-50.zip)

**Comment by Denis-Asipenko** [comment]
should display an invalid address error after the user has moved to another field.
[video_2019-09-03_16-04-06.zip](https://github.com/BeamMW/android-wallet/files/3569544/video_2019-09-03_16-04-06.zip)

**Comment by Denis-Asipenko** [comment]
checked
