### ISSUE TITLE
Rework choose categories screen (for multi-choice)

### ISSUE THREAD

**Issue by alexandrashelenkova** [BeamMW/android-wallet#260]
Change tag view on edit address/contacts view https://zpl.io/2pMvWqy
Change choosing tags flow 
https://zpl.io/aMR9MZK
https://zpl.io/VKyKxwR
https://zpl.io/2v0KROe

**Comment by Denis-Asipenko** [comment]
Categories aren't displayed on the send screen
![image](https://user-images.githubusercontent.com/45556620/63431172-f9c8d280-c426-11e9-84b3-b595cb20e240.png)

**Comment by Denis-Asipenko** [comment]
design:
https://app.zeplin.io/project/5ba9be48f029d520c456f395/screen/5cf7246601603b1d7a8f8b01
![image](https://user-images.githubusercontent.com/45556620/63523649-2eaa5780-c503-11e9-836f-41842c0e9640.png)
actual:
![image](https://user-images.githubusercontent.com/45556620/63523947-c6a84100-c503-11e9-8f16-4da8aa91e7ef.png)

**Comment by Denis-Asipenko** [comment]
Edit address - when you add a tag to an address, some tags aren't selected.
**Note: more than 4 tags were created by the user**
[20190902_171816.zip](https://github.com/BeamMW/android-wallet/files/3566368/20190902_171816.zip)

**Comment by Denis-Asipenko** [comment]
checked
