### ISSUE TITLE
Scan QR from album - very handy from mobile-to-mobile

### ISSUE THREAD

**Issue by alexandrashelenkova** [BeamMW/android-wallet#261]
Updated screen is here https://zpl.io/29OQ5JB

**Comment by Denis-Asipenko** [comment]
no permissions to read and write files.

**Comment by Denis-Asipenko** [comment]
@Miolin Please, add haptic feedback if the user scans or selects from the album QR-code does not contain our address

**Comment by Denis-Asipenko** [comment]
checked
