### ISSUE TITLE
Password request after send confirmation screen

### ISSUE THREAD

**Issue by alexandrashelenkova** [BeamMW/android-wallet#262]
Screens are here:
https://zpl.io/VQQKEyP
https://zpl.io/ag6PN5R
https://zpl.io/2EWPe3e
https://zpl.io/b6gjvWW

**Comment by Denis-Asipenko** [comment]
design:
https://app.zeplin.io/project/5ba9be48f029d520c456f395/screen/5d3826a9421705777855d9fb
![image](https://user-images.githubusercontent.com/45556620/63435385-7c559000-c42f-11e9-8cc0-90dea613e670.png)
actual:
![image](https://user-images.githubusercontent.com/45556620/63435433-8f686000-c42f-11e9-9a72-70544d13a5bd.png)

**Comment by Denis-Asipenko** [comment]
checked
