### ISSUE TITLE
Restore wallet

### ISSUE THREAD

**Issue by alexandrashelenkova** [BeamMW/android-wallet#264]
Restore wallet flow is here https://app.zeplin.io/project/5ba9be48f029d520c456f395/dashboard?seid=5d3836ce8c57df2dccaa97fe

**Comment by Denis-Asipenko** [comment]
![image](https://user-images.githubusercontent.com/45556620/63273908-86e51d80-c2a7-11e9-8b35-46d59349732a.png)

**Comment by Denis-Asipenko** [comment]
1. - make changes according to task https://github.com/BeamMW/android-wallet/issues/296
2. - replace the screen when downloading  recovery file on:

https://app.zeplin.io/project/5ba9be48f029d520c456f395/screen/5d383644f58f61632cda51ec
![image](https://user-images.githubusercontent.com/45556620/63415672-c24a2e00-c406-11e9-9264-088128f135c1.png)

3. - change  text on "Owner key" screen:

"**Paste this code in Beam Wallet on your desktop to proceed restore from the node. 
Once you'll paste the code, run your node on desktop and click next on mobile app.**"

![image](https://user-images.githubusercontent.com/45556620/63418644-1f94ae00-c40c-11e9-9b69-c880c79f1467.png)
and also need to raise buttons a bit higher.

4. - If try to connect to the wrong address(node that you cannot connect to) must add this screen:
https://app.zeplin.io/project/5ba9be48f029d520c456f395/screen/5d383641e7a5a52ebc4d1da0
![image](https://user-images.githubusercontent.com/45556620/63420039-93d05100-c40e-11e9-9ad0-e1607ebbe766.png)

**Comment by Denis-Asipenko** [comment]
- Submit for checking after implementation: 
https://github.com/BeamMW/android-wallet/issues/296
https://github.com/BeamMW/android-wallet/issues/309

**Comment by Denis-Asipenko** [comment]
- Design:

https://app.zeplin.io/project/5ba9be48f029d520c456f395/screen/5d5fdab06986389b1ea7bd4d
![image](https://user-images.githubusercontent.com/45556620/63755590-a55aa280-c8bf-11e9-919f-0dda5325f219.png)
https://app.zeplin.io/project/5ba9be48f029d520c456f395/screen/5d5fdab1e4adeb4ff21c9979
![image](https://user-images.githubusercontent.com/45556620/63755657-bc999000-c8bf-11e9-99c9-6d709b9038f8.png)
![image](https://user-images.githubusercontent.com/45556620/63756647-64638d80-c8c1-11e9-9058-07c75d925c49.png)



- Actual:
![image](https://user-images.githubusercontent.com/45556620/63755981-46495d80-c8c0-11e9-81f4-275569e6ddae.png)
![image](https://user-images.githubusercontent.com/45556620/63756254-b3f58980-c8c0-11e9-8108-c5580fd0c69c.png)
![image](https://user-images.githubusercontent.com/45556620/63756531-341bef00-c8c1-11e9-9b10-6dbaa8c6c790.png)

**Comment by Denis-Asipenko** [comment]
balance doesn't apdate
[video_2019-08-27_14-01-50.zip](https://github.com/BeamMW/android-wallet/files/3545760/video_2019-08-27_14-01-50.zip)

**Comment by Denis-Asipenko** [comment]
not fixed
https://github.com/BeamMW/android-wallet/issues/264#issuecomment-525207996

**Comment by Denis-Asipenko** [comment]
Crash app.
[video_2019-08-28_16-48-00.zip](https://github.com/BeamMW/android-wallet/files/3551217/video_2019-08-28_16-48-00.zip)

**Comment by Denis-Asipenko** [comment]
- Wallet crashes if during restore(connection local node) or creation wallet the application is minimized and then the system kills the process
[video_2019-08-30_16-51-32.zip](https://github.com/BeamMW/android-wallet/files/3560159/video_2019-08-30_16-51-32.zip)
   In addition, if you restore the wallet after such a failure by downloading the recovery file, node address that was specified when you tried to connect to the local node will be saved.

**Comment by Denis-Asipenko** [comment]
- **Restore with trusted node:**

1. Forbid invalid characters from being entered in the node address.
2. Forbid to enter multiple rows(a column).

![image](https://user-images.githubusercontent.com/45556620/64333074-7d192500-cfde-11e9-9663-0364a5c37e53.png)

**Comment by Denis-Asipenko** [comment]
When downloading a restore file, if you tap "cancel" at the end of the download, the download continues.
[20190905_131633.zip](https://github.com/BeamMW/android-wallet/files/3578797/20190905_131633.zip)

**Comment by Denis-Asipenko** [comment]
- It is forbidden to enter characters other than numbers after the colon in the port number. Allow input from 1 to 65535 .0 and everything greater than 65535 - make invalid.
![image](https://user-images.githubusercontent.com/45556620/64411801-b44b0d00-d096-11e9-8958-43f5da779ccd.png)

- After disabling network on the screen "Downloading  blockchain info" tap in the popup alert "try again" and after that, the text from the "Restore wallet " screen will be added.
[video_2019-09-06_11-22-10.zip](https://github.com/BeamMW/android-wallet/files/3582966/video_2019-09-06_11-22-10.zip)

**Comment by Denis-Asipenko** [comment]
checked
