### ISSUE TITLE
Review buttons positions on login/restore screens + small text fix

### ISSUE THREAD

**Issue by alexandrashelenkova** [BeamMW/android-wallet#265]

**Comment by alexandrashelenkova** [comment]
1. On seed phrase screen (during restore) move button lower, should be same as on other restore/login screens
<img width="555" alt="Screenshot 2019-08-15 at 10 15 38" src="https://user-images.githubusercontent.com/7249484/63068475-d04f0900-bf45-11e9-88a8-32eaeb16a8cd.png">
2. Remove sentence "Connect your device to power source to avoid restore stopping"
<img width="287" alt="Screenshot 2019-08-15 at 10 15 48" src="https://user-images.githubusercontent.com/7249484/63068487-dcd36180-bf45-11e9-9011-8d740de34258.png">

**Comment by Roberrtt** [comment]
Checked on App Version:3.2.09
