### ISSUE TITLE
Improve empty state when transaction history is empty

### ISSUE THREAD

**Issue by alexandrashelenkova** [BeamMW/android-wallet#268]
Empty state screen is here https://zpl.io/bz7lYK8

Texts for different tabs:
Text for **All, Sent, Received**  - "Your transactions list is empty".
Text for **In progress** - "You have no active transactions" if there is no transactions in progress but there are other transactions and "Your transactions list is empty" if there are no transactions at all.
Also if there are no transactions at all, let's not show tabs on top of the screen too.

**Comment by Roberrtt** [comment]
Checked on App Version:3.2.09
