### ISSUE TITLE
Improve empty state for UTXO and addresses/contacts screens

### ISSUE THREAD

**Issue by alexandrashelenkova** [BeamMW/android-wallet#269]
Screens
utxo https://zpl.io/aRGAnNr (please make empty state icon for privacy mode be on the same position https://zpl.io/VkpWM9q)
addresses https://zpl.io/aBWnQqq
contacts https://zpl.io/ag67xrR

If there's no addresses and contacts, please hide tabs on top of the screen if possible.

**Comment by alexandrashelenkova** [comment]
Please add small text fixes to empty screens.

Contacts/Addresses
Text for **My active** - "Your addresses list is empty" if there are no addresses at all, "You have no active addresses" if there are some expired addresses.
Text for **My expired** - "Your addresses list is empty" if there are no addresses at all, "You have no expired addresses" if there are some active addresses.
Text for **Contacts** - "Your contacts list is empty"

UTXO
Text for **All, Spent, Unavailable**  - "Your UTXO list is empty".
Text for **In progress** - "You have no active UTXO" if there is no UTXO in progress but there are other UTXOs and "Your UTXO list is empty" if there are no UTXO at all.
Also if there are no UTXO at all, let's not show tabs on top of the screen too.

**Comment by Denis-Asipenko** [comment]
checked
