### ISSUE TITLE
Redesign amount presentation of long numbers

### ISSUE THREAD

**Issue by vain-onnellinen** [BeamMW/android-wallet#27]
**Options that we discussed about:**
- Show groths instead of beams when amount is less than 10 000 groth
-  Separate groths 
-  Present Sending and receiving in different lines
- Take Maturing out to Available Balance section
- Rounding

**Comment by kaminskyelina** [comment]
![IMAGE 2019-04-01 18:49:57](https://user-images.githubusercontent.com/45590119/55341232-f308e580-54ae-11e9-81e1-570f7ecb5db3.jpg)

**Comment by alexandrashelenkova** [comment]
new design is here zpl.io/2vO09v7

**Comment by Denis-Asipenko** [comment]
Steps to behaviour reproduced:
1. Go to wallet.
2. Send or receive transaction on your wallet.
2. On the main screen collapse and expand "in progress" window.
![image](https://user-images.githubusercontent.com/45556620/58017172-2c9dba80-7b08-11e9-810d-2ec83f1a7564.png)

**Comment by Denis-Asipenko** [comment]
![image](https://user-images.githubusercontent.com/45556620/58024234-65df2600-7b1a-11e9-9779-866f5ce6285b.png)

**Comment by Denis-Asipenko** [comment]
checked
