### ISSUE TITLE
Settings screen redesign

### ISSUE THREAD

**Issue by alexandrashelenkova** [BeamMW/android-wallet#270]
Changes:
1. Add headers to sections, reorganise items in sections
2. Change toggles background
3. "Run random node" rename to "Connect to random node"
4. If "Run random node is off", ip:port shouldn't be editable and should be shown as a description of an item above
5. "Fingerprint", "Face Recognition" should be with capital first letters

Screens:
https://zpl.io/V4zGXJ0
https://zpl.io/VkeyPRq

**Comment by alexandrashelenkova** [comment]
<img width="370" alt="Screenshot 2019-08-15 at 11 08 15" src="https://user-images.githubusercontent.com/7249484/63070244-09d74280-bf4d-11e9-859d-5675b9044a0e.png">

**Comment by Denis-Asipenko** [comment]
@DenisDemyanko  Need to increase the area of tapping on "Connect to random node" and address when connecting to a specific node.
[20190823_104450.zip](https://github.com/BeamMW/android-wallet/files/3533353/20190823_104450.zip)

**Comment by Denis-Asipenko** [comment]
checked
