### ISSUE TITLE
Add actions to addresses on Address screen

### ISSUE THREAD

**Issue by alexandrashelenkova** [BeamMW/android-wallet#272]
Selection by long tap. If one address selected - actions: copy, edit, delete. https://zpl.io/bJWLBxK
If few addresses selected - action: delete. https://zpl.io/bekymjW

**Comment by Denis-Asipenko** [comment]
@DenisDemyanko Need to increase the address selection area on the entire line

**Comment by Denis-Asipenko** [comment]
checked
