### ISSUE TITLE
Contacts/addresses screen redesign

### ISSUE THREAD

**Issue by alexandrashelenkova** [BeamMW/android-wallet#273]
New addresses is here https://app.zeplin.io/project/5ba9be48f029d520c456f395/dashboard?seid=5c518b1f5420114200108193
Detail addresses/contacts view be added in separate task.

**Comment by Denis-Asipenko** [comment]
make changes according to comment https://github.com/BeamMW/android-wallet/issues/269#issuecomment-523917213

**Comment by Denis-Asipenko** [comment]
- Bug.

Steps reproduce to behavior:
1. Go to addresses screen.
2. Select an address and go to addresses details.
1. Select edit the address.
2. Select: expires "In 24 hours" on "Never".
3. Tap on the "Save" button.
Expected: expiration date change to never.
Actual: expiration date isn't changed.
[video_2019-08-23_15-02-09.zip](https://github.com/BeamMW/android-wallet/files/3534324/video_2019-08-23_15-02-09.zip)

- Design:
https://app.zeplin.io/project/5ba9be48f029d520c456f395/screen/5c7d24b8760bbd51f336edfd
![image](https://user-images.githubusercontent.com/45556620/63593159-0fbbcc00-c5bc-11e9-81b9-100a41195342.png)
Actual:
![image](https://user-images.githubusercontent.com/45556620/63593255-4e518680-c5bc-11e9-91dc-afbdf43d4476.png)

**Comment by Denis-Asipenko** [comment]
Edit address-address name is not saved when the first tag is created.
[video_2019-08-27_14-31-17.zip](https://github.com/BeamMW/android-wallet/files/3545853/video_2019-08-27_14-31-17.zip)

**Comment by Denis-Asipenko** [comment]
Edit address - if you set  "never"  in  "Expires"  and tap save and then return to that screen again, the "Expires" will be set to "24 hours"
[video_2019-08-28_11-11-29.zip](https://github.com/BeamMW/android-wallet/files/3549836/video_2019-08-28_11-11-29.zip)

**Comment by Denis-Asipenko** [comment]
Address book - in contacts\addresses missing transactions list.
![image](https://user-images.githubusercontent.com/45556620/64109642-b6f0ee00-cd88-11e9-8415-5549348bd0f4.png)
![image](https://user-images.githubusercontent.com/45556620/64109624-a5a7e180-cd88-11e9-9885-d74ee00b061e.png)

**Comment by Denis-Asipenko** [comment]
@Miolin 
Need to change text when deleting multiple addresses
> **Delete addresses**
> Delete all transactions related to this addresses

![image](https://user-images.githubusercontent.com/45556620/64170040-c3904780-ce57-11e9-89a9-b2dfafeba7d4.png)

> **Addresses deleted**

![image](https://user-images.githubusercontent.com/45556620/64170216-3dc0cc00-ce58-11e9-959f-1418fa341035.png)

**Comment by Denis-Asipenko** [comment]
checked
