### ISSUE TITLE
UTXO screen redesign

### ISSUE THREAD

**Issue by alexandrashelenkova** [BeamMW/android-wallet#274]
Changes:
- update vidget view (height and hash)
- remove "All" tab
- new tabs: Available, In progress, Spent, Unavailable
- add transaction's comment and date
- update row's view for new design

Screens:
https://zpl.io/VOArlWP
https://zpl.io/anLXjKQ
https://zpl.io/bekmlYm
https://zpl.io/2jYOAwp

**Comment by alexandrashelenkova** [comment]
<img width="590" alt="Screenshot 2019-08-19 at 17 13 13" src="https://user-images.githubusercontent.com/7249484/63253567-aaf32f80-c2a4-11e9-9cc8-69b5c1f61409.png">

**Comment by Denis-Asipenko** [comment]
@DenisDemyanko  make changes according to comment https://github.com/BeamMW/android-wallet/issues/269#issuecomment-523917213

**Comment by Denis-Asipenko** [comment]
The available tab does not display the date.
Example:
![image](https://user-images.githubusercontent.com/45556620/63932776-86474680-ca60-11e9-97f0-2e61cab5454c.png)
![image](https://user-images.githubusercontent.com/45556620/63932800-952df900-ca60-11e9-84da-dc1f4498987a.png)
[video_2019-08-29_13-26-29.zip](https://github.com/BeamMW/android-wallet/files/3555081/video_2019-08-29_13-26-29.zip)

**Comment by Denis-Asipenko** [comment]
checked
