### ISSUE TITLE
Send/receive screen small improvements

### ISSUE THREAD

**Issue by alexandrashelenkova** [BeamMW/android-wallet#276]
- "send all" rename to "add all", make less attention to the button?
- “paste address or find contact” rename to "send to"
- "annotation" rename to "comment", "won't be shared" moved to hint instead of field header
- "category" rename to "tag"
- "existing addresses", "addresses" rename to "my active addresses"
- addresses/contacts view updated to addresses/contacts screens (multi-categories, expiration date, etc)
- update annotation on receive screen ("Send this address over...")
- change wallet background colour (applies to whole app, mainnet only).

Updated screens are here:
send https://app.zeplin.io/project/5ba9be48f029d520c456f395/dashboard?seid=5cee6dd12f02be1d5003768c
receive https://app.zeplin.io/project/5ba9be48f029d520c456f395/dashboard?seid=5cee7c2d4c7fea1d62dc3144

**Comment by Denis-Asipenko** [comment]
- Forbid invalid characters from being entered in the contact's address
- To forbid to enter multiple rows(a column)

![image](https://user-images.githubusercontent.com/45556620/63937256-a4b23f80-ca6a-11e9-857a-6dfa0f48dd74.png)

**Comment by Denis-Asipenko** [comment]
not error message:"Incorrect address"
![image](https://user-images.githubusercontent.com/45556620/64118907-4c987780-cda1-11e9-9b11-13d1effd38c1.png)

**Comment by Denis-Asipenko** [comment]
Design:
https://app.zeplin.io/project/5ba9be48f029d520c456f395/screen/5cf7271a6af3e11bb49cb6c1
![image](https://user-images.githubusercontent.com/45556620/64174552-32729e00-ce62-11e9-9d13-42961b2f19de.png)
https://app.zeplin.io/project/5ba9be48f029d520c456f395/screen/5cf7271aa03dad1de7679bd5
![image](https://user-images.githubusercontent.com/45556620/64174700-7bc2ed80-ce62-11e9-87da-a9cb49882296.png)
https://app.zeplin.io/project/5ba9be48f029d520c456f395/screen/5be5b6fe5087e47ea746a39d
![image](https://user-images.githubusercontent.com/45556620/64175076-3ce16780-ce63-11e9-8db7-1fc87c2d5a86.png)
https://app.zeplin.io/project/5ba9be48f029d520c456f395/screen/5d36f5f2a2e9ba2f7bf40e64
![image](https://user-images.githubusercontent.com/45556620/64175136-5e425380-ce63-11e9-9374-196fb28347b0.png)
https://app.zeplin.io/project/5ba9be48f029d520c456f395/screen/5cf724665b623413417cd980
![image](https://user-images.githubusercontent.com/45556620/64175215-8762e400-ce63-11e9-8b44-d237c0b67c7c.png)
Actual:
![image](https://user-images.githubusercontent.com/45556620/64174590-44ecd780-ce62-11e9-94a5-1b56194cd4a3.png)
![image](https://user-images.githubusercontent.com/45556620/64174668-6d74d180-ce62-11e9-9749-fc76eee47c2c.png)
![image](https://user-images.githubusercontent.com/45556620/64174777-a57c1480-ce62-11e9-8a22-37ae9e64400a.png)
![image](https://user-images.githubusercontent.com/45556620/64175432-f0e2f280-ce63-11e9-8530-8730b4d5459e.png)

**Comment by Denis-Asipenko** [comment]
checked
