### ISSUE TITLE
When showing owner key the explanation should be given on what it is good for

### ISSUE THREAD

**Issue by alexandrashelenkova** [BeamMW/android-wallet#279]
Add alert which should be displayed after user chooses Show owner key in Settings. https://zpl.io/2pkgQeE (just with password)
https://zpl.io/2pkgQEo (with Face Recognition)
https://zpl.io/2yWoxno (with Face Fingerprint)

After alert comes face recognition (https;//zpl.io/awOd9N1) / fingerprint (https://zpl.io/V0LnXBw) screen comes first, then password screen (https://zpl.io/2j5oElQ).

Update text on owner key screen https://zpl.io/beAr63p

**Comment by DenisDemyanko** [comment]
@alexandrashelenkova 

screen order remains as in ios:
1. Password
2. Fingerprint

**Comment by Denis-Asipenko** [comment]
Distance from 
- label
- field
- button

Make two times lower.
![image](https://user-images.githubusercontent.com/45556620/63426854-7efaba00-c41c-11e9-92ce-ba8ec65c313f.png)
![image](https://user-images.githubusercontent.com/45556620/63426862-828e4100-c41c-11e9-938b-4c85695b0bad.png)

**Comment by alexandrashelenkova** [comment]
1. If Fingerprint is disable, this dialog should appear https://zpl.io/2pkgQeE (request only password). We can't request Fingerprint if it's disable in the app.
2. Please fix mistake in alerts 
<img width="417" alt="Screenshot at Aug 21 22-37-03" src="https://user-images.githubusercontent.com/7249484/63441589-41218400-c464-11e9-978f-9950125d3576.png">

**Comment by Denis-Asipenko** [comment]
checked
