### ISSUE TITLE
Align send screen UX with the spec

### ISSUE THREAD

**Issue by vain-onnellinen** [BeamMW/android-wallet#28]
https://app.zeplin.io/project/5ba9be48f029d520c456f395/screen/5be5b6ff0a39623f93bd22a0
https://app.zeplin.io/project/5ba9be48f029d520c456f395/screen/5be5b6fccdb5d33fb0605ccb
https://app.zeplin.io/project/5ba9be48f029d520c456f395/screen/5be5b6faa6ae643eda99f4b7
https://app.zeplin.io/project/5ba9be48f029d520c456f395/screen/5bbb21e3796c0d0aecf20ea4
https://app.zeplin.io/project/5ba9be48f029d520c456f395/screen/5c0fb6cc81415cb0062aaf8a
https://app.zeplin.io/project/5ba9be48f029d520c456f395/screen/5c0fb8867eda90245b22c997

**Comment by Denis-Asipenko** [comment]
invalid
