### ISSUE TITLE
when accepting password the keyboard should pop out automatically (examples: password settings screen when running the app; entering the password to unblock "enter the password to approve every send", "change wallet password" etc)

### ISSUE THREAD

**Issue by alexandrashelenkova** [BeamMW/android-wallet#282]

**Comment by Denis-Asipenko** [comment]
on this screen, too, you need to add automatic focus and display the keyboard
![image](https://user-images.githubusercontent.com/45556620/63341609-48586d00-c352-11e9-902e-8e6ccd91696a.png)

**Comment by Denis-Asipenko** [comment]
checked

**Comment by sasha-abramovich** [comment]
@alexandrashelenkova in the future @gingervik kindly asked to write long cases in the task description.
