### ISSUE TITLE
Align receive screen UX with the spec

### ISSUE THREAD

**Issue by vain-onnellinen** [BeamMW/android-wallet#29]
https://app.zeplin.io/project/5ba9be48f029d520c456f395/screen/5bd4de3aa5db70097c6df21c
https://app.zeplin.io/project/5ba9be48f029d520c456f395/screen/5bd4de38cac1e00a202579c0
https://app.zeplin.io/project/5ba9be48f029d520c456f395/screen/5bbb21e4a55ed15fd398a478
https://app.zeplin.io/project/5ba9be48f029d520c456f395/screen/5be5b6fe5087e47ea746a39d

**Comment by Denis-Asipenko** [comment]
invalid
