### ISSUE TITLE
"Creating wallet" header is missing

### ISSUE THREAD

**Issue by alexandrashelenkova** [BeamMW/android-wallet#293]

**Comment by alexandrashelenkova** [comment]
There is no header and "Cancel" button on the screen during wallet creation (masternet).
<img width="721" alt="Screenshot at Aug 15 10-21-58" src="https://user-images.githubusercontent.com/7249484/63068659-90d4ec80-bf46-11e9-9a8a-5895e9e9439f.png">

**Comment by Denis-Asipenko** [comment]
checked
