### ISSUE TITLE
When focus goes to the next field (input seed phrase flow), input filed isn't visible

### ISSUE THREAD

**Issue by alexandrashelenkova** [BeamMW/android-wallet#294]
When user taps on "Puppy" hint on the keyboard, focus goes to the next input field (9), but it's hidden behind keyboard. Screen should scroll up so focused field would be visible.

**Comment by alexandrashelenkova** [comment]
![IMG_0830](https://user-images.githubusercontent.com/7249484/63072098-95080680-bf54-11e9-9f0d-efc9fd473471.png)

**Comment by Denis-Asipenko** [comment]
checked
