### ISSUE TITLE
Remove "+" icon on addresses tabs

### ISSUE THREAD

**Issue by alexandrashelenkova** [BeamMW/android-wallet#295]
"+" icon should be only on "Contacts" tab. Please make it appear and dissapear smooth, so it won't "Blink" during changing tabs

**Comment by alexandrashelenkova** [comment]
<img width="367" alt="Screenshot at Aug 15 15-57-27" src="https://user-images.githubusercontent.com/7249484/63081121-66e6ee80-bf75-11e9-9f47-9340a165fa8b.png">

**Comment by Denis-Asipenko** [comment]
checked
