### ISSUE TITLE
Add alert after submitting seed phrase (restore flow)

### ISSUE THREAD

**Issue by alexandrashelenkova** [BeamMW/android-wallet#296]
https://zpl.io/adNnPjR

Do not show this alert when opening restore from starting screen https://zpl.io/adNeLJp

**Comment by Denis-Asipenko** [comment]
Please make according to the design
- Design:

https://app.zeplin.io/project/5ba9be48f029d520c456f395/screen/5d5a2559b1beb630a2b817e5
![image](https://user-images.githubusercontent.com/45556620/63753820-7f7fce80-c8bc-11e9-8833-0d6cc6d71042.png)
- Actual:

![image](https://user-images.githubusercontent.com/45556620/63754022-d4234980-c8bc-11e9-930f-69db7cee3f8f.png)

**Comment by Denis-Asipenko** [comment]
![image](https://user-images.githubusercontent.com/45556620/63842669-bbcf2f80-c98d-11e9-93b8-67757bacdd2b.png)

**Comment by Denis-Asipenko** [comment]
chacked
