### ISSUE TITLE
Main screen redesign

### ISSUE THREAD

**Issue by alexandrashelenkova** [BeamMW/android-wallet#297]
Screens https://zpl.io/V1lmB4X
https://zpl.io/V19Yy8m

On main screen show only 5 latests transactions (only type of transactions, status and amount). 
Maturing move to Available card (would be opened by tap on Maturing header)

**Comment by Denis-Asipenko** [comment]
@Miolin  

- Make changes according to task https://github.com/BeamMW/android-wallet/issues/268
Design:
https://app.zeplin.io/project/5ba9be48f029d520c456f395/screen/5bbb21de326ac118dbb26ff7
![image](https://user-images.githubusercontent.com/45556620/63573995-6f4fb280-c58f-11e9-9e6d-2a0a69b59258.png)
Actual:
![image](https://user-images.githubusercontent.com/45556620/63574062-93ab8f00-c58f-11e9-94fc-c7fd31d96231.png)
![image](https://user-images.githubusercontent.com/45556620/63574091-a920b900-c58f-11e9-8117-7fd6ade33e00.png)

**Comment by Denis-Asipenko** [comment]
When you activate the secret mode, some screens do not hide the amount.
[video_2019-08-29_11-25-14.zip](https://github.com/BeamMW/android-wallet/files/3554575/video_2019-08-29_11-25-14.zip)

**Comment by Denis-Asipenko** [comment]
checked
