### ISSUE TITLE
UTXO detail screen redesign

### ISSUE THREAD

**Issue by alexandrashelenkova** [BeamMW/android-wallet#298]
New screen is here: https://zpl.io/2pkmZAy

**Comment by Denis-Asipenko** [comment]
design:
https://app.zeplin.io/project/5ba9be48f029d520c456f395/screen/5d5d39e52dba3f9bc1f20323
![image](https://user-images.githubusercontent.com/45556620/63936860-a4fe0b00-ca69-11e9-8017-39ba6fa1b65d.png)
actual:
![image](https://user-images.githubusercontent.com/45556620/63936869-acbdaf80-ca69-11e9-95e4-7e1664a78690.png)

**Comment by Denis-Asipenko** [comment]
Details: icon (triangle) wrong position when you open the UTXO details screen
[video_2019-08-30_11-52-32.zip](https://github.com/BeamMW/android-wallet/files/3559108/video_2019-08-30_11-52-32.zip)

**Comment by Denis-Asipenko** [comment]
checked
