### ISSUE TITLE
Address/contact detail screen redesign

### ISSUE THREAD

**Issue by alexandrashelenkova** [BeamMW/android-wallet#299]
New screens:
https://zpl.io/aRGBAge
https://zpl.io/adNDnmn
https://zpl.io/bPgORAl
https://zpl.io/aNzqWq9

**Comment by Denis-Asipenko** [comment]
Address details screen:
When editing the expiration date is not updated after the change from "24 hours" to "Never" and vice versa.

**Comment by Denis-Asipenko** [comment]
![image](https://user-images.githubusercontent.com/45556620/66028948-deadb000-e506-11e9-990b-a50b6c41036e.png)
Do not display tooltips on this screen.
![image](https://user-images.githubusercontent.com/45556620/66028120-17e52080-e505-11e9-9dcc-63842cc9cf61.png)

**Comment by Denis-Asipenko** [comment]
checked
