### ISSUE TITLE
Transaction detail redesign

### ISSUE THREAD

**Issue by alexandrashelenkova** [BeamMW/android-wallet#300]
Screens are here:
https://zpl.io/a89Rn5g
https://zpl.io/bJWnNGE

**Comment by Denis-Asipenko** [comment]
Payment proof is not copied by long tap.

**Comment by Denis-Asipenko** [comment]
Add the ability to copy fields: 

- Kernel ID. 
- Contact.
- My address. 
- Transaction ID.

**Comment by Denis-Asipenko** [comment]
![image](https://user-images.githubusercontent.com/45556620/65866019-cf026000-e37c-11e9-9ec4-37b6fffe2341.png)

**Comment by Denis-Asipenko** [comment]
Design:
https://app.zeplin.io/project/5ba9be48f029d520c456f395/screen/5d5c10ee03703951ee6e6f25
![image](https://user-images.githubusercontent.com/45556620/65948396-d55b0f80-e442-11e9-9600-8241b7395b86.png)
Actual:
![image](https://user-images.githubusercontent.com/45556620/65948411-e3109500-e442-11e9-9bd2-366d7d81cf71.png)
![image](https://user-images.githubusercontent.com/45556620/65948418-e73cb280-e442-11e9-9653-5335f62c1f39.png)

**Comment by Denis-Asipenko** [comment]
The contact should be displayed first.
![image](https://user-images.githubusercontent.com/45556620/65969708-ecfbbd80-e46d-11e9-8030-9d253c722a63.png)
actual:
![image](https://user-images.githubusercontent.com/45556620/65969764-0270e780-e46e-11e9-88b5-7e390c30ba7c.png)

**Comment by Denis-Asipenko** [comment]
![image](https://user-images.githubusercontent.com/45556620/66027160-000c9d00-e503-11e9-94fa-a21b9bdc8d27.png)

**Comment by Denis-Asipenko** [comment]
checked
