### ISSUE TITLE
Remove confirmation alert after changing language

### ISSUE THREAD

**Issue by alexandrashelenkova** [BeamMW/android-wallet#301]
Language should change without confirmation dialog (cause this dialog has language that user probably doesn't understand). Let's remove it. Apply language and bring to the previous screen just by tapping on language's line

**Comment by alexandrashelenkova** [comment]
![2019-08-20 13 14 46](https://user-images.githubusercontent.com/7249484/63319389-805cb180-c34c-11e9-90f6-214b8fcbc066.jpg)

**Comment by alexandrashelenkova** [comment]
Also, is it possible to not restart app every time when we change language?

**Comment by Denis-Asipenko** [comment]
checked
