### ISSUE TITLE
Header should be in caps in all translations

### ISSUE THREAD

**Issue by alexandrashelenkova** [BeamMW/android-wallet#304]
Header should be in caps no matter how it is written in translations file. Only "АВТОМАТИЧЕСКОЕ ВОССТАНОВЛЕНИЕ", not the part in breaks.

**Comment by alexandrashelenkova** [comment]
![2019-08-21 22 10 27](https://user-images.githubusercontent.com/7249484/63439390-80e66c80-c460-11e9-810b-1ce019e785eb.jpg)

**Comment by sasha-abramovich** [comment]
Maybe just Russian, Finnish and German shouldn't be capitalized? @alexandrashelenkova thoughts please?

**Comment by alexandrashelenkova** [comment]
@sasha-abramovich why these languages?) And we have other header in caps too, so it should be consistent everywhere.

**Comment by sasha-abramovich** [comment]
@alexandrashelenkova just because their words are very long? remember what the Finnish translator suggested? that was the trigger for my rationale

**Comment by alexandrashelenkova** [comment]
Let's keep it all caps please.

**Comment by Denis-Asipenko** [comment]
checked
