### ISSUE TITLE
Remove frame around selected item

### ISSUE THREAD

**Issue by alexandrashelenkova** [BeamMW/android-wallet#305]
There's small frame around selected item in a drop down list (the last item on screenshot). Is it possible to remove it?

**Comment by alexandrashelenkova** [comment]
![2019-08-21 22 12 29](https://user-images.githubusercontent.com/7249484/63439584-eaff1180-c460-11e9-9f81-c0dfa4b39c35.jpg)

**Comment by Denis-Asipenko** [comment]
checked
