### ISSUE TITLE
Time format in transaction details should be same as is on user's device

### ISSUE THREAD

**Issue by alexandrashelenkova** [BeamMW/android-wallet#306]

**Comment by alexandrashelenkova** [comment]
<img width="420" alt="Screenshot at Aug 21 22-18-21" src="https://user-images.githubusercontent.com/7249484/63439973-9dcf6f80-c461-11e9-915b-a958f5719f74.png">

**Comment by Denis-Asipenko** [comment]
Steps to reproduce behavior: 
1. Go to wallet.
2. Check time format in transaction details( time format  24 hours).
3. Go to settings on the device and change time format for 12 hours.
4. Return to wallet and check time format in transaction details.
Expected: time format change.
Actual: time format doesn't change.
Note: To change the time format in the wallet, you need to restart the app.

**Comment by Denis-Asipenko** [comment]
checked
