### ISSUE TITLE
Add dialog about Fabric access

### ISSUE THREAD

**Issue by alexandrashelenkova** [BeamMW/android-wallet#307]
Dialog is here https://zpl.io/aMRDBvK

**Comment by Denis-Asipenko** [comment]
Actual:
![image](https://user-images.githubusercontent.com/45556620/65690883-9448b100-e078-11e9-9736-f8b2411cb5bb.png)
Design:
https://app.zeplin.io/project/5ba9be48f029d520c456f395/screen/5d5f874eff86179b0c00db59
![image](https://user-images.githubusercontent.com/45556620/65690906-9e6aaf80-e078-11e9-990a-f18463f547b4.png)

**Comment by Denis-Asipenko** [comment]
checked
