### ISSUE TITLE
Snack bar under buttons

### ISSUE THREAD

**Issue by alexandrashelenkova** [BeamMW/android-wallet#310]

**Comment by alexandrashelenkova** [comment]
![2019-08-26 09 45 25](https://user-images.githubusercontent.com/7249484/63659861-5856cd80-c7e6-11e9-8244-c6a44f50e4c0.jpg)

**Comment by Denis-Asipenko** [comment]
![image](https://user-images.githubusercontent.com/45556620/63686185-ea240200-c809-11e9-84d4-4166c56e713c.png)

**Comment by Denis-Asipenko** [comment]
checked on version 3.0.15
