### ISSUE TITLE
Fingerprint background should be red (while error)

### ISSUE THREAD

**Issue by alexandrashelenkova** [BeamMW/android-wallet#311]
Fingerprint background should be red, also alert message is missing.
https://zpl.io/boZK6Zg

**Comment by alexandrashelenkova** [comment]
![2019-08-26 09 51 30](https://user-images.githubusercontent.com/7249484/63660031-390c7000-c7e7-11e9-8728-1c19ec813f29.jpg)

**Comment by Denis-Asipenko** [comment]
- We should fasten a warning that the fingerprint is not recognized after 5 attempts.

![image](https://user-images.githubusercontent.com/45556620/65506051-5e1dfc80-ded3-11e9-8784-136751b7c3c3.png)

- Also, the fingerprint icon should be omitted below, and the text "Restore wallet or create new one" should be raised above,as in this screenshot.
![image](https://user-images.githubusercontent.com/45556620/65506580-8e19cf80-ded4-11e9-8ed2-8187f26f2688.png)

**Comment by Denis-Asipenko** [comment]
Language of the wallet-English.
Local-Russian.
![image](https://user-images.githubusercontent.com/45556620/65516176-346fd000-dee9-11e9-9ac3-1b556d611449.png)

**Comment by Denis-Asipenko** [comment]
checked
