### ISSUE TITLE
Screen small fixes

### ISSUE THREAD

**Issue by alexandrashelenkova** [BeamMW/android-wallet#312]

**Comment by alexandrashelenkova** [comment]
1. "UNDO" in snack bar should be in caps letters
App
<img width="416" alt="Screenshot 2019-08-26 at 09 58 19" src="https://user-images.githubusercontent.com/7249484/63660231-0e6ee700-c7e8-11e9-8fad-a711937ecd0a.png">
Design 
<img width="363" alt="Screenshot 2019-08-26 at 09 58 51" src="https://user-images.githubusercontent.com/7249484/63660242-1fb7f380-c7e8-11e9-931a-6677eaa97dbf.png">
https://zpl.io/2vO5EEY

2. After turn off Privacy Mode, Available and In progress card should have same conditions as it was before turning on Privacy Mode - if were open, should be open; if were closed, should be closed. At the moment cards are always closed after turning off Privacy Mode.

**Comment by Roberrtt** [comment]
3. Show all (transactions) should have normal letter spacing
4. Space between In progress card and Transactions header should be 30 dp

**Comment by Roberrtt** [comment]
Checked
