### ISSUE TITLE
Tag screen redesign

### ISSUE THREAD

**Issue by alexandrashelenkova** [BeamMW/android-wallet#316]
New design is here: https://zpl.io/aX9oXr8

Also if there are no addresses connected to tag, let's not show "addresses/contacts" tab at all.

**Comment by Denis-Asipenko** [comment]
Design:
https://app.zeplin.io/project/5ba9be48f029d520c456f395/screen/5d5fd8348847a29b549c18a8
![image](https://user-images.githubusercontent.com/45556620/65967033-98eeda00-e469-11e9-9b5a-388e4c0310f3.png)
Actual:
![image](https://user-images.githubusercontent.com/45556620/65967080-b15ef480-e469-11e9-85e8-9e0f85a58b56.png)

**Comment by Roberrtt** [comment]
Checked on App Version:3.2.09
