### ISSUE TITLE
Payment proof screen redesign

### ISSUE THREAD

**Issue by alexandrashelenkova** [BeamMW/android-wallet#318]
New screens are here 
https://app.zeplin.io/project/5ba9be48f029d520c456f395/dashboard?seid=5c9cdeb9eb413e0ab96f31c2

**Comment by Denis-Asipenko** [comment]
Design:
![image](https://user-images.githubusercontent.com/45556620/65516246-523d3500-dee9-11e9-8a9f-a21bd5a7829e.png)
Actual:
![image](https://user-images.githubusercontent.com/45556620/65516261-59644300-dee9-11e9-8c27-6a1266399d22.png)

**Comment by Denis-Asipenko** [comment]
checked
