### ISSUE TITLE
Implement transaction statuses & icons

### ISSUE THREAD

**Issue by alexandrashelenkova** [BeamMW/android-wallet#320]
Transaction statuses are here http://zpl.io/aX9oemX
These statuses should be used everywhere where user can see transactions in the app

**Comment by alexandrashelenkova** [comment]
@DenisDemyanko please rename "Sending" and "Receiving" statuses in to "In progress", cause it's more correct term for such statuses as "waiting", "confirming".

**Comment by Roberrtt** [comment]
Checked on App Version:3.2.09
