### ISSUE TITLE
Sidemenu - the status bar is fully colored.

### ISSUE THREAD

**Issue by Denis-Asipenko** [BeamMW/android-wallet#322]
- Design:

https://app.zeplin.io/project/5ba9be48f029d520c456f395/screen/5bbb21eb252aba5fcdfaed6d
![image](https://user-images.githubusercontent.com/45556620/63694753-d1264b80-c81f-11e9-940e-633ba73d2535.png)

- Actual:

![image](https://user-images.githubusercontent.com/45556620/63694788-e1d6c180-c81f-11e9-8d6d-bba9e33d856f.png)

**Comment by alexandrashelenkova** [comment]
Let's fix that in the next release, to not delay this one.

**Comment by DenisDemyanko** [comment]
Can't fixes.
Menu should not overlap status bar

**Comment by alexandrashelenkova** [comment]
Okay, let's leave as it is now. Thank you
