### ISSUE TITLE
Transaction search results

### ISSUE THREAD

**Issue by alexandrashelenkova** [BeamMW/android-wallet#323]
Updated design https://zpl.io/bJGNzO3
Transaction type, status, comment (with icon), date, amount should be shown always in transactions lists. Additional show field which contains searched info (transaction or kernel id, addresses or contact, contacts name (with icon). Searched words should be highlighted (#00F6D2).

**Comment by alexandrashelenkova** [comment]
Let's do only second part in this sprint, implementing search by kernel ID can wait for CC 3.2.

**Comment by Denis-Asipenko** [comment]
checked
