### ISSUE TITLE
Implement search by Kernel ID

### ISSUE THREAD

**Issue by alexandrashelenkova** [BeamMW/android-wallet#324]
Transaction search should be by kernel id too (not only transactions id), fix empty screen state wording https://zpl.io/boMkRYv

**Comment by Denis-Asipenko** [comment]
Design:
![image](https://user-images.githubusercontent.com/45556620/65495711-e0042a80-debf-11e9-8496-2a80d4d724b9.png)
Actual:
![image](https://user-images.githubusercontent.com/45556620/65496088-851f0300-dec0-11e9-8df1-3a22a56d1fab.png)

**Comment by Denis-Asipenko** [comment]
checked
