### ISSUE TITLE
Update Share transaction details screen

### ISSUE THREAD

**Issue by alexandrashelenkova** [BeamMW/android-wallet#337]
New versions are here 
mainnet https://zpl.io/2jMwm36
testnet https://zpl.io/29ne5RY
masternet https://zpl.io/V0p1Z1m

**Comment by Denis-Asipenko** [comment]
![image](https://user-images.githubusercontent.com/45556620/66214669-d56d4080-e6ca-11e9-90d7-9ed928b1f2cb.png)

**Comment by Denis-Asipenko** [comment]
design:
![image](https://user-images.githubusercontent.com/45556620/66298766-ed2b0b80-e8fa-11e9-9679-7baab87efe21.png 
actual:
![image](https://user-images.githubusercontent.com/45556620/66298835-0cc23400-e8fb-11e9-9509-d8ba7ba9786f.png)

**Comment by Denis-Asipenko** [comment]
checked
