### ISSUE TITLE
Make the "Show all" button more visible.

### ISSUE THREAD

**Issue by Denis-Asipenko** [BeamMW/android-wallet#342]
We need to make the "Show all" button more visible to the user and to navigate through the wallet was more intuitive.
![image](https://user-images.githubusercontent.com/45556620/65230452-8cb46580-dad6-11e9-8367-1003a29af0a2.png)

**Comment by dariatarakanova** [comment]
Please make margin between TRANSACTIONS and AVAILABLE block the same as on design https://zpl.io/V1lmB4X

So it help to make button "show more" more visible. 
It can be clearly seen here:
![image](https://user-images.githubusercontent.com/47353570/67273424-10db7d80-f4c7-11e9-8006-d929a8606f18.png)

**Comment by Denis-Asipenko** [comment]
checked
