### ISSUE TITLE
In the alert, when you delete a contact, change "address" to "contact".

### ISSUE THREAD

**Issue by Denis-Asipenko** [BeamMW/android-wallet#345]
This Alert displayed if the user wants to delete the contact from whom the transactions were received or sent.
![image](https://user-images.githubusercontent.com/45556620/65239073-d1e09380-dae6-11e9-9ffd-2fd94504a349.png)

**Comment by alexandrashelenkova** [comment]
Added comments about wording on this screen in zeplin, I guess we don't need separate screen for that?

**Comment by Denis-Asipenko** [comment]
checked
