### ISSUE TITLE
On "Seed phrase" screen a possible to make a screenshot.

### ISSUE THREAD

**Issue by Denis-Asipenko** [BeamMW/android-wallet#348]
Steps to reproduce  behavior:
1. Go to wallet.
2. Start create new wallet.
3. On "Create new password" screen, return to the previous screen.
4. A warning message appears that the seed phrases will be re-generated. Tap "GENERATE".
5. Try taking a screenshot on "Seed phrase" screen.
Expected: Screenshot cannot be taken.
Actual: Screenshot was taken.

**Comment by sasha-abramovich** [comment]
if it takes too long to fix - please skip, we'll change this functionality anyways

**Comment by sasha-abramovich** [comment]
actually, taking my words back - let's not allow taking the screenshot as expected. in the new onboarding, we'll present the seed phrase and we'll write that until some balance this phrase will be always accessible from settings. users still shouldn't take screenshots. as there is a risk that if someone takes a screenshot during onboarding and the screenshot will be kept on his cloud (prone to hacking) and one day same guy will receive 1000000BEAM to his wallet and if his wallet is monitored a hacker will know it. so, better still not to allow taking screenshots.

**Comment by Roberrtt** [comment]
Checked on App Version:3.2.09
