### ISSUE TITLE
Cannot open Advanced Tab after pasted address (Send screen)

### ISSUE THREAD

**Issue by alexandrashelenkova** [BeamMW/android-wallet#350]
![2019-09-28 17 21 36](https://user-images.githubusercontent.com/7249484/65814461-947db380-e214-11e9-86e0-ed188a59d029.jpg)

**Comment by Denis-Asipenko** [comment]
Bug not fixed
[video_2019-09-30_17-59-16.zip](https://github.com/BeamMW/android-wallet/files/3671846/video_2019-09-30_17-59-16.zip)

**Comment by Denis-Asipenko** [comment]
checked
