### ISSUE TITLE
Hide tabs on addresses screen when address is selected

### ISSUE THREAD

**Issue by alexandrashelenkova** [BeamMW/android-wallet#352]
When one or more addresses/contacts are selected, tabs should be hidden, so user won't try to tap it. Please make tabs disagreeing softly.

**Comment by Denis-Asipenko** [comment]
Crash wallet.
Note: There are several active addresses and contacts in the address book.
Steps to reproduce behavior:
1. Go to the wallet.
2. Go to "Address book"
3. Select all addresses in the tab "MY ACTIVE".
4. Remove the labels of the selected addresses one by one.
5. Go to the "CONTACTS" tab.
6. Select all contacts.
7. Remove the labels of the selected contacts one by one.
Expected: labels are removed and the wallet works.
Actual: Crash wallet.
Version: 3.2.06
[video_2019-10-01_11-37-40.zip](https://github.com/BeamMW/android-wallet/files/3675216/video_2019-10-01_11-37-40.zip)

- I also think that it is necessary to speed up the shift of addresses to the place of tabs.

- When removing selection labels from addresses and shift addresses in the opposite direction, it appears that addresses are shuffled.
[video_2019-10-01_11-40-25.zip](https://github.com/BeamMW/android-wallet/files/3675240/video_2019-10-01_11-40-25.zip)

**Comment by Denis-Asipenko** [comment]
checked
