### ISSUE TITLE
Send screen-the "Edit address" \ "Advanced" tab isn't smoothly hidden.

### ISSUE THREAD

**Issue by Denis-Asipenko** [BeamMW/android-wallet#354]
Steps to reproduce behavior:
1. Go to Send screen.
2. Tap the "ADVANCED" tab.
3. In "ADVANCED" tab tap "EDIT ADDRESS" tab.
4. Go down to the bottom of the screen.
5. Tap the "EDIT ADDRESS" tab to hide it.
6. Tap the "ADVANCED" tab to hide it.
Expected: Tabs hide smoothly.
Actual: Tabs are hidden not smoothly, but with jumps to the top of the screen.
[20191001_134800.zip](https://github.com/BeamMW/android-wallet/files/3676383/20191001_134800.zip)

**Comment by DenisDemyanko** [comment]
Can't fixed right now

**Comment by Denis-Asipenko** [comment]
checked
