### ISSUE TITLE
Add alert when delete transaction.

### ISSUE THREAD

**Issue by Denis-Asipenko** [BeamMW/android-wallet#358]
Please pay attention to the case when several transactions will be deleted. In this case, you must specify **TRANSACTIONS** in the text.
https://app.zeplin.io/project/5ba9be48f029d520c456f395/screen/5cebaee2bff8802fafa3fb01
![image](https://user-images.githubusercontent.com/45556620/66040146-67d0e100-e51f-11e9-8bbd-06253aa72e7a.png)

**Comment by Roberrtt** [comment]
Checked

**Comment by Denis-Asipenko** [comment]
Also, need to add this alert when the user selects "Delete" transaction on the "Transaction details" screen.

**Comment by Roberrtt** [comment]
Checked
