### ISSUE TITLE
Implement restore wallet

### ISSUE THREAD

**Issue by vain-onnellinen** [BeamMW/android-wallet#36]

**Comment by vain-onnellinen** [comment]
@Miolin after suggestions will be included we need to make color handling for seed phrases by analogy with create wallet flow

**Comment by sasha-abramovich** [comment]
@alexandrashelenkova please attach screenshots

**Comment by roman-strilets** [comment]
SHA-1: 913c51ac6a64567f6b4697c51e373b3c5eca85d3
implemented ImportRecovery wrapper for android

**Comment by Denis-Asipenko** [comment]
@Miolin after restoring the wallet by connecting to the local node, in the settings displayed that the wallet is connected to the random node.

**Comment by Denis-Asipenko** [comment]
checked
