### ISSUE TITLE
Settings screen-sort tags alphabetically.

### ISSUE THREAD

**Issue by Denis-Asipenko** [BeamMW/android-wallet#362]
Numbers in ascending order.
If the tag contains only characters, it must be at the end of the list.
![image](https://user-images.githubusercontent.com/45556620/66203397-ef9a2500-e6b0-11e9-9d36-0b10e60b8ccd.png)

**Comment by Denis-Asipenko** [comment]
@DenisDemyanko 
1. Forbid duplicate names at the time of creation. Even if you set a different color for the name
2. Names with a small letter must be after names with a big letter if they begin with the same letter
![image](https://user-images.githubusercontent.com/45556620/72259591-e90d3900-3621-11ea-91a7-a46a8a9002e9.png)
![image](https://user-images.githubusercontent.com/45556620/72260935-e9f39a00-3624-11ea-86e0-85dbeb30ac48.png)

**Comment by Sergei-Beam** [comment]
checked
