### ISSUE TITLE
Easy onboarding

### ISSUE THREAD

**Issue by alexandrashelenkova** [BeamMW/android-wallet#368]

**Comment by dariatarakanova** [comment]
Screens are here: https://app.zeplin.io/project/5ba9be48f029d520c456f395/dashboard?seid=5da6eb9c0ffcaa17e913b6e0

1. Add "I will do it later" button on seed phrase screen, if user chooses that do not show seed phrase confirmation flow.
2. On main screen show Get beams and Secure your phrase cards (user can close it). Remove Transactions list header, leave only empty state icon and text (ability to go to Payment proof flow won't be here also by now until we will find a better place for that).
3. When user choose Get beams - show external link alert and send user back to the main screen (no get beams card anymore).
4. After user's balance reach 10 beams, the complete verification card couldn't be hidden anymore.
5. In settings add 2 items: Get beams from the community faucet (hide after user receives his first beams - even if not from the faucet) and Complete wallet verification (hide after user complete it). Reorganise items on Settings screen required too.

**Comment by DenisDemyanko** [comment]
please notice:
after discussed with @sasha-abramovich 
1. minimum amount is 100 beam
2. order on settings screen should be like ios https://app.zeplin.io/project/5c73dc8aa74b4b4085a86a91/screen/5cc26a424a92851016e146d8

**Comment by Sergei-Beam** [comment]
4. User still have the ability to hide the card but after user's balance reaches 10 beams it should be forbidden
![image](https://user-images.githubusercontent.com/44496108/72705633-059ef900-3b6d-11ea-976f-2c0eac6af743.png)
5. Settings
Card and settings item `Get beams from the community` should be hidden forever if user at least once get beams for the faucet or from another side

**Comment by Sergei-Beam** [comment]
checked
