### ISSUE TITLE
Create settings screen

### ISSUE THREAD

**Issue by vain-onnellinen** [BeamMW/android-wallet#37]
https://app.zeplin.io/project/5ba9be48f029d520c456f395/screen/5c0fd36b77c41daf9b95e562

**Comment by sasha-abramovich** [comment]
Only the relevant settings should be implemented:
- Node IP (which was randomly selected) - read only
- Sending logs when problem happens (button)
- Change wallet password

@alexandrashelenkova please provide designs

**Comment by sasha-abramovich** [comment]
@alexandrashelenkova please consider the design for https://github.com/BeamMW/android-wallet/issues/90

**Comment by sasha-abramovich** [comment]
@kaminskyelina: thanks, @alexandrashelenkova is on it.

**Comment by alexandrashelenkova** [comment]
Settings screen is here zpl.io/bJ7ALpx

**Comment by alexandrashelenkova** [comment]
@kaminskyelina please have a look at new version of settings screen

**Comment by Denis-Asipenko** [comment]
checked
