### ISSUE TITLE
Add refresh by pulling screen down (main screen and transactions lists)

### ISSUE THREAD

**Issue by alexandrashelenkova** [BeamMW/android-wallet#371]
Add default Android refresh on main wallet screen and transactions list screen.
Arrow's colour should be same as app background colour.
![2019-10-15 10 54 06](https://user-images.githubusercontent.com/7249484/66796408-21757c00-ef3a-11e9-8137-28e236d21b1a.jpg)

**Comment by Sergei-Beam** [comment]
checked
