### ISSUE TITLE
Ask password when change node settings

### ISSUE THREAD

**Issue by alexandrashelenkova** [BeamMW/android-wallet#373]

**Comment by dariatarakanova** [comment]
Please add this alert after user changes node settings:

finger+password: https://zpl.io/2ZmxZnw
finger+password (error): https://zpl.io/Vqk6pk4
face+password (error): https://zpl.io/bJgNr1n
password: https://zpl.io/aR9NZ0p

@alexandrashelenkova could you please check if all good

**Comment by Denis-Asipenko** [comment]
checked
