### ISSUE TITLE
Change "General settings" to "Feedback" on Settings screen

### ISSUE THREAD

**Issue by dariatarakanova** [BeamMW/android-wallet#376]
Please change title of second "General settings" block (where rate app and report a problem is) to "Feedback" on Settings screen

![image](https://user-images.githubusercontent.com/47353570/66913229-e5671780-f01c-11e9-92dc-9b0015709296.png)

**Comment by Sergei-Beam** [comment]
Irrelevant since we remade whole settings screen 
![Screenshot_2020-01-13-16-05-02-556_com mw beam beamwallet masternet](https://user-images.githubusercontent.com/44496108/72258233-9da55b80-361e-11ea-840f-779ebbd45dd9.jpg)
