### ISSUE TITLE
Payment proof (if transactions list is empty)

### ISSUE THREAD

**Issue by alexandrashelenkova** [BeamMW/android-wallet#378]
- Add item "Payment proof" in settings https://zpl.io/V4zGXJ0 (Setting have to be regrouped as weel, with new section UTILITIES)

- Item should open Payment proof screen https://zpl.io/aNzL1PD

- If transactions list is empty, Payment proof would be available only from Settings

- If there are transactions in the wallet, Payment proof would be available from Settings and Transactions list screen (https://zpl.io/beW1OMN).

**Comment by Denis-Asipenko** [comment]
checked
