### ISSUE TITLE
Add "Select all" button in multi selection mode (transactions, addresses screens)

### ISSUE THREAD

**Issue by alexandrashelenkova** [BeamMW/android-wallet#380]

**Comment by dariatarakanova** [comment]
Addresses: 
1 selected https://zpl.io/bJWLBxK
2 selected https://zpl.io/bekymjW
all selected  https://zpl.io/VKLQ7j6

Transactions: 
1 selected https://zpl.io/boL4v5E
2 selected https://zpl.io/bWXKgP1
all selected https://zpl.io/bA5DxBx

**Comment by Sergei-Beam** [comment]
1. System should untick checkbox automatically if user first of all ticked checkbox to select all allowed rows and then manually unticked one or more rows
2. System should tick checkbox automatically if user select all allowed rows manually

**Comment by Sergei-Beam** [comment]
Checked
