### ISSUE TITLE
Add actions for long tap on app icon

### ISSUE THREAD

**Issue by alexandrashelenkova** [BeamMW/android-wallet#381]
Android should have same actions as it currently is on iOS 
![IMG_3335](https://user-images.githubusercontent.com/7249484/67195419-7c700d00-f42b-11e9-8f79-525001785a25.PNG)

**Comment by alexandrashelenkova** [comment]
Some examples of Android realisation 
![2019-10-21 17 53 41](https://user-images.githubusercontent.com/7249484/67195620-da045980-f42b-11e9-883e-46db0e5aadb9.jpg)
![2019-10-21 17 53 53](https://user-images.githubusercontent.com/7249484/67195621-da045980-f42b-11e9-8492-6a00097dbd18.jpg)
![2019-10-21 17 54 22](https://user-images.githubusercontent.com/7249484/67195622-da045980-f42b-11e9-9a96-8165971c8238.jpg)
![2019-10-21 17 54 26](https://user-images.githubusercontent.com/7249484/67195623-da9cf000-f42b-11e9-90b9-336cd1bd88fa.jpg)

**Comment by dariatarakanova** [comment]
Please make this functionality relying on design example:
https://app.zeplin.io/project/5ba9be48f029d520c456f395/dashboard?seid=5daee871d3ae88554d596a5d

Please let me know if you need anything else

**Comment by Sergei-Beam** [comment]
checked
