### ISSUE TITLE
Add version number on login/restore screens

### ISSUE THREAD

**Issue by alexandrashelenkova** [BeamMW/android-wallet#382]
Currently version number user can see only on very first screen https://zpl.io/br0v8YW
Let's also add it on:

- Input password screens (while login to existed wallet) https://zpl.io/brllDmr
- Restore and creating wallet loading screens https://zpl.io/29PPrOe https://zpl.io/aX9J9rX

**Comment by Denis-Asipenko** [comment]
checked
