### ISSUE TITLE
Check buttons position on all screens

### ISSUE THREAD

**Issue by dariatarakanova** [BeamMW/android-wallet#383]
Basic rule for all screen of login/restore flow and screen with one or 2 input fields:

- if there's no need to type in anything and show keyboard - button should be on fixed height from the bottom of the screen (100 pt)
examples
https://zpl.io/25ww7g3
https://zpl.io/brlk0B5

- if there're input fields, button should have fixed distance from input field (60 pt)
examples
https://zpl.io/aMj1B17
https://zpl.io/brllDmr
https://zpl.io/2EWPe3e

Exceptions:
https://zpl.io/a3RRwBN (error might be long so button should be 130 pt after input line)
https://zpl.io/aXkWmlg (on smallest screen there's not enough space to make height from the bottom of the screen 100 pt (for bigger screens it should be 100 pt though))

**Comment by VladislavKulyba** [comment]
1. In the field Send and Receive should be 30 pt from the last element to the button
![image](https://user-images.githubusercontent.com/51320829/72803958-69561e80-3c60-11ea-8aa9-b374664dbb90.png)

2. In this popup distance from input field is 50 pt, should be 60 pt
![Snag_86f919](https://user-images.githubusercontent.com/51320829/72804448-6a3b8000-3c61-11ea-9596-3bf25826386b.png)

3. In the screen with entering password after restore the distance from input field should be 60 pt
![Snag_89cac7](https://user-images.githubusercontent.com/51320829/72804626-d8804280-3c61-11ea-8034-cf3d839fa6a5.png)

4. Restore wlllet. The buttons should have fixed distance from input field (60 pt) from last words
 ![Snag_927902](https://user-images.githubusercontent.com/51320829/72805112-2cd7f200-3c63-11ea-84be-55d11a479891.png)

5. In the screens with input field and other elements (example: tags, add contact), the distance should be 60 pt from the last element to the button
![Snag_8ef625](https://user-images.githubusercontent.com/51320829/72804889-a4595180-3c62-11ea-9cc8-d3c595d9c2e5.png)

6. The button should have fixed distance from input field (60 pt) should be done for all screens with entering password (seed verification, show owner key)
![Snag_983a37](https://user-images.githubusercontent.com/51320829/72805490-0d8d9480-3c64-11ea-8ffa-0d7ac50e8e8a.png)

**Comment by VladislavKulyba** [comment]
Checked
