### ISSUE TITLE
Export / import transaction history, tags and addresses (in settings)

### ISSUE THREAD

**Issue by alexandrashelenkova** [BeamMW/android-wallet#384]

**Comment by dariatarakanova** [comment]
- Add "Export wallet data" and "Import wallet data" on Settings screen https://zpl.io/V4zGXJ0
- If user choses export, open this popup https://zpl.io/aXmmwNX (by default all items in the list should be selected). 
- Next open popup with 2 options save or share https://zpl.io/bJggG4K
- If user choses "save to downloads" download and show this bar https://zpl.io/bADDlJP
- If user choses "share" open default bottom sheet https://zpl.io/bzjj6r7

**Comment by dariatarakanova** [comment]
@DenisDemyanko @Denis-Asipenko I have also cleated design for alert before importing https://zpl.io/an70Y7A

It should appears just after tap on Import wallet data and before https://zpl.io/aMjjj93

**Comment by Roberrtt** [comment]
No pop-up  when there's a flashcard
![Screenshot_361](https://user-images.githubusercontent.com/50007056/72601910-61784080-3927-11ea-8767-86e4997f847f.png)

There's no alert when a date is imported to a wallet with a different seed phrase 
![Screenshot_360](https://user-images.githubusercontent.com/50007056/72601968-8076d280-3927-11ea-8488-bcccc2d285a2.png)

**Comment by DenisDemyanko** [comment]
@Roberrtt 
No pop-up when there's a flashcard

we use standard file picker. we don't should display this message. If we want use own picker, then yes. But this is big task.

**Comment by Roberrtt** [comment]
checked
