### ISSUE TITLE
Update Beam Wallet app icon

### ISSUE THREAD

**Issue by dariatarakanova** [BeamMW/android-wallet#386]
Please update app icon for
Mainnet - https://drive.google.com/drive/u/1/folders/1iPBzeULjeZmOiZocBOYjTshnfDKb_9Xz
Testnet - https://drive.google.com/drive/u/1/folders/1U8pEk1UULpF5wzh8axFwq6x8ypXPS3F3
Masternet - https://drive.google.com/drive/u/1/folders/1zLfGefd-vvBrNrbH8uXIP0ANUvtcLiYQ

**Comment by Denis-Asipenko** [comment]
checked on masternet
