### ISSUE TITLE
Share transaction details image - make image size depends on content

### ISSUE THREAD

**Issue by dariatarakanova** [BeamMW/android-wallet#388]
All text should be visible on transaction details image

![image](https://user-images.githubusercontent.com/47353570/68018040-ce712800-fca0-11e9-8a79-b7c3aefafa5b.png)

**Comment by Denis-Asipenko** [comment]
checked on masternet.
![image](https://user-images.githubusercontent.com/45556620/72326641-9afb4280-36c0-11ea-85b4-9a390b0a1397.png)
