### ISSUE TITLE
Make sections on Settings screen

### ISSUE THREAD

**Issue by dariatarakanova** [BeamMW/android-wallet#389]
To avoid long scroll on Settings screen please make sections with inner screens:
![image](https://user-images.githubusercontent.com/47353570/68297946-d49c4580-00a0-11ea-80bb-dd1efa0acd7d.png)

Please notice, when tap on General item opens - https://zpl.io/a7vX0n8 - with title "General". The same for all items that have inner screens.

All screens here:
https://app.zeplin.io/project/5ba9be48f029d520c456f395/dashboard?seid=5dc2be1a0f24826062fe4b60

**Comment by Denis-Asipenko** [comment]
checked
