### ISSUE TITLE
Add gradient to Testnet wallet screens

### ISSUE THREAD

**Issue by dariatarakanova** [BeamMW/android-wallet#390]
Please add gradient to next screens:
Main wallet screen
Transactions
Addresses
UTXO
Settings

Now we have gradients only on Send and Receive screens.

Design here: https://zpl.io/V1p7OrZ

**Comment by Denis-Asipenko** [comment]
![image](https://user-images.githubusercontent.com/45556620/72610913-bde45b80-3939-11ea-90e7-9f1d3b28f861.png)

**Comment by Denis-Asipenko** [comment]
checked
