### ISSUE TITLE
Show seed phrase - create screens

### ISSUE THREAD

**Issue by dariatarakanova** [BeamMW/android-wallet#392]
1) Add item menu "Show seed phrase" on screen Settings/Privacy - https://zpl.io/2ExnZKM
2) Next open screen with fingerpring and then password - https://zpl.io/a8R5mwx https://zpl.io/2vAEz6n 
3) Next show screen with seed phrase https://zpl.io/bzjPG6z

**Comment by Sergei-Beam** [comment]
Irrelevant since we decided to show seed only until the user doesn't complete verification
