### ISSUE TITLE
Easy onboarding screen - change phrase

### ISSUE THREAD

**Issue by dariatarakanova** [BeamMW/android-wallet#397]
Change “secure your phrase” to “complete verification” on https://zpl.io/aXmXYzK and https://zpl.io/2Zmrq5G

**Comment by Sergei-Beam** [comment]
checked

**Comment by Sergei-Beam** [comment]
According to design the text should be "complete verification"
https://zpl.io/2Zmrq5G
![image](https://user-images.githubusercontent.com/44496108/72600315-73a4af80-3924-11ea-8f8d-722b1030c61a.png)

**Comment by Sergei-Beam** [comment]
checked
