### ISSUE TITLE
Create utxo details screen

### ISSUE THREAD

**Issue by vain-onnellinen** [BeamMW/android-wallet#40]
https://app.zeplin.io/project/5ba9be48f029d520c456f395/screen/5bfa78ff92d01e7ea2aa7391

**Comment by Denis-Asipenko** [comment]
Edit utxo details screen
![screenshot_3](https://user-images.githubusercontent.com/45556620/51540641-091f7780-1e68-11e9-865e-24d77d4daca9.png)

**Comment by Denis-Asipenko** [comment]
checked
