### ISSUE TITLE
The seed phrases are not accepted

### ISSUE THREAD

**Issue by Roberrtt** [BeamMW/android-wallet#413]
When you enter the correct words, they are highlighted in red and it isn't possible to complete verification
![Screenshot_355](https://user-images.githubusercontent.com/50007056/72416589-17a52400-3788-11ea-8ca9-574124ae9e5b.png)

**Comment by Sergei-Beam** [comment]
The seed phrase confirmation window doesn't even open on my phone ![2020-01-15_12-52-17](https://user-images.githubusercontent.com/44496108/72423796-f0edea00-3795-11ea-8b42-362696dbd96f.gif)

**Comment by Roberrtt** [comment]
checked
