### ISSUE TITLE
If is located in the settings, the back button doesn't exit the wallet

### ISSUE THREAD

**Issue by Roberrtt** [BeamMW/android-wallet#415]
When we are in the settings, using the "back" button from the app doesn't exit
Step:
- open wallet
- enter password
- go to tab settings
- click 2 times back
Expected: exits the app
Actual: side menu opens
[Video.zip](https://github.com/BeamMW/android-wallet/files/4064793/Video.zip)

**Comment by DenisDemyanko** [comment]
@Roberrtt 
No. 
Expected result - the main wallet screen opens, application should not close.
In any case, this does not work now. fix it.

**Comment by Roberrtt** [comment]
checked
