### ISSUE TITLE
Wallet crash when you click 2 times on the "start using your wallet" button

### ISSUE THREAD

**Issue by Roberrtt** [BeamMW/android-wallet#416]
When creating a wallet, if you click 2 times on the "start using your wallet" button, the wallet crashes
Steps:
- run app 
- click "create new wallet"
- click  "I understand"
- click  "I will do it later"
- enter and confirm password
- click 2 times  "start using your wallet"
Expected: opened popup " Use you Fingerprint"
Actual: wallet crashes
[VideoCrash.zip](https://github.com/BeamMW/android-wallet/files/4064960/VideoCrash.zip)

**Comment by Denis-Asipenko** [comment]
checked
