### ISSUE TITLE
Receive screen doesn't close after share the address. 

### ISSUE THREAD

**Issue by Denis-Asipenko** [BeamMW/android-wallet#417]
After share the address "Receive" screen needs to close and go over on "Wallet" screen.
Str:
1. Go to "Receive" screen.
2. Share address.
Expected:  "Receive" screen closed and goes over on "Wallet" screen.
Actual: After share the address "Receive" screen doesn't close.

**Comment by DenisDemyanko** [comment]
In most cases this impossible. We can't detect the user cancel sharing or share completed

**Comment by Denis-Asipenko** [comment]
Impossible to implement.
