### ISSUE TITLE
The wallet.dat imported to wallet with a different seed phrase

### ISSUE THREAD

**Issue by Roberrtt** [BeamMW/android-wallet#421]
When importing a file to  wallet with a different seed phrase, data must not be imported
Precondition
There is wallet.dat from another wallet. Wallet created and open
Step:
- go to settings
- click utilities 
- click Import wallet data
- click import in popup
- choose wallet.dat
- go to address >contact
[Video.zip](https://github.com/BeamMW/android-wallet/files/4071633/Video.zip)

Expected: data doesn't import 
Actual: contacts and tags are imported

**Comment by Roberrtt** [comment]
If you select only contacts and tags in the export, the file is imported to wallet with a different seed phrase

**Comment by DenisDemyanko** [comment]
@Roberrtt i think is ok. currently we checking only transactions and own addresses.

**Comment by Roberrtt** [comment]
checked
