### ISSUE TITLE
When importing any file with the format .dat, wallet is crashed 

### ISSUE THREAD

**Issue by Roberrtt** [BeamMW/android-wallet#422]
If we import any file with the format .dat (except wallet.dat) then the wallet crashed

Step
- open the wallet
- go to settings
- click utilities
- click import wallet data > import
- choose any file with format .dat
[Video.zip](https://github.com/BeamMW/android-wallet/files/4072134/Video.zip)

Expected: wallet shows an error
Actual: wallet crashed

**Comment by Denis-Asipenko** [comment]
checked
