### ISSUE TITLE
Displaying the amount in second currency

### ISSUE THREAD

**Issue by dariatarakanova** [BeamMW/android-wallet#435]
Please add second currency amount on next screens:

1) Settings screen - add second currency (usd / btc) - https://zpl.io/adG8ZOl
2) Main wallet screen - https://zpl.io/VO7zZQL
3) Send screens (amount + total available + fee) - https://zpl.io/a3OYmQx
4) Transaction fee screen - https://zpl.io/bej7ZGz and https://zpl.io/brQJxOD
5) Transaction confirmation screen - https://zpl.io/anEWwvA
6) Receive screens - https://zpl.io/b6mYqYK and https://zpl.io/2vkGxLP
7) Transaction detail screens - https://zpl.io/VY7936E 
8) Share transaction details - https://zpl.io/b6mYqKR

**Comment by dariatarakanova** [comment]
@DenisDemyanko  Please add "Off" choice to secondary currency
https://zpl.io/2E17kon
![image](https://user-images.githubusercontent.com/47353570/83410568-44986180-a41f-11ea-9747-fa5f81c9c869.png)

**Comment by Denis-Asipenko** [comment]
1.
![image](https://user-images.githubusercontent.com/45556620/84650231-81308680-af10-11ea-9a46-30da3c0a12fb.png)
2.
![image](https://user-images.githubusercontent.com/45556620/84650347-b8069c80-af10-11ea-9a9d-4b19236fdc72.png)
3.
![image](https://user-images.githubusercontent.com/45556620/84651413-97d7dd00-af12-11ea-9780-223f6a390e8c.png)

**Comment by Denis-Asipenko** [comment]
checked
