### ISSUE TITLE
Create Notifications 

### ISSUE THREAD

**Issue by dariatarakanova** [BeamMW/android-wallet#439]
1) please add Notifications to side menu https://zpl.io/VD0gENg
2) create Notifications item in Settings https://zpl.io/bep6zrD and https://zpl.io/boX3qRW
3) create Notifications screen https://zpl.io/bA1RoX6
4) All read notifications https://zpl.io/V1BxKoJ
5) create Notification details view for "update" notification https://zpl.io/Vk61jDW
6) create Notification details view for "in the press", "hot news" etc.. https://zpl.io/2jJ3GpO
7) after tap on "address" notification - open screen with address details https://zpl.io/aNQxXpD
8) after tap on "transaction" notification - open screen with transaction details https://zpl.io/VY7936E
9) Empty notifications screen https://zpl.io/V1Bx0wZ
10) when privacy mode is on do not show amounts on notifications https://zpl.io/2yZ3nOq

When open Notifications first time new notifications should be highlighted (as on design https://zpl.io/bA1RoX6). Notifications become read when user open it or if he goes to another screen and then come back https://zpl.io/V1BxKoJ.

In-app notification https://zpl.io/V1BxKoJ
- news
- updates (if the app do not update automatically after 1-2 days)

Push notification https://zpl.io/a70PMxY
- transactions (send, receive, failed)
- AS (completed, failed, expired)
- addresses (expired)

all screens here https://app.zeplin.io/project/5ba9be48f029d520c456f395/dashboard?seid=5ea7eb1340adc5243bc22430

**Comment by dariatarakanova** [comment]
Address expiration was removed from design https://zpl.io/2E0Ej5l
![image](https://user-images.githubusercontent.com/47353570/83427318-38b99900-a439-11ea-9776-d8c000bd5ff0.png)

**Comment by Denis-Asipenko** [comment]
1. align the number on the notification icon.
![image](https://user-images.githubusercontent.com/45556620/84667370-ee511580-af2a-11ea-83e1-45827618ba04.png)
2. Also, implement this.

> Notifications become read when user open it or if he goes to another screen and then come back h

>

**Comment by Denis-Asipenko** [comment]
Privacy mode does not work on the notifications screen if the user is on this screen but on another screen work normally.
![image](https://user-images.githubusercontent.com/45556620/84775329-bfe54000-afe7-11ea-986b-1463c77ae2b5.png)
Please, align this.
![image](https://user-images.githubusercontent.com/45556620/84775504-fd49cd80-afe7-11ea-85b5-f6c09b7f47cc.png)
Also, need to be the possibility to display the update notification in three digits. Currently only two digits.

**Comment by Denis-Asipenko** [comment]
checked
