### ISSUE TITLE
Support Lelantus-MW: unlinking flow

### ISSUE THREAD

**Issue by dariatarakanova** [BeamMW/android-wallet#441]
Designs: https://app.zeplin.io/project/5ba9be48f029d520c456f395/dashboard?seid=5ebebbe59f02512fd66688c7

1) Add icon on Available block (available and unlinked tabs) https://zpl.io/bPJg0Zl
![image](https://user-images.githubusercontent.com/47353570/83406585-a94fbe00-a417-11ea-9242-505b9f3a7b78.png)
![image](https://user-images.githubusercontent.com/47353570/83406604-b1a7f900-a417-11ea-9856-546d0665d53a.png)

2) If in the wallet 0 Beams and no unlinked do not show tabs and icon "unlinked" https://zpl.io/aBJp51q
![image](https://user-images.githubusercontent.com/47353570/83406647-c4bac900-a417-11ea-96e1-ab0a1a87850d.png)

3) Create tab "unlinked" and show it only if there are unlinked funds in the wallet  https://zpl.io/bPJg0Zl
![image](https://user-images.githubusercontent.com/47353570/83406678-d13f2180-a417-11ea-80cc-45914b1fc4aa.png)

4) Unlinked tab view https://zpl.io/VKZLqNP
![image](https://user-images.githubusercontent.com/47353570/83406720-ea47d280-a417-11ea-942d-45cfca203709.png)

5) If all funds in the wallet unlinked - make "unlinked" icon inactive https://zpl.io/29xEZOA
![image](https://user-images.githubusercontent.com/47353570/83406737-f59afe00-a417-11ea-97f8-4b1755129583.png)

6) Create screen Unlink https://zpl.io/bAJWEBO
![image](https://user-images.githubusercontent.com/47353570/83406754-fe8bcf80-a417-11ea-8517-f514704295ff.png)

7) Create confirmation screen https://zpl.io/ag46KlR
![image](https://user-images.githubusercontent.com/47353570/83406768-05b2dd80-a418-11ea-97f2-30b230a024db.png)

8) When unlink "in progress" - show also % below status
![image](https://user-images.githubusercontent.com/47353570/83406781-0f3c4580-a418-11ea-8d27-ce4cb9f6d8eb.png)

9) Unlink statuses icons https://zpl.io/b6xJ58q

10) Unlinked transaction details https://zpl.io/a8ovK94
![image](https://user-images.githubusercontent.com/47353570/83406810-1c593480-a418-11ea-87d2-77edf4ec03f6.png)

11) Unlinking transaction details https://zpl.io/bJJ0qy3
![image](https://user-images.githubusercontent.com/47353570/83406823-24b16f80-a418-11ea-92e7-5c6baf729a87.png)

12) Transaction details actions: https://zpl.io/2pGjOEJ and https://zpl.io/a79x41Y
![image](https://user-images.githubusercontent.com/47353570/83406843-2ed36e00-a418-11ea-9275-365104a5a7c0.png)

![image](https://user-images.githubusercontent.com/47353570/83406859-35fa7c00-a418-11ea-8645-0b2fcd69c69d.png)

13) Stop unlinking alert https://zpl.io/b6doMqj
![image](https://user-images.githubusercontent.com/47353570/83406930-64785700-a418-11ea-92de-a0c34181ebe3.png)

14) Select transaction on wallet screen https://zpl.io/V1G5qLQ
![image](https://user-images.githubusercontent.com/47353570/83406951-6f32ec00-a418-11ea-96ac-7640563e5409.png)

**Comment by gingervik** [comment]
irrelevant
