### ISSUE TITLE
Support Lelantus-MW: send screen

### ISSUE THREAD

**Issue by dariatarakanova** [BeamMW/android-wallet#443]
Please add possibility to send unlinked funds https://zpl.io/Vxxv6Zg

1) Add switcher "Unlinked funds only" on Amount section
![image](https://user-images.githubusercontent.com/47353570/83407048-9b4e6d00-a418-11ea-9149-6887607d0915.png)

2) When "Unlinked funds only" is ON:
- "TOTAL AVAILABLE" change to "UNLINK AVAILABLE"
- Button "add all" change to "add all unlinked"

3) "Unlinked funds only" is OFF https://zpl.io/bLln5ld
![image](https://user-images.githubusercontent.com/47353570/83407071-a5706b80-a418-11ea-9602-8960081426e6.png)

4) Please change design for button "add all (unlinked)" - remove border
![image](https://user-images.githubusercontent.com/47353570/83407135-bcaf5900-a418-11ea-9ca7-14fe3bfac069.png)

**Comment by dariatarakanova** [comment]
@DenisDemyanko  please make a small change https://zpl.io/Vxxv6Zg

1)please remove border on button "change"

![image](https://user-images.githubusercontent.com/47353570/83559531-6546e100-a51d-11ea-849f-5663ceb1ed21.png)

**Comment by dariatarakanova** [comment]
@DenisDemyanko  new **UPD:**

1) redesign for send to field https://zpl.io/Vxxv6Zg Please display only 6 first and 6 last symbols of token. Do not highlight them with pink, just white text.
![image](https://user-images.githubusercontent.com/47353570/86026538-3b0f1300-ba38-11ea-96e5-6a91174c71ef.png)

2) Show token screen https://zpl.io/2EN93Kl
![image](https://user-images.githubusercontent.com/47353570/86026675-6691fd80-ba38-11ea-8822-57ddda2a8521.png)

**Comment by gingervik** [comment]
irrelevant
