### ISSUE TITLE
Add versions to generated token

### ISSUE THREAD

**Issue by Roberrtt** [BeamMW/android-wallet#445]
Will need to check when the token will be implemented
BeamMW/beam#1435

**Comment by DenisDemyanko** [comment]
This task can't be done in this release.
This big solution. We need implement assets.

**Comment by KatsiarynaV** [comment]
@DenisDemyanko This task was not implemented in version 5.1. Please implement this task.

**Comment by KatsiarynaV** [comment]
1.When user insert address generated by newer version text about address version doesn't fit on the screen and "show address" button and address expiration isn't displayed
![13](https://user-images.githubusercontent.com/68267190/92695874-c880b480-f351-11ea-8061-ce714f220027.jpg)
![15](https://user-images.githubusercontent.com/68267190/92696211-3927d100-f352-11ea-910b-9453a3129c9c.jpg)
2. When user minimize wallet screen and then reopen it text about address version is disappear
![19](https://user-images.githubusercontent.com/68267190/92702062-6af06600-f359-11ea-8532-aa12cf78b945.gif)
3. Text color should be gray
![20](https://user-images.githubusercontent.com/68267190/92702769-3f21b000-f35a-11ea-882d-9ebdd6276341.jpg)

**Comment by KatsiarynaV** [comment]
When user insert address generated by newer version "show address" button and address expiration (one-time use or permanent) isn't displayed
![21](https://user-images.githubusercontent.com/68267190/92733096-efee7600-f37f-11ea-8168-9c1a70dfd9cc.jpg)
![15](https://user-images.githubusercontent.com/68267190/92732623-5f179a80-f37f-11ea-9093-820bdb32bad9.jpg)

**Comment by KatsiarynaV** [comment]
Change text sequence as in UI wallet. Text about address version should be right under the addres
![22](https://user-images.githubusercontent.com/68267190/92890508-d997f700-f41f-11ea-995d-e92b829dc070.jpg)
![23](https://user-images.githubusercontent.com/68267190/92890681-00562d80-f420-11ea-9ba3-dc17e6d2acc3.jpg)

**Comment by KatsiarynaV** [comment]
Checked
