### ISSUE TITLE
Send screen - impossible to enter an amount without 0 at the beginning (0.3 BEAM etc...)

### ISSUE THREAD

**Issue by dariatarakanova** [BeamMW/android-wallet#446]
There is no way to enter .3 on amount field, but only 0.3.

This issue is on ios, please check it on android @Denis-Asipenko @VladislavKulyba 
ios bug: https://github.com/BeamMW/ios-wallet/issues/383

**Comment by kazaryan-t** [comment]
Checked.

**Comment by rimoney** [comment]
check it
