### ISSUE TITLE
Avoid showing the Loading screen whenever possible

### ISSUE THREAD

**Issue by sasha-abramovich** [BeamMW/android-wallet#447]

**Comment by Denis-Asipenko** [comment]
the download screen is displayed when creating a new wallet
![D629E0FF-727C-4C8A-BC6F-CABAC0C20E39](https://user-images.githubusercontent.com/45556620/92576649-70cf4400-f292-11ea-82a1-e7e7cb355b64.GIF)

**Comment by DenisDemyanko** [comment]
Cannot be removed when creating and restoring a wallet.

**Comment by Denis-Asipenko** [comment]
checked
