### ISSUE TITLE
Add wallet ID to TX detail 

### ISSUE THREAD

**Issue by dariatarakanova** [BeamMW/android-wallet#449]
Please Add wallet ID to TX detail https://zpl.io/a89Rn5g
![image](https://user-images.githubusercontent.com/47353570/83407560-a81f9080-a419-11ea-8289-f0017fa27f5d.png)

and to shared transaction detail img
![image](https://user-images.githubusercontent.com/47353570/83407814-2aa85000-a41a-11ea-89bf-84be4d376b62.png)

**Comment by kazaryan-t** [comment]
Cannot copy and share Wallet ID field.

**Comment by Denis-Asipenko** [comment]
@DenisDemyanko please, implement changes.
"WALLET ID" change on "IDENTITY" .
![image](https://user-images.githubusercontent.com/45556620/92567943-18df1000-f287-11ea-8ac0-7ccf6799948f.png)
https://app.zeplin.io/project/5ba9be48f029d520c456f395/screen/5e13081bd30a77171f0683e4

Current:
![image](https://user-images.githubusercontent.com/45556620/92568058-4461fa80-f287-11ea-8537-135df0650e85.png)

**Comment by kazaryan-t** [comment]
Not fixed.
https://github.com/BeamMW/android-wallet/issues/449#issuecomment-688355635
https://github.com/BeamMW/android-wallet/issues/449#issuecomment-689366391
![1](https://user-images.githubusercontent.com/68247034/92629377-e4934000-f2d6-11ea-819f-a549f0319499.jpg)

**Comment by KatsiarynaV** [comment]
Need to make it possible to copy field "Identity"
![24](https://user-images.githubusercontent.com/68267190/92924150-22ac7300-f441-11ea-86e1-319658923628.jpg)

**Comment by KatsiarynaV** [comment]
On the shared transaction detail image:
1. Сhange currency icon to BEAM
2. Fields "Identity" and "Kernel ID" overlap each other

![25](https://user-images.githubusercontent.com/68267190/93051613-77cccc80-f66d-11ea-8f36-415c1705afb2.jpg)

**Comment by KatsiarynaV** [comment]
Checked
