### ISSUE TITLE
Show error in status when exchange currencies can't be shown

### ISSUE THREAD

**Issue by dariatarakanova** [BeamMW/android-wallet#450]
Please show "yellow" status when exchange rate for BTC/USD wasn't received and hide second currency:
https://zpl.io/29QOgNp

![image](https://user-images.githubusercontent.com/47353570/85409797-edddfd80-b56e-11ea-929f-55878d0495b5.png)

**Comment by KatsiarynaV** [comment]
When exchange rate for BTC/USD wasn't received hide second currency as in design
![07](https://user-images.githubusercontent.com/68267190/92454165-e53db080-f1c8-11ea-8068-63dba7a0ab0b.jpg)
![08](https://user-images.githubusercontent.com/68267190/92454174-e7077400-f1c8-11ea-8852-73ed0b6f0694.png)

**Comment by KatsiarynaV** [comment]
Hide second currency on all screens
![01](https://user-images.githubusercontent.com/68267190/92717180-79924980-f368-11ea-938a-7653766768d0.jpg)
![02](https://user-images.githubusercontent.com/68267190/92717182-7a2ae000-f368-11ea-9db0-715bd258b3db.jpg)
![03](https://user-images.githubusercontent.com/68267190/92717184-7ac37680-f368-11ea-9327-bd39cf2f46de.jpg)

**Comment by KatsiarynaV** [comment]
checked
