### ISSUE TITLE
Update the text on restore flow screens

### ISSUE THREAD

**Issue by dariatarakanova** [BeamMW/android-wallet#451]
1) Updated text for RESTORE WITH OWN NODE (advanced) section (title+description). But please check all the text: https://zpl.io/bPggEop
![image](https://user-images.githubusercontent.com/47353570/83617878-61a17180-a592-11ea-9efc-23e1503c58af.png)

2) Update text for automatic restore alert https://zpl.io/V0wdMko
![image](https://user-images.githubusercontent.com/47353570/83617928-74b44180-a592-11ea-8f32-eb1048eb70d6.png)

3) Update text for trusted node restore alert https://zpl.io/2GWxznE
![image](https://user-images.githubusercontent.com/47353570/83617989-8695e480-a592-11ea-9aac-67334d60ab93.png)

4) Update the text in red box on restore wallet node screen https://zpl.io/a3RRwBN
![image](https://user-images.githubusercontent.com/47353570/83618062-9b727800-a592-11ea-95d1-21956e05c460.png)

5) Update the text in red box on restore wallet wrong node screen https://zpl.io/VkeNz85
![image](https://user-images.githubusercontent.com/47353570/83618148-b3e29280-a592-11ea-8c15-18f907767e17.png)

6) Update the comment on Owner key screen https://zpl.io/aX9XrqE
![image](https://user-images.githubusercontent.com/47353570/83618204-ca88e980-a592-11ea-9f27-04d269859cb2.png)

7) Update the text on Not enough space for restore alert https://zpl.io/VqL85z5
![image](https://user-images.githubusercontent.com/47353570/83618271-e4c2c780-a592-11ea-85d4-e7411888383d.png)

8) Update the text the same as here: with "." and ":" https://zpl.io/aMRABDR
![image](https://user-images.githubusercontent.com/47353570/83618347-0459f000-a593-11ea-9819-033d9aa14637.png)

9) Update the text on restoring screen and add "." after "Restored 34%" https://zpl.io/25ww7g3
![image](https://user-images.githubusercontent.com/47353570/83618721-8813dc80-a593-11ea-8b9b-e313abec37d4.png)

**Comment by Denis-Asipenko** [comment]
1. 
![image](https://user-images.githubusercontent.com/45556620/84505081-ca40ca80-acc5-11ea-9332-cc7968bef8bc.png)
2.
![image](https://user-images.githubusercontent.com/45556620/84505105-d3319c00-acc5-11ea-816e-c370590f2c67.png)
3.
![image](https://user-images.githubusercontent.com/45556620/84505508-81d5dc80-acc6-11ea-8439-7bd6bdc2b413.png)

**Comment by Denis-Asipenko** [comment]
please fix
![image](https://user-images.githubusercontent.com/45556620/84649699-a375d480-af0f-11ea-8143-ff6d0ab39237.png)

**Comment by Denis-Asipenko** [comment]
checked
