### ISSUE TITLE
Receive lelantus

### ISSUE THREAD

**Issue by dariatarakanova** [BeamMW/android-wallet#454]
Please create lelantus flow for Receive https://app.zeplin.io/project/5ba9be48f029d520c456f395/dashboard?seid=5ee374e914cfd8b6649afa9a

1) Permanent token https://zpl.io/2pGDrRl
![image](https://user-images.githubusercontent.com/47353570/84503323-aa5bd780-acc2-11ea-8fcf-6f925662a56f.png)

2) One-time use token https://zpl.io/aMJMkER
![image](https://user-images.githubusercontent.com/47353570/84503253-8bf5dc00-acc2-11ea-934e-6394796e2055.png)

3) All hide view https://zpl.io/ag4Zq1O
![image](https://user-images.githubusercontent.com/47353570/84503348-b778c680-acc2-11ea-81fd-8fd42740c987.png)

4) Permanent/ One-time use (general) selection https://zpl.io/a8oOkqd
![image](https://user-images.githubusercontent.com/47353570/84503398-cc555a00-acc2-11ea-8077-374d5dd0169b.png)

5) Receive from (advanced) selection https://zpl.io/29xBkdw
![image](https://user-images.githubusercontent.com/47353570/84503373-c19ac500-acc2-11ea-946f-61cf75db99f9.png)

6) Show token https://zpl.io/2pGDrqN
![image](https://user-images.githubusercontent.com/47353570/84503436-dbd4a300-acc2-11ea-9cc9-c92178da6c71.png)

7) Show QR code https://zpl.io/bAJzk3e
![image](https://user-images.githubusercontent.com/47353570/84503455-e727ce80-acc2-11ea-9f6a-559f5130ec35.png)

**Comment by dariatarakanova** [comment]
**UPD:** @DenisDemyanko please follow this instruction

1) Permanent token - General and receive from view https://zpl.io/2pGDrRl
![image](https://user-images.githubusercontent.com/47353570/85125092-b6e8ae80-b233-11ea-8fcd-9ae09de56953.png)

2) One-time use token - General (no receive from) view https://zpl.io/aMJMkER
![image](https://user-images.githubusercontent.com/47353570/85125078-af290a00-b233-11ea-9e10-aefafc0f3de3.png)

3) Hidden view https://zpl.io/ag4Zq1O
![image](https://user-images.githubusercontent.com/47353570/85125059-a6383880-b233-11ea-9e68-c963100d4e85.png)

4) Show token https://zpl.io/2pGDrqN
![image](https://user-images.githubusercontent.com/47353570/85125030-93256880-b233-11ea-9dea-75841ea0a845.png)

5) Share QR https://zpl.io/bAJzk3e
![image](https://user-images.githubusercontent.com/47353570/85125053-9d476700-b233-11ea-95ec-324f589c94c8.png)

6) No need "prefer to receive unlinked funds"

**Comment by Denis-Asipenko** [comment]
invalid
