### ISSUE TITLE
Check all screens so that they match the design

### ISSUE THREAD

**Issue by Denis-Asipenko** [BeamMW/android-wallet#458]
We need to check all screens in the wallet so that they match the design.
![image](https://user-images.githubusercontent.com/45556620/85260826-f69dd900-b473-11ea-85a7-99e85962db3b.png)
![image](https://user-images.githubusercontent.com/45556620/85261081-5ac09d00-b474-11ea-90ee-24fc998b0b0f.png)

**Comment by kazaryan-t** [comment]
Checked.
