### ISSUE TITLE
Implement API for blockchain info

### ISSUE THREAD

**Issue by vain-onnellinen** [BeamMW/android-wallet#46]
https://app.zeplin.io/project/5ba9be48f029d520c456f395/screen/5c115f0771324f509cc751e6

**Comment by kaminskyelina** [comment]
Sasha will think and decide about a screen to present the statistics

**Comment by sasha-abramovich** [comment]
I'll close this one. We were thinking to implement a mini-explorer in the app. All the apps. This won't happen too soon anyways.
