### ISSUE TITLE
Change "Scalable confidential cryptocurrency" to "Confidential, fast, easy to use" 

### ISSUE THREAD

**Issue by dariatarakanova** [BeamMW/android-wallet#460]
https://zpl.io/aXkM95M
https://zpl.io/br0v8YW

change it everywhere it appears

**Comment by KatsiarynaV** [comment]
App's loading screen: change "Scalable confidential cryptocurrency" to "Confidential, fast, easy to use"
![06](https://user-images.githubusercontent.com/68267190/92472760-a0267800-f1e2-11ea-92b5-00e7a584dc38.jpg)

**Comment by KatsiarynaV** [comment]
Checked
