### ISSUE TITLE
Status for downed random node

### ISSUE THREAD

**Issue by dariatarakanova** [BeamMW/android-wallet#462]
New status for situation when random node is down: https://zpl.io/2ZEl63q

![image](https://user-images.githubusercontent.com/47353570/87051501-503e2b80-c208-11ea-93f7-893f14b339a1.png)

**Comment by kazaryan-t** [comment]
When connecting to a node that was unavailable, the wallet did not reconnect to another random node for more than 2 minutes.

**Comment by kazaryan-t** [comment]
Checked.
