### ISSUE TITLE
Status + TX details for Max privacy transactions

### ISSUE THREAD

**Issue by dariatarakanova** [BeamMW/android-wallet#463]
Status flow for max privacy tx: changing - in progress - sent

1) Status "changing" https://zpl.io/25RlMlj
![image](https://user-images.githubusercontent.com/47353570/87548885-cc77b980-c6b5-11ea-897a-ad7d96c4043b.png)

2) Transaction details https://zpl.io/agYEyy0
![image](https://user-images.githubusercontent.com/47353570/87548925-db5e6c00-c6b5-11ea-8820-3ba3c696563d.png)

**Comment by kazaryan-t** [comment]
Invalid.
