### ISSUE TITLE
Send - new flow with max privacy txs

### ISSUE THREAD

**Issue by dariatarakanova** [BeamMW/android-wallet#466]
Design: https://app.zeplin.io/project/5ba9be48f029d520c456f395/dashboard?seid=5f201a7d890ac8386a3e86df

1) Regular / one-time use https://zpl.io/VKMEBY7
 - Rename Send to to Transaction info.
 - Add Max privacy + switcher (here:off)
 - Advanced - Outgoing address: add "type"
 - Transaction fee for regular (not max privacy) is 100 GROTH
screenshot https://prnt.sc/tpwqzc

2) Max privacy / one-time use https://zpl.io/adORyLn
 - Max privacy + switcher (here:on) + comment under "Transaction is slower, fees are higher."
 - Transaction fee for max privacy is 1,200,000 GROTH
screenshot https://prnt.sc/tpwrhj

3) Max privacy / permanent. When token do not saved in to address book display text "Permanent token." https://zpl.io/V4WEGqQ
screenshot https://prnt.sc/tpws9l

4) Max privacy / permanent. When token SAVED in to address book display text contact name+tags https://zpl.io/aXBKyop
screenshot https://prnt.sc/tpwsm3

5) Fee error - when user wants to reduce the fee for max privacy transaction.Button "next" is inactive. https://zpl.io/amp83RK
screenshot https://prnt.sc/tpwt4o

6) Receiver requested max privacy (offline token) transaction https://zpl.io/VDypQGe
screenshot https://prnt.sc/tpwtpv

7) Receiver requested max privacy (online token) transaction https://zpl.io/2yn1MBo
screenshot https://prnt.sc/tpwu54

8) Confirmation screen https://zpl.io/adXAAPl
screenshot https://prnt.sc/tpwutq

9) Show token https://zpl.io/2GZn5wd
screenshot https://prnt.sc/tpwvjb

**Comment by Denis-Asipenko** [comment]
@DenisDemyanko changes were made to the send screen, please implement them.
https://app.zeplin.io/project/5ba9be48f029d520c456f395/dashboard?seid=5f201a7d890ac8386a3e86df

**Comment by KatsiarynaV** [comment]
1. Change text for field 'type' to "Address will expirein 2 hours after succesfull transaction" when switcher isn't enabled to permanent outgoin address. 
![01](https://user-images.githubusercontent.com/68267190/92619661-7a749e00-f2ca-11ea-90ae-98307926da7c.jpg)
![001](https://user-images.githubusercontent.com/68267190/92619817-a859e280-f2ca-11ea-8e74-6b297234bf1f.jpg)
2. When we insert a contact in field 'transaction info' switcher to max privacy isn't displayed
![03](https://user-images.githubusercontent.com/68267190/92617938-81021600-f2c8-11ea-94a3-415afeb87a06.jpg)
![003](https://user-images.githubusercontent.com/68267190/92617965-895a5100-f2c8-11ea-8098-cc6c34eb8754.jpg)
3. When we insert offline maxprivacy address address type with counter should be displayed. And need to remove switcher
![04](https://user-images.githubusercontent.com/68267190/92618377-f7067d00-f2c8-11ea-9268-b736a5a82e3b.jpg)
![004](https://user-images.githubusercontent.com/68267190/92618390-fa016d80-f2c8-11ea-9e27-680fcbf21da7.jpg)
4. On confirmation screen in fields 'transaction fee', 'total utxo value', 'change' exchange currencies should be displayed
![05](https://user-images.githubusercontent.com/68267190/92620443-51084200-f2cb-11ea-8426-98841f54b1fa.jpg)
![005](https://user-images.githubusercontent.com/68267190/92620251-1e5e4980-f2cb-11ea-9ad9-3c7db9cc69ef.jpg)
5. Add currency choice to the field amount
![06](https://user-images.githubusercontent.com/68267190/92620718-a2183600-f2cb-11ea-929c-2a339d0d53d1.jpg)
![006](https://user-images.githubusercontent.com/68267190/92620826-c5db7c00-f2cb-11ea-9598-2400384ee61a.jpg)
6. When we insert an address with requesting amount amount doesn't insert automatically
![2](https://user-images.githubusercontent.com/68267190/92621955-27e8b100-f2cd-11ea-8b0e-4add14cb19d1.jpg)

**Comment by KatsiarynaV** [comment]
1. When we insert offline maxprivacy address change text "Offline transactions: 0/10" to "Offline transactions remaining: 10"
![007](https://user-images.githubusercontent.com/68267190/92916827-8da47c80-f436-11ea-8c6a-10f3591ccd5e.jpg)
![07](https://user-images.githubusercontent.com/68267190/92916830-8ed5a980-f436-11ea-8a9a-c11d05b5c6a4.jpg)
2. On the screen "Show address" for regular permanent address (for exchange or mining pool): add field "Transaction type" and rename field "Address" to "SBBS Address"
![13](https://user-images.githubusercontent.com/68267190/92920948-d27ee200-f43b-11ea-99b3-b55e40827e6f.jpg)
![14](https://user-images.githubusercontent.com/68267190/92919434-2936ec80-f439-11ea-85bf-c5eb62d7e170.jpg)
3. On the screen "Show address" for online max privacy address: add field "Address type"
![15](https://user-images.githubusercontent.com/68267190/92921084-1a056e00-f43c-11ea-8fb8-204d3debf4c2.jpg)
![16](https://user-images.githubusercontent.com/68267190/92921188-48834900-f43c-11ea-9ee9-fcb7a06801e9.jpg)
4. On the screen "Show address" for offline max privacy address: in the field "Transaction type" remove word "offline"
![17](https://user-images.githubusercontent.com/68267190/92921431-b16ac100-f43c-11ea-80ed-5f3bda8c7d4c.jpg)
![18](https://user-images.githubusercontent.com/68267190/92921433-b29bee00-f43c-11ea-9a00-aefc0d2629fc.jpg)

**Comment by KatsiarynaV** [comment]
Change text for max privacy transactions to "Transaction is slower, receiver pays fees"
![09](https://user-images.githubusercontent.com/68267190/93300332-4126bb80-f7ff-11ea-9ca5-d559cf3b3d93.jpg)
![08](https://user-images.githubusercontent.com/68267190/93300329-408e2500-f7ff-11ea-8dd3-94a8735fdcfc.jpg)

**Comment by KatsiarynaV** [comment]
Nedd to remove switcher to max privacy
![11](https://user-images.githubusercontent.com/68267190/94782190-8b996200-03d3-11eb-8bb8-b3348512badf.jpg)

**Comment by KatsiarynaV** [comment]
There aren't max privacy transactions in 5.1. Please remove max privacy field
![12](https://user-images.githubusercontent.com/68267190/94894693-8bac6700-0492-11eb-87c4-6621204bc642.jpg)
![13](https://user-images.githubusercontent.com/68267190/94895096-5a806680-0493-11eb-9efc-2a0b132b8e8d.jpg)

**Comment by DenisDemyanko** [comment]
This should be done in other ticket.
https://github.com/BeamMW/android-wallet/issues/477

**Comment by KatsiarynaV** [comment]
Please remove offline field wneh regular address is inserted
![03](https://user-images.githubusercontent.com/68267190/95094356-7b1a1c00-0732-11eb-9f00-19a45cbed978.jpg)

**Comment by KatsiarynaV** [comment]
Checked

**Comment by KatsiarynaV** [comment]
1. Change text when we insert SBBS addres to "This type of address does not support offline transactions"
![21](https://user-images.githubusercontent.com/68267190/95954030-62c99180-0e03-11eb-8799-ed546a55d2da.jpg)
![20](https://user-images.githubusercontent.com/68267190/95953750-f3ec3880-0e02-11eb-9864-a67b49dce88d.jpg)

2. Confirmation screen for offline transactions: change field "address type" to "transactions remaining"
![22](https://user-images.githubusercontent.com/68267190/95954084-72e17100-0e03-11eb-8eab-a8830b3ff147.jpg)
![23](https://user-images.githubusercontent.com/68267190/95954087-737a0780-0e03-11eb-9d59-cac252e5a57d.jpg)
