### ISSUE TITLE
Receive screen - new flow with max privacy transactions

### ISSUE THREAD

**Issue by dariatarakanova** [BeamMW/android-wallet#467]
Design: https://app.zeplin.io/project/5ba9be48f029d520c456f395/dashboard?seid=5f201b5c12b83b36fe21fa4e
Add "Edit token" setting only for permanent token.

1) Regular / one-time use https://zpl.io/beRzGlD
screenshot https://prnt.sc/tpwzye

2) Max privacy / one-time use https://zpl.io/2v4n8Er
screenshot https://prnt.sc/tpx0vl

3) Regular / permanent https://zpl.io/2p90Nq8
screenshot https://prnt.sc/tpx2du

4) Max privacy / permanent https://zpl.io/2ZWqOoL
screenshot https://prnt.sc/tpx2r8

5) After click on "share address" display action sheet with different tokens https://zpl.io/b6rJwWy
screenshot https://prnt.sc/tpx34b

6) Show token https://zpl.io/a3nJwNQ
screenshot https://prnt.sc/tpx461

7) QR code https://zpl.io/a8g3xlX
screenshot https://prnt.sc/tpx3rq

**Comment by kazaryan-t** [comment]
There are some inconsistencies between design and Android Wallet:
 
1. Receive screen - rename Transaction comment to Comment. https://zpl.io/beRzGlD
![Screenshot_20200910-131329_Beam Wallet Masternet](https://user-images.githubusercontent.com/68247034/92727167-5fac3300-f377-11ea-9862-0fb131c1b315.jpg)

2. Receive screen - Advanced - rename Request an amount to Amount.  https://zpl.io/beRzGlD
![2](https://user-images.githubusercontent.com/68247034/92720782-ccbacb00-f36d-11ea-81d1-17549aedbb60.jpg)

3. When switcher is enabled to Max privacy transaction, there should appear the comment "Transaction is slower, receiver pays fees." under the switcher. https://zpl.io/2v4n8Er
![6](https://user-images.githubusercontent.com/68247034/92722154-d34a4200-f36f-11ea-8295-05e9aaa232c2.jpg)

4. Show token - the first letter of the button copy should be lowercase. https://zpl.io/a3nJwNQ
![7](https://user-images.githubusercontent.com/68247034/92722267-fbd23c00-f36f-11ea-985e-7eae5455f6f7.jpg)

5. Show token (for max privacy offline transaction) - need to change address type 20/10 to address type (10) as in the UI Wallet. 
![Screenshot_20200910-131406_Beam Wallet Masternet](https://user-images.githubusercontent.com/68247034/92727474-d9442100-f377-11ea-90c0-b7168744659f.jpg)
![8](https://user-images.githubusercontent.com/68247034/92722338-1ad0ce00-f370-11ea-80dc-2a906650bbad.png)

**Comment by KatsiarynaV** [comment]
Max privacy - only permanent token option should be
Remove address expiration field. It should be permanent for all max privacy transactions
![08](https://user-images.githubusercontent.com/68267190/92889747-28915c80-f41f-11ea-81ae-ac65dcef9e06.jpg)

**Comment by kazaryan-t** [comment]
Need to change the comment for Max privacy transactions, it should be iqual to the comment in UI wallet and design - _"Transaction is slower, receiver pays fees."_  https://zpl.io/2v4n8Er
![10](https://user-images.githubusercontent.com/68247034/93564444-5e3fc380-f992-11ea-8187-8b399246bbdc.png)
![11](https://user-images.githubusercontent.com/68247034/93564450-5f70f080-f992-11ea-8a1c-0cb9e7a2f124.jpg)

**Comment by KatsiarynaV** [comment]
1. For regular permanent address field 'online address (for exchange or mining pool)' is duplicated
![01](https://user-images.githubusercontent.com/68267190/95094896-16ab8c80-0733-11eb-8c3a-363895a0f76a.jpg)
2. For regular one-time use address remove field 'online address (for exchange or mining pool)' as in UI wallet
![02](https://user-images.githubusercontent.com/68267190/95094910-1a3f1380-0733-11eb-8fa7-02b049cb9dde.jpg)
![002](https://user-images.githubusercontent.com/68267190/95094918-1ca16d80-0733-11eb-86c8-a1fec7ee85b3.jpg)

**Comment by KatsiarynaV** [comment]
Not fixed:
1. For regular permanent address field 'online address (for exchange or mining pool)' is duplicated.  Please remove duplicate
![01](https://user-images.githubusercontent.com/68267190/95201607-d73f7780-07e8-11eb-961e-70b0de79767c.jpg)
2. For regular one-time use address remove field 'online address (for exchange or mining pool)' as in UI wallet
![02](https://user-images.githubusercontent.com/68267190/95201661-e6bec080-07e8-11eb-90d5-d3e430dbca2d.jpg)
![002](https://user-images.githubusercontent.com/68267190/95201667-e9b9b100-07e8-11eb-8971-018a4a39c275.jpg)

**Comment by KatsiarynaV** [comment]
Checked
