### ISSUE TITLE
Send screen - choose another currency (equivalent to BEAM)

### ISSUE THREAD

**Issue by dariatarakanova** [BeamMW/android-wallet#468]
1) Add arrow near BEAM/USD/BTC currency https://zpl.io/VKME9qX
![image](https://user-images.githubusercontent.com/47353570/88672786-89273d00-d0f0-11ea-83fc-73209460dbbc.png)

2) Choose currency screen https://zpl.io/amp8xn3
![image](https://user-images.githubusercontent.com/47353570/88673927-d6f07500-d0f1-11ea-8d25-beb2fbb59c32.png)

**Comment by KatsiarynaV** [comment]
checked
