### ISSUE TITLE
Rename token to address on all screens

### ISSUE THREAD

**Issue by Denis-Asipenko** [BeamMW/android-wallet#469]
According to the latest solutions, we do not mention the token. Rename token to address on all screens.

**Comment by KatsiarynaV** [comment]
Rename token to address on all screens
![06](https://user-images.githubusercontent.com/68267190/92711779-80698e00-f361-11ea-8ed7-0921c1cf5705.jpg)
![01](https://user-images.githubusercontent.com/68267190/92711787-81022480-f361-11ea-8af7-bd770a6fc72c.jpg)
![02](https://user-images.githubusercontent.com/68267190/92711790-819abb00-f361-11ea-95af-3fb44a9f68c5.jpg)
![04](https://user-images.githubusercontent.com/68267190/92711792-82335180-f361-11ea-9e2a-55d199a466bc.jpg)
![05](https://user-images.githubusercontent.com/68267190/92711793-82335180-f361-11ea-840a-e71f84a858b4.jpg)

**Comment by KatsiarynaV** [comment]
Checked
