### ISSUE TITLE
Add button to wallet status "cannot connect to: (node _address)" when specific node is selected

### ISSUE THREAD

**Issue by dariatarakanova** [BeamMW/android-wallet#476]
Design: https://zpl.io/anxYPnx

When wallet cannot connect to specific node please show this status + button "change". Button leads to settings/node, so user can change the node manually

![image](https://user-images.githubusercontent.com/47353570/93601069-47689380-f9c9-11ea-9d9e-7f35962918d2.png)

**Comment by kazaryan-t** [comment]
1. Please, put the wallet status "cannot connect to: (node _address)" on the same line on all screens.

https://zpl.io/anxYPnx
![Screenshot_20201211-152315_Beam Wallet Masternet](https://user-images.githubusercontent.com/68247034/101903796-de5a7b80-3bc5-11eb-98dd-5247525da9a1.jpg)

2. Need to fix the wallet status "cannot connect to: (node _address)" on **Notifications** screen.

![Screenshot_20201211-145846_Beam Wallet Masternet](https://user-images.githubusercontent.com/68247034/101904745-5d03e880-3bc7-11eb-8529-6515974f528c.jpg)

**Comment by kazaryan-t** [comment]
Checked.
