### ISSUE TITLE
Remove the online address and rename max privacy to offline

### ISSUE THREAD

**Issue by Denis-Asipenko** [BeamMW/android-wallet#477]

**Comment by dariatarakanova** [comment]
All screens here https://app.zeplin.io/project/5c73dc8aa74b4b4085a86a91/dashboard?seid=5f1ed1f2ab9a393acc565e63

**Comment by dariatarakanova** [comment]
receive screen: https://app.zeplin.io/project/5ba9be48f029d520c456f395/dashboard?seid=5f201b5c12b83b36fe21fa4e

**Comment by Denis-Asipenko** [comment]
checked
