### ISSUE TITLE
Receive screen - change text about fee for offline transactions 

### ISSUE THREAD

**Issue by dariatarakanova** [BeamMW/android-wallet#484]
https://zpl.io/2v4n8Er

This text only for offline txs.
Please change text about fee to "To spend the received coins the min transaction fee will be ~0.01 BEAM."

For regular tx the text is old "For the transaction to complete, you should get online during the 12 hours after Beams are sent."

![image](https://user-images.githubusercontent.com/47353570/95182404-3becd900-07cd-11eb-9635-48487798d9e5.png)

**Comment by kazaryan-t** [comment]
Checked.
