### ISSUE TITLE
Offline transaction status example

### ISSUE THREAD

**Issue by dariatarakanova** [BeamMW/android-wallet#485]
https://zpl.io/V1lmB4X

all icons here https://zpl.io/b6xJ58q

**Comment by kazaryan-t** [comment]
Change the icon for Received (offline) status. 
According to the design it should be an arrow with white horizontal line on the top.
https://zpl.io/b6xJ58q
![Screenshot_20201012-163542_Beam Wallet Masternet](https://user-images.githubusercontent.com/68247034/95752992-9395b380-0ca9-11eb-8083-fdc04258f885.jpg)

**Comment by kazaryan-t** [comment]
Checked.
