### ISSUE TITLE
Changes on Addresses screens

### ISSUE THREAD

**Issue by dariatarakanova** [BeamMW/android-wallet#486]
All screens here: https://app.zeplin.io/project/5ba9be48f029d520c456f395/dashboard?seid=5c518b1f5420114200108193

1) Remove expiration date https://zpl.io/VYoGK7e
2) On "My active" addresses add  feature - receive https://zpl.io/adNDnmn
3) On "Contacts" addresses add feature - send https://zpl.io/bLeeKND
4) Add identity to address details https://zpl.io/aRGBAge
5) Only 2 expirations choices: never and 24h

**Comment by KatsiarynaV** [comment]
1. Move the icon and text higher as in design
![0001](https://user-images.githubusercontent.com/68267190/95438228-ac772f80-095e-11eb-87f0-253b8065b671.jpg)
2. Tabs are hiding when we selected address. Need to add 'edit addres' button
![0003](https://user-images.githubusercontent.com/68267190/95438447-f829d900-095e-11eb-8a33-771de834283c.jpg)
3. When deleting address change "ok" button to 'delete" and word "with" to "to"
![0004](https://user-images.githubusercontent.com/68267190/95439020-bb121680-095f-11eb-9003-dd2639c25eaa.jpg)
4. On the "add contact" screen add the connection indicator
![0005](https://user-images.githubusercontent.com/68267190/95439503-64590c80-0960-11eb-99df-2d6e57612d1d.jpg)
5. Change the date type as in design
![0006](https://user-images.githubusercontent.com/68267190/95439839-d598bf80-0960-11eb-9637-7dd7de48802c.jpg)
6. On the 'edit address' screen the 'expires' block is displayed incorrectly
![0007](https://user-images.githubusercontent.com/68267190/95440134-36c09300-0961-11eb-969c-4ebda618f6f5.jpg)
7. Add address and change the text on the show QR screen as in design
![0008](https://user-images.githubusercontent.com/68267190/95440834-10e7be00-0962-11eb-9649-44c9f8d06875.jpg)

**Comment by KatsiarynaV** [comment]
Address details: remove "receive" button for my expired addresses
![202](https://user-images.githubusercontent.com/68267190/95594354-7ff10f80-0a53-11eb-8915-76c0ac293cdd.jpg)

**Comment by KatsiarynaV** [comment]
Checked
