### ISSUE TITLE
UTXO screen - changes

### ISSUE THREAD

**Issue by dariatarakanova** [BeamMW/android-wallet#487]
UTXO screens: https://app.zeplin.io/project/5ba9be48f029d520c456f395/dashboard?seid=5bfa7967d6daf54e6d2c0ef3

1) Status and date move below amount https://zpl.io/VOArlWP , https://zpl.io/anLXjKQ , https://zpl.io/bekmlYm , https://zpl.io/2jYOAwp
![image](https://user-images.githubusercontent.com/47353570/95243559-7b411700-0819-11eb-8985-9be875558f2c.png)

2) Please add Maturity and Type to UTXO details https://zpl.io/2pkmZAy
![image](https://user-images.githubusercontent.com/47353570/95243586-85631580-0819-11eb-8d3a-4bbba5225d80.png)

3) Please remove comments from UTXO screen https://zpl.io/VOArlWP and leave it only on UTXO details screen https://zpl.io/2pkmZAy

**Comment by KatsiarynaV** [comment]
Change the color of word 'available' to green as in design
![0001](https://user-images.githubusercontent.com/68267190/95453356-5cef2e80-0973-11eb-94fc-569d7424bd25.jpg)

**Comment by kazaryan-t** [comment]
The word "unavailable" should be displayed in grey color.

![02](https://user-images.githubusercontent.com/68247034/95581406-a8700e00-0a41-11eb-8949-da9168387b4f.jpg)
![01](https://user-images.githubusercontent.com/68247034/95581412-ac039500-0a41-11eb-9961-8d5d966cea19.png)

**Comment by KatsiarynaV** [comment]
Checked
