### ISSUE TITLE
Notifications about offline tx's 

### ISSUE THREAD

**Issue by dariatarakanova** [BeamMW/android-wallet#488]
Design: https://zpl.io/bPjMjnl

![image](https://user-images.githubusercontent.com/47353570/95306732-723f5c80-0890-11eb-8aa7-85b4ea06feb9.png)

**Comment by kazaryan-t** [comment]
Incorrect information in Notifications for transactions sent to offline.

Actual: You sent 10 BEAM to _sender's address_. (example)
Expected: You sent 10 BEAM to _receiver's address_. (example)

![Screenshot_20201012-121738_Beam Wallet Masternet](https://user-images.githubusercontent.com/68247034/95731580-608ef800-0c88-11eb-8906-98b2b930bd41.jpg)
![Screenshot_20201012-121745_Beam Wallet Masternet](https://user-images.githubusercontent.com/68247034/95731586-61278e80-0c88-11eb-86b7-1b9a75cd116e.jpg)

**Comment by kazaryan-t** [comment]
Not fixed.

![20201013_115522](https://user-images.githubusercontent.com/68247034/95839208-6ac5fa80-0d4b-11eb-809f-a491706c90fd.jpg)
![20201013_115540](https://user-images.githubusercontent.com/68247034/95839213-6bf72780-0d4b-11eb-9ae5-924eacef63ab.jpg)

**Comment by kazaryan-t** [comment]
Checked.
