### ISSUE TITLE
Shielded coins aren't displayed in the balance

### ISSUE THREAD

**Issue by KatsiarynaV** [BeamMW/android-wallet#490]
Shielded coins aren't displayed in the balance
![04](https://user-images.githubusercontent.com/68267190/95730529-0a6d8500-0c87-11eb-88c0-f0b6754a8029.jpg)

**Comment by DenisDemyanko** [comment]
Please provide your database and password?

**Comment by KatsiarynaV** [comment]
[logs.zip](https://github.com/BeamMW/android-wallet/files/5370381/logs.zip)
Password: 1

**Comment by KatsiarynaV** [comment]
Remove tab "shielded" . Only "available" balance should be as in UI wallet
![10](https://user-images.githubusercontent.com/68267190/95961759-28192680-0e0e-11eb-8c29-fcdb6aab9f9c.jpg)
![11](https://user-images.githubusercontent.com/68267190/95962351-efc61800-0e0e-11eb-8d18-38406cd2f4c7.jpg)

**Comment by KatsiarynaV** [comment]
Remove word 'shielded' from balance
![12](https://user-images.githubusercontent.com/68267190/96118454-32155500-0ef4-11eb-85fe-a53c0762575e.jpg)
