### ISSUE TITLE
Send - Max privacy UI

### ISSUE THREAD

**Issue by dariatarakanova** [BeamMW/android-wallet#498]
Screens - https://app.zeplin.io/project/5ba9be48f029d520c456f395/dashboard?seid=5f8e9bc85fd2c601c6c90a31

1) Offline address - https://zpl.io/aBLkoRQ
2) Max privacy address - https://zpl.io/VDLkvKq
3) Permanent - https://zpl.io/bPezO9y
4) One-time use - https://zpl.io/VDLkvWJ
5) Send to contact. First address type, below contact https://zpl.io/aBLkoRQ
6) Rename "Transaction comment" to "Comment"
7) Rename "show address" to "more details"
![image](https://user-images.githubusercontent.com/47353570/96560147-935b7080-12c6-11eb-94d3-87a8eca9f4d0.png)

8) Please add descriptions for all empty fields (address (updated text), amount, comment) https://zpl.io/aReBn9E Please display it from the beginning, not only after tap on field

**Comment by kazaryan-t** [comment]
1. Please, rename **Outgoing addresses (auto-generated)** to **Outgoing address (auto-generated)**.
2. Hide the middle part of outgoing address as in the design https://zpl.io/bPezO9y.

![Screenshot_20201215-102044_Beam Wallet Masternet](https://user-images.githubusercontent.com/68247034/102184682-e580d280-3ec0-11eb-998b-65365cfaf07e.jpg)

3. Change the text on empty fields as in the design. https://zpl.io/aReBn9E

![2](https://user-images.githubusercontent.com/68247034/102191465-80ca7580-3eca-11eb-97cf-964fb4941682.png)
![3](https://user-images.githubusercontent.com/68247034/102191553-a0619e00-3eca-11eb-80d2-e237e31d031c.jpg)

**Comment by kazaryan-t** [comment]
Some letters of description for the empty field "Transaction info" are hidden.
![Screenshot_20201216-142133_Beam Wallet Masternet](https://user-images.githubusercontent.com/68247034/102343355-7b912780-3fab-11eb-87a8-3fad9e4369e5.jpg)

**Comment by kazaryan-t** [comment]
Impossible to fix. 
Checked.
