### ISSUE TITLE
Receive screen - Max privacy UI

### ISSUE THREAD

**Issue by dariatarakanova** [BeamMW/android-wallet#499]
Screens - https://app.zeplin.io/project/5ba9be48f029d520c456f395/dashboard?seid=5f8e9bbc59576057124516fa

1) Regular / one-time use - 3 addresses https://zpl.io/a3LkZQd
2) Regular / permanent - 3 addresses (only online for wallet will be changed) https://zpl.io/bPezOyM
3) Max privacy address - https://zpl.io/VOeRM31
4) Share address (after tap o button) - https://zpl.io/2jDLEKr
5) Address details (after tap on "more details")
https://zpl.io/VQkALLW , https://zpl.io/aMek777 , https://zpl.io/a3LkZ6l , https://zpl.io/V076lN9
6) Please add description for all empty fields (name/comment/amount) https://zpl.io/agjMLxD
7) Name and tag for address will be applied to used addresses after successful transaction.

**Comment by KatsiarynaV** [comment]
1. Change text for max privacy transaction as in UI wallet: "Max Privacy transaction can last at most 72 hours"
![text max privacy android](https://user-images.githubusercontent.com/68267190/101755848-6bc69e80-3ae6-11eb-826c-34ab30126980.jpg)
![text max privacy desktop](https://user-images.githubusercontent.com/68267190/101755999-97e21f80-3ae6-11eb-9369-f8445e540f8b.jpg)

2. Change the field name from "AMOUNT" to "REQUESTED AMOUNT"
![01](https://user-images.githubusercontent.com/68267190/101756367-feffd400-3ae6-11eb-96ae-8319e7f7c3c5.jpg)

**Comment by KatsiarynaV** [comment]
1. Change the text when wallet is connected to a random remote node to "Connect to integrated or own node to enable **receiving max privacy and offline** transactions"
![02](https://user-images.githubusercontent.com/68267190/102177781-460a1280-3eb5-11eb-90c7-5c9887229d32.jpg)
![03](https://user-images.githubusercontent.com/68267190/102177835-5f12c380-3eb5-11eb-8e29-21ddb06e669e.jpg)

**Comment by KatsiarynaV** [comment]
Checked
