### ISSUE TITLE
Display Max privacy coins in AVAILABLE block

### ISSUE THREAD

**Issue by dariatarakanova** [BeamMW/android-wallet#500]
1) Create tab "Max privacy" https://zpl.io/V1lmB4X
2) Display there max privacy coins https://zpl.io/bJenNv9
![image](https://user-images.githubusercontent.com/47353570/96576496-f0612180-12da-11eb-9cf2-497b19f70962.png)

**Comment by Denis-Asipenko** [comment]
@dariatarakanova need to think through the design so that the user can track the time when the coin becomes available as it is implemented in the desktop wallet
![image](https://user-images.githubusercontent.com/45556620/101377970-8e2ca200-38c3-11eb-8156-d0f2d9bd21f5.png)

**Comment by dariatarakanova** [comment]
1) Please add tab "Max Privacy" to Available block https://zpl.io/bJenNv9
![image](https://user-images.githubusercontent.com/47353570/101905811-b288c700-3bc0-11eb-9177-1dfde2f249b5.png)

2) Please add button "more details" https://zpl.io/bJenNv9
![image](https://user-images.githubusercontent.com/47353570/101905825-b9173e80-3bc0-11eb-909b-0c2d6e5360da.png)

3) More details screen https://zpl.io/bzKWW43
![image](https://user-images.githubusercontent.com/47353570/101905948-dea44800-3bc0-11eb-91f8-807c75946310.png)

3.1) Create table with Amount and Latest unlocked time 
![image](https://user-images.githubusercontent.com/47353570/101905975-e7951980-3bc0-11eb-967d-7265e791c8fe.png)

3.2) Add sort icon 
![image](https://user-images.githubusercontent.com/47353570/101906003-f4197200-3bc0-11eb-8a31-0417760d1b34.png)

3.3) Sort view. **Default sorting is Time: small to large** https://zpl.io/Vkg55y5
![image](https://user-images.githubusercontent.com/47353570/101906020-fd0a4380-3bc0-11eb-8e48-8ca55df308e6.png)

**Comment by kazaryan-t** [comment]
Checked.
