### ISSUE TITLE
Public offline address UI

### ISSUE THREAD

**Issue by dariatarakanova** [BeamMW/android-wallet#501]
1) Add "show public offline address" to settings (block utilities) https://zpl.io/bo6Akov
2) Show public offline address screen https://zpl.io/2GL48oW
3) Transaction details https://zpl.io/anxP53r
Transaction status - offline, but please specify address type (Public offline address) inside details.

**Comment by KatsiarynaV** [comment]
Contact is saved without address for public offline transactions 
![02](https://user-images.githubusercontent.com/68267190/101874030-257e4780-3b99-11eb-8642-f7842310df30.jpg)
![01](https://user-images.githubusercontent.com/68267190/101872593-92441280-3b96-11eb-9852-2f60be0ae48b.jpg)

**Comment by KatsiarynaV** [comment]
Checked
