### ISSUE TITLE
Export transaction history(CSV) - need to add columns for second currency, max. privacy and offline transactions.

### ISSUE THREAD

**Issue by Denis-Asipenko** [BeamMW/android-wallet#503]
We need to adjust the CSV file to take into account the new features of the wallet

**Comment by kazaryan-t** [comment]
1. Please fix the information in Date|Time column for _received max privacy_ transactions in transaction history (CSV file). 

![4](https://user-images.githubusercontent.com/68247034/102264780-26abcd80-3f27-11eb-9c12-1791962cd066.png)
[logs.zip](https://github.com/BeamMW/android-wallet/files/5698191/logs.zip)

2. Add columns in transaction history (CSV):

-  Amount, USD
- Amount, BTC
- Comment
- Sending identity
- Receiving identity
- Token
- Payment proof

![5](https://user-images.githubusercontent.com/68247034/102267573-2ca3ad80-3f2b-11eb-91fb-3deef9218327.png)

**Comment by kazaryan-t** [comment]
Checked.
