### ISSUE TITLE
Transaction details - shielded coins don't displayed in transaction utxo list

### ISSUE THREAD

**Issue by Denis-Asipenko** [BeamMW/android-wallet#504]

**Comment by KatsiarynaV** [comment]
Transaction utxo list isn't displayed for received max privacy, offline and public offline transactions
![01](https://user-images.githubusercontent.com/68267190/101872290-1053e980-3b96-11eb-932e-f0b43cfd4fd5.jpg)
![02](https://user-images.githubusercontent.com/68267190/101872309-18138e00-3b96-11eb-918b-7308ec2327c3.jpg)
![03](https://user-images.githubusercontent.com/68267190/101872312-1a75e800-3b96-11eb-8672-1b559c4f8d58.jpg)
![04](https://user-images.githubusercontent.com/68267190/101872412-44c7a580-3b96-11eb-9b1f-20fa23ed3b20.jpg)

**Comment by KatsiarynaV** [comment]
"Shielded pool" should be displayed in the field 'contact' for max privacy and offline transactions
![14](https://user-images.githubusercontent.com/68267190/103198211-cfc7d000-48f8-11eb-88c3-b69e5a6ff9ef.jpg)

**Comment by KatsiarynaV** [comment]
Checked
