### ISSUE TITLE
Send - confirmation screen (redesign)

### ISSUE THREAD

**Issue by dariatarakanova** [BeamMW/android-wallet#505]
Design with changes https://zpl.io/bz415W7 , https://zpl.io/anwYlKv

Information is placed more compact now

**Comment by KatsiarynaV** [comment]
![01](https://user-images.githubusercontent.com/68267190/101875606-f2898300-3b9b-11eb-9fc3-f9ec74f479e4.jpg)

**Comment by KatsiarynaV** [comment]
checked
