### ISSUE TITLE
Changes to the Receive screen

### ISSUE THREAD

**Issue by Denis-Asipenko** [BeamMW/android-wallet#507]
We need to come up with something with this switch. because it is essentially only for one address  "Online address (for wallet)". the other two should always be permanent by default. After the design is ready, please assigned this task to @DenisDemyanko to implement changes in the wallet.  
Current:
![image](https://user-images.githubusercontent.com/45556620/101748497-b09a0780-3add-11eb-9405-2db07fbb696e.png)

An example solution that is implemented on a desktop wallet: 
![image](https://user-images.githubusercontent.com/45556620/101739507-a9242f80-3ad8-11eb-8505-7bc43887ed07.png)

**Comment by dariatarakanova** [comment]
https://zpl.io/bPezOyM

Please make section for Address type, each address itself (online for wallet, online for exchanges, offline) and Edit address.

Remove address expiration title and place switcher to Online address (for wallet)
![image](https://user-images.githubusercontent.com/47353570/102086756-42c54700-3e21-11eb-96c1-04abd19052bd.png)

**Comment by KatsiarynaV** [comment]
1. Offline address shoud only be "permanent"
![12](https://user-images.githubusercontent.com/68267190/102219448-8d61c480-3ef0-11eb-99bf-39e6062009c2.jpg)
2. Online address for exchange or mining pool shoud only be "permanent"
![13](https://user-images.githubusercontent.com/68267190/102220147-78396580-3ef1-11eb-9561-25176ea2a343.jpg)

**Comment by KatsiarynaV** [comment]
1. Offline address shoudn't change when switching from one-time to permanent
![gif01](https://user-images.githubusercontent.com/68267190/102880224-0a92b980-445c-11eb-9fcc-e3104dc754e4.gif)

2. If it's possible please align buttons
![15](https://user-images.githubusercontent.com/68267190/102880573-99073b00-445c-11eb-8784-ae9704afeaca.jpg)

**Comment by KatsiarynaV** [comment]
![gif02](https://user-images.githubusercontent.com/68267190/103076480-de537600-45de-11eb-90e7-345b920cac86.gif)

**Comment by KatsiarynaV** [comment]
Checked
