### ISSUE TITLE
Add to Settings "Max privacy lock time limit"

### ISSUE THREAD

**Issue by dariatarakanova** [BeamMW/android-wallet#508]
1) Please add "Max privacy lock time limit" to Privacy settings  https://zpl.io/2ExnZKM

![image](https://user-images.githubusercontent.com/47353570/101894899-7e58da80-3baf-11eb-9bae-fb7cdde5b4c9.png)

2) "Max privacy lock time limit" page https://zpl.io/bLZOjBm

![image](https://user-images.githubusercontent.com/47353570/101894943-8dd82380-3baf-11eb-93ea-1193273cc03a.png)

**Comment by KatsiarynaV** [comment]
Checked
