### ISSUE TITLE
Receive Max privacy. Comment "can take up to XX days"

### ISSUE THREAD

**Issue by dariatarakanova** [BeamMW/android-wallet#510]
Please add comment to Max privacy tx: "Max Privacy transaction can last at most 72 hours." - https://zpl.io/VOeRM31

![image](https://user-images.githubusercontent.com/47353570/101893958-22418680-3bae-11eb-8e99-30149dade67b.png)

**Comment by KatsiarynaV** [comment]
Please, make the text exactly as in the design

**Comment by kazaryan-t** [comment]
1. Please, divide both texts for Max privacy transaction in two lines as in the design putting enter after words _'can last'_ and _'transaction fee'_.

![Receive Max privacy  Comment _can take up to XX da](https://user-images.githubusercontent.com/68247034/102338192-957b3c00-3fa4-11eb-9362-8b0463adb900.png)

2. Change the letter **P** in the comment **"Max privacy transaction can last at most 72 hours."** to lower case.

![Screenshot_20201216-132309_Beam Wallet Masternet](https://user-images.githubusercontent.com/68247034/102338074-65cc3400-3fa4-11eb-84e2-d9c0281eb78a.jpg)

**Comment by kazaryan-t** [comment]
Checked.
