### ISSUE TITLE
Display app version as "v 5.2.00" (the same as on desktop)

### ISSUE THREAD

**Issue by dariatarakanova** [BeamMW/android-wallet#512]
Current implementation:
![image](https://user-images.githubusercontent.com/47353570/102077998-d5121e80-3e12-11eb-917b-d480761e4d64.png)

Login screen (updated) https://zpl.io/aXkM95M
![image](https://user-images.githubusercontent.com/47353570/102139166-213a7e80-3e66-11eb-9cc1-e88c84481c26.png)

Settings screen (updated) https://zpl.io/bzjKoJ8
![image](https://user-images.githubusercontent.com/47353570/102139230-3b745c80-3e66-11eb-8954-ebb16df74fc2.png)

**Comment by KatsiarynaV** [comment]
Checked
