### ISSUE TITLE
Contacts: tags aren't saved

### ISSUE THREAD

**Issue by KatsiarynaV** [BeamMW/android-wallet#517]
When sending transaction and saving the contact tags aren't saved
![05](https://user-images.githubusercontent.com/68267190/102582923-ac40a080-4114-11eb-8f54-95ae045a9e7e.jpg)

**Comment by kazaryan-t** [comment]
There are some problems with deleting contact's tag. 
Cannot delete the last tag and some of them appear after deleting.

https://user-images.githubusercontent.com/68247034/102768223-deab0180-4391-11eb-95b1-bdfa5e1fbac0.mp4

https://user-images.githubusercontent.com/68247034/102768764-b8399600-4392-11eb-85e5-1c63045b7961.mp4

**Comment by kazaryan-t** [comment]
Checked.
