### ISSUE TITLE
When sending transaction to a contact, this contact is removed from the address book

### ISSUE THREAD

**Issue by KatsiarynaV** [BeamMW/android-wallet#518]
**Describe the bug**
When the user send transaction to a contact, this contact is removed from the address book. When the user reopen the wallet, the contact is displayed in the address book again

**To Reproduce**
1. Go to the address book - contacts
2. Send transaction to a contact

**Actual behaviour**
The wallet remove the contact from address book. When the user reopen the wallet, the contact is displayed in the address book again

**Expected behaviour**
The contact remains in the address book 

![01](https://user-images.githubusercontent.com/68267190/102594273-08acbb80-4127-11eb-859a-a3a13241ac63.jpg)
![02](https://user-images.githubusercontent.com/68267190/102594278-0a767f00-4127-11eb-9f94-59227cbca649.jpg)
![03](https://user-images.githubusercontent.com/68267190/102594286-0cd8d900-4127-11eb-8f15-2740d705f2cf.jpg)
![04](https://user-images.githubusercontent.com/68267190/102594298-0fd3c980-4127-11eb-9aee-c66cbaaac503.jpg)
![05](https://user-images.githubusercontent.com/68267190/102594306-12362380-4127-11eb-8720-eb9e64550cfd.jpg)

**Comment by kazaryan-t** [comment]
Checked.
