### ISSUE TITLE
Transaction details: transaction fee isn't displayed

### ISSUE THREAD

**Issue by KatsiarynaV** [BeamMW/android-wallet#519]
Ttransaction fee isn't displayed on the Transaction details screen (for sent transactions)
![07](https://user-images.githubusercontent.com/68267190/102757179-fbd7d400-4381-11eb-9e5c-25bfd521d36f.jpg)

**Comment by kazaryan-t** [comment]
Checked.

**Comment by KatsiarynaV** [comment]
Transaction details screen: transaction fee is displayed incorrect for transactions with shielded coins
![13](https://user-images.githubusercontent.com/68267190/103195638-ba03dc00-48f3-11eb-8d6b-fa11b1f055c0.jpg)

**Comment by KatsiarynaV** [comment]
checked
