### ISSUE TITLE
During wallet creation, after the wallet moves to background, it backs to foreground to previous screen 

### ISSUE THREAD

**Issue by kaminskyelina** [BeamMW/android-wallet#52]
**Device:**
Oukitel
Model: K10
OS: Android 7.1.1

**Scenario:**
Install Beam Wallet
Tap on Create New Wallet
Tap on Generate Recovery Phrase 
Tap on Copy 
Open other application to Paste copied Recovery Phrase ->Beam wallet moved to the background
Back to Beam Wallet->Beam wallet in frontend

**Expected result:**
Beam wallet on the same screen

**Actual result:**
Beam wallet back to Create Wallet screen - which means the user should generate new phrase

**Comment by Denis-Asipenko** [comment]
checked
