### ISSUE TITLE
Rename "Transaction type" to "Address type" on receive screen

### ISSUE THREAD

**Issue by kazaryan-t** [BeamMW/android-wallet#524]
Please rename "Transaction type" to "Address type" on the receive screen as in the iOS wallet and desktop wallet.

Current implementation:
![Screenshot_20210112-112425_Beam Wallet Testnet](https://user-images.githubusercontent.com/68247034/104290499-756b6980-54cb-11eb-94f1-080ff6fe95a2.jpg)
![Screenshot_20210112-110553_Beam Wallet Testnet](https://user-images.githubusercontent.com/68247034/104290509-79978700-54cb-11eb-933a-780a7de3f136.jpg)

Desktop:
![Beam Wallet Masternet 2021-01-12 11 47 02](https://user-images.githubusercontent.com/68247034/104290748-c4b19a00-54cb-11eb-9348-68cba83e5614.png)

iOS:
![Кино и ТВ 2021-01-12 11 49 14](https://user-images.githubusercontent.com/68247034/104291022-15c18e00-54cc-11eb-9ee0-849161308143.png)

**Comment by KatsiarynaV** [comment]
checked
