### ISSUE TITLE
Fix text on "show QR code" for max privacy (receive)

### ISSUE THREAD

**Issue by dariatarakanova** [BeamMW/android-wallet#525]
Comment about transaction should be the same on receive screen and on show qr code dialog.
![image](https://user-images.githubusercontent.com/47353570/106119017-62a89400-615d-11eb-8c85-f1009f90bc80.png)

Correct text https://zpl.io/bANE4wn
![image](https://user-images.githubusercontent.com/47353570/106119540-fe3a0480-615d-11eb-960f-2cac0694468e.png)

**Comment by dariatarakanova** [comment]
Please change the text for Max Privacy tx to "Max Privacy transaction can last at most 72 hours."
https://zpl.io/bANE4wn

![image](https://user-images.githubusercontent.com/47353570/119343384-097de680-bc9f-11eb-94ea-3e07284d3118.png)

**Comment by Denis-Asipenko** [comment]
checked
