### ISSUE TITLE
Use calcShieldedCoinSelectionInfo instead of calcChange

### ISSUE THREAD

**Issue by anatolse** [BeamMW/android-wallet#526]
calcChange was deprecated. Newer code  should use calcShieldedCoinSelectionInfo.
The sample of the usage you can find in https://github.com/BeamMW/beam-ui/blob/master/ui/viewmodel/send_view.cpp
void SendViewModel::RefreshCsiAsync()

**Comment by Denis-Asipenko** [comment]
checked
