### ISSUE TITLE
Mobile node flow

### ISSUE THREAD

**Issue by dariatarakanova** [BeamMW/android-wallet#529]
We need to differentiate 3 nodes: random, mobile and own

1) Random node https://zpl.io/2Gjz6jj
1.1) Connection to Random node is fast and no need any loading screen. Just click "connect" button.
2.2) When wallet connect to Random node - status is "circle" with text "online"
![image](https://user-images.githubusercontent.com/47353570/115199803-3e28dc00-a0fc-11eb-9529-2231a29076fd.png)

2) Mobile node
2.1) Connection will take some time and after tap on "connection" button show loading screen https://zpl.io/ag3GX3R
![image](https://user-images.githubusercontent.com/47353570/115199456-e5594380-a0fb-11eb-96fc-01118c52b268.png)

3.2) After loading screen open Wallet screen with toaster https://zpl.io/VQNWpNP
![image](https://user-images.githubusercontent.com/47353570/115199530-fa35d700-a0fb-11eb-8522-fbad8dc6f11a.png)

3.3) When wallet connect to Mobile node - status is "circle" with text "online: mobile node"

Own node
4.1) Connection to Own node is advanced feature and requests ip:port that appears only after choosing this node https://zpl.io/2j3lr3q
![image](https://user-images.githubusercontent.com/47353570/115199597-0d48a700-a0fc-11eb-9ae3-9c0f1cf36414.png)

4.2) When wallet connect to Own node - status is "lock" with text "online" https://zpl.io/aX7WnQx
![image](https://user-images.githubusercontent.com/47353570/115202378-02434600-a0ff-11eb-818f-79f6484b60a8.png)

**Comment by Denis-Asipenko** [comment]
align point 4.2 
Also, when creating a wallet, the lock indicator icon indicates a connection to its own node, but when creating a wallet, it connects to a random node.
![image](https://user-images.githubusercontent.com/45556620/119308183-6a90c480-bc75-11eb-8dfe-1852a13da5ee.png)

**Comment by dariatarakanova** [comment]
Own node connected https://zpl.io/2j3mpW4 
1) make another nodes inactive
2) make IP address non-editable
3) button should be "disconnect"
4) only after tap on button "disconnect" used can change IP and connect to another node https://zpl.io/ag3KgdR

![image](https://user-images.githubusercontent.com/47353570/119565674-ea707900-bdb2-11eb-8b7e-82f4d219363d.png)

**Comment by Denis-Asipenko** [comment]
checked
