### ISSUE TITLE
Send screen - 6.0

### ISSUE THREAD

**Issue by dariatarakanova** [BeamMW/android-wallet#531]
Designs - https://zpl.io/bz38eX4

1) We will remove "advanced", "tags", "edit address" and make mobile features equal to desktop.

2) Remove "Fee" block.

3) Make each section as block with non-transparent bg https://zpl.io/VOv087k
![image](https://user-images.githubusercontent.com/47353570/114774955-68377280-9d79-11eb-9a88-1a7428726501.png)

4) Change "more details" to "address details" and "add all" to "add max" https://zpl.io/bL940ED
![image](https://user-images.githubusercontent.com/47353570/114775095-9452f380-9d79-11eb-8410-39e2baf0ff8a.png)

5) Regular(offline) address https://zpl.io/bL940ED
![image](https://user-images.githubusercontent.com/47353570/114775150-a765c380-9d79-11eb-89d8-601808a7235d.png)

6) Max Privacy address. There is no "Transaction type" block  https://zpl.io/bl3lExD
![image](https://user-images.githubusercontent.com/47353570/114775208-b6e50c80-9d79-11eb-8d0b-7309750c1544.png)

7) Address details https://zpl.io/aX7Y8JP
![image](https://user-images.githubusercontent.com/47353570/114776077-bb5df500-9d7a-11eb-9f97-5520b6e1cfc3.png)

8) Confirmation screen https://zpl.io/bJDE4x9
![image](https://user-images.githubusercontent.com/47353570/114776031-ac774280-9d7a-11eb-9fca-fb8369e8be96.png)

9) Please make buttons "Send", "Copy and close"and "Next" the same wight.
![image](https://user-images.githubusercontent.com/47353570/114776049-b436e700-9d7a-11eb-8a9b-b9b03bf7a63b.png)

10) Make main title in white color and sub-titles in grey color
![image](https://user-images.githubusercontent.com/47353570/114775539-1511ef80-9d7a-11eb-9a54-0085581dae2a.png)

**Comment by kazaryan-t** [comment]
1. Please, add address type for saved contacts.

![6 0_send-contact-list - 03 Android Wallet - Zeplin](https://user-images.githubusercontent.com/68247034/119345602-c6714280-bca1-11eb-9782-704752b32ff8.png) 

2. Change the text for Max Privacy transactions to "Max Privacy transaction can last at most 72 hours."
3. Place text about min transaction fee as in the design.

![Screenshot_20210524-145816_Beam Wallet Masternet j](https://user-images.githubusercontent.com/68247034/119346178-8eb6ca80-bca2-11eb-858c-c022de8d306c.png)

![6 0_send-max-privacy - 03 Android Wallet - Zeplin ](https://user-images.githubusercontent.com/68247034/119348140-21586900-bca5-11eb-8fab-2e73d9d47f42.png)

4. When the sender pastes Max Privacy address, the message for regular transactions appears in the screen.

![Screenshot_20210524-145921_Beam Wallet Masternet j](https://user-images.githubusercontent.com/68247034/119346488-f240f800-bca2-11eb-83bb-5e31124041bc.png)
 
The text should be:

_Max Privacy transaction can last at most 72 hours.
Min transaction fee to send Max privacy coins is 0.01 BEAM._

5. On the confirmation screen, when user select the address from contacts, the contact's name should appear first and under the contact's name goes contact's address (as in the design).
6. Change the color of the fee amount (in the design the fee amount color is white) 

![6 0_confirmation-offline - 03 Android Wallet - Zep](https://user-images.githubusercontent.com/68247034/119347376-21a43480-bca4-11eb-8925-acc6f6dea3cd.png)
![Фотографии 2021-05-24 15 22 06](https://user-images.githubusercontent.com/68247034/119347417-2cf76000-bca4-11eb-9c0b-b7d4e49ce4e0.png)

**Comment by kazaryan-t** [comment]
Please, change the color of the contact's name and his address on the Confirmation screen (in the design the contact's name color is white and the address is grey).

Design - https://zpl.io/bJDE4x9
![Screenshot_20210525-164439_Beam Wallet Masternet](https://user-images.githubusercontent.com/68247034/119510105-ed02ac80-bd79-11eb-8054-d1a948c796ac.jpg)

**Comment by kazaryan-t** [comment]
Checked.

**Comment by KatsiarynaV** [comment]
Remove text for max privacy and offline/public offline transactions. There aren't any text for this transaction types in the UI wallet.
![04](https://user-images.githubusercontent.com/68267190/119941748-a8555c00-bf99-11eb-9aab-1e53a326e4a4.jpg)

**Comment by dariatarakanova** [comment]
1) Correct text for offline transaction is "Min transaction fee to send offline transaction is 0.01 BEAM." https://zpl.io/aME8AXm

2) Change "Regular address" https://zpl.io/a88zgDE to "Regular online-only address" and "Regular offline-only address" https://zpl.io/aME8AXm
![image](https://user-images.githubusercontent.com/47353570/120222937-71a56d00-c249-11eb-8f72-775693b10d49.png)

**Comment by KatsiarynaV** [comment]
Remove 'null' under the amount field when exchange rate wasn't received
![05](https://user-images.githubusercontent.com/68267190/120274135-18285700-c2b8-11eb-920d-568a9f1a49df.jpg)

**Comment by KatsiarynaV** [comment]
1. Change text for public offline transactions to "Min transaction fee to send offline transaction is 0.01 BEAM."
![06](https://user-images.githubusercontent.com/68267190/120328812-e03f0500-c2f3-11eb-8784-8e53e1360aec.jpg)

2. When switcher is enabled to offline transaction type  the adress type should be "Regular offline-only address"
![07](https://user-images.githubusercontent.com/68267190/120328988-11b7d080-c2f4-11eb-959e-d07f1361f5f0.jpg)
![08](https://user-images.githubusercontent.com/68267190/120329341-6b1fff80-c2f4-11eb-91d2-72e3c0844cbd.jpg)

**Comment by KatsiarynaV** [comment]
Checekd
