### ISSUE TITLE
Receive screen - 6.0

### ISSUE THREAD

**Issue by dariatarakanova** [BeamMW/android-wallet#532]
Designs https://zpl.io/V1xynEJ

1) Make all title in white color https://zpl.io/bARmyNq
![image](https://user-images.githubusercontent.com/47353570/114780735-789f1b80-9d80-11eb-981d-ee786351cacc.png)

2) Rename "Address type" to "Transaction type" https://zpl.io/bARmyNq
![image](https://user-images.githubusercontent.com/47353570/114781276-24e10200-9d81-11eb-93ae-604de042ece9.png)

3) Change "more details" to "address details" https://zpl.io/bARmyNq
![image](https://user-images.githubusercontent.com/47353570/114781326-31655a80-9d81-11eb-9b24-62b4b041e8ad.png)

4) Regular TX https://zpl.io/bARmyNq
![image](https://user-images.githubusercontent.com/47353570/114781370-3fb37680-9d81-11eb-887b-60a4e50a6f95.png)

5) Max privacy TX https://zpl.io/bz38oPM
![image](https://user-images.githubusercontent.com/47353570/114781426-4e9a2900-9d81-11eb-96ad-b8f98c4d85f1.png)

6) Address details. Add "copy" icon and rename button to "copy and close" https://zpl.io/ag380RN
![image](https://user-images.githubusercontent.com/47353570/114781463-5e197200-9d81-11eb-8cc1-90b6d48ac201.png)

7) QR for regular tx https://zpl.io/VQN0D69
QR for max privacy https://zpl.io/2GjEl89
![image](https://user-images.githubusercontent.com/47353570/114781647-9d47c300-9d81-11eb-8ea5-e564410a92ff.png)

8) Make buttons "copy and close" , "share address" and "share QR" the same wight

**Comment by KatsiarynaV** [comment]
1. For "TRANSACTION TYPE", "ADDRESS", "BEAM" make letter spacing as in design
2. Make the word "optional" in lowercase
3. Make the text "Comments are local and won't be shared" in italics
![0001](https://user-images.githubusercontent.com/68267190/119311589-eee54680-bc79-11eb-8c76-e51d0777ebd5.jpg)

4. Change text for max privacy transactions to "Max privacy transaction can last at most 72 hours."
![0005](https://user-images.githubusercontent.com/68267190/119339377-bfdecd00-bc99-11eb-80e2-46fe8c54a951.jpg)

5. Place text "Min transaction fee.." as in design
![0002](https://user-images.githubusercontent.com/68267190/119313241-ff96bc00-bc7b-11eb-8049-a0ed4609f068.jpg)
![0003](https://user-images.githubusercontent.com/68267190/119314126-070a9500-bc7d-11eb-963c-cf2fb9ed89b9.jpg)

6. For regular transactions add the text "Sender will be given a choice between regular and offline payment." as in UI wallet
![0004](https://user-images.githubusercontent.com/68267190/119319175-c57ce880-bc82-11eb-9e1e-156166c91822.jpg)

**Comment by KatsiarynaV** [comment]
Please, make indent between texts as in the design
![17](https://user-images.githubusercontent.com/68267190/119457064-f07b4100-bd43-11eb-876d-c54d26e7f7b7.jpg)

**Comment by KatsiarynaV** [comment]
Place triangles as in the design
![24](https://user-images.githubusercontent.com/68267190/119509153-0e16cd80-bd79-11eb-97cb-51052dc03d47.jpg)

**Comment by KatsiarynaV** [comment]
Checked

**Comment by Denis-Asipenko** [comment]
If you enter a name for the address in the comment field, the name is not saved after the address is saved .
