### ISSUE TITLE
Remove "Off" from second currency in settings

### ISSUE THREAD

**Issue by dariatarakanova** [BeamMW/android-wallet#533]
Leave only 2 options: USD (Default) and BTC.
https://zpl.io/2E17kon

![image](https://user-images.githubusercontent.com/47353570/115451577-09b13f00-a226-11eb-93de-96a3bc9b074e.png)

**Comment by Denis-Asipenko** [comment]
Make according to the design:https://app.zeplin.io/project/5ba9be48f029d520c456f395/screen/5d5fd55d754cd99aeffdde83
![image](https://user-images.githubusercontent.com/45556620/119334456-d1bd7180-bc93-11eb-852f-48401fab3d0f.png)

**Comment by Denis-Asipenko** [comment]
checked
