### ISSUE TITLE
Dapps notifications

### ISSUE THREAD

**Issue by dariatarakanova** [BeamMW/android-wallet#534]
Notifications: https://zpl.io/a7AKyRE
![image](https://user-images.githubusercontent.com/47353570/118032516-72489300-b370-11eb-9485-8b02779aa202.png)

Tap on DAPPs notification - open Dapp's transactions screen with unfolded transactions details

**Comment by KatsiarynaV** [comment]
1. Change DAPP to DApp
DApp transaction completed
DApp transaction failed
DApp transaction expired

2. Make all notifications comments as in the UI wallet

Faucet:
- Deposit to Faucet 
- Withdraw from Faucet

![01](https://user-images.githubusercontent.com/68267190/137440964-ad0486bc-b124-4abc-89a3-46426d588cf0.jpg)

BeamX DAO:
One text for all transactions: "Lock/Unlock and get farmed beamX tokens"

![04](https://user-images.githubusercontent.com/68267190/137442067-24b446b7-0f4b-4d0a-b4d0-94a9d5c5f69e.jpg)
![05](https://user-images.githubusercontent.com/68267190/137442070-0f588343-c886-4a76-8ef0-b8f8c4553537.jpg)
