### ISSUE TITLE
Main screen with CA

### ISSUE THREAD

**Issue by dariatarakanova** [BeamMW/android-wallet#535]
Designs: https://zpl.io/2GjjXDd

1) Add "Asset" title and "Show all" (the same as with transactions). Display 4 recently used assets https://zpl.io/ad33lQn

2) Locked amount displays under the total amount

3) Display USD/BTC amount on the right side of asset's tile

![image](https://user-images.githubusercontent.com/47353570/118031457-395bee80-b36f-11eb-84e5-703490e75f10.png)

4) All assets list https://zpl.io/29mmX7w. Assets can be sorted https://zpl.io/aR44lnz
![image](https://user-images.githubusercontent.com/47353570/118031572-5d1f3480-b36f-11eb-9769-b9f1ed94c89a.png)

5) Asset screen: display asset amount and asset's transactions https://zpl.io/ad33ldp
![image](https://user-images.githubusercontent.com/47353570/118031626-6d371400-b36f-11eb-83ea-e1a77c5bcf9b.png)

6) "Info" icon opens detailed balance https://zpl.io/ag33lxO and asset's info https://zpl.io/bz33KQ7
![image](https://user-images.githubusercontent.com/47353570/118031887-b38c7300-b36f-11eb-8ae5-3d4675d97062.png)

**Comment by Denis-Asipenko** [comment]
Bugs:

- --

![image](https://user-images.githubusercontent.com/45556620/126492379-e821a0c9-7a4a-485b-9ec3-da30fbc4c7d2.png)

- - -

make the icons more expressive
![image](https://user-images.githubusercontent.com/45556620/126492615-2b93ca22-baea-46f0-9fe5-b91e324fd955.png)

- --

 the balance isn't displayed on the main screen when sending the beam
![image](https://user-images.githubusercontent.com/45556620/126492679-ac985610-eb97-4831-94b1-6b6a1dde242a.png)

- - -

"more details " button doesn't work

![image](https://user-images.githubusercontent.com/45556620/126493302-7e1e281d-1890-44d4-86b3-6867fe5eab08.png)

---

negative balance
![image](https://user-images.githubusercontent.com/45556620/126493992-5606c6a4-3d60-4a26-b9f4-9713d90ff68c.png)

---

**Comment by Denis-Asipenko** [comment]
1. If the asset does not have a short, long description, then do not display the fields empty. Or if some one field is empty, then it should not be displayed.(marked in red)
2. Incorrect display smallest unit name.(marked in yellow)
![image](https://user-images.githubusercontent.com/45556620/127129682-49fe5b2e-5f0c-467c-9ab8-7edd4caa68fb.png)
![image](https://user-images.githubusercontent.com/45556620/127130042-8f5c0ce7-02fd-4c32-aeee-695693abb12e.png)
3. An asset with a zero balance should not be displayed
![image](https://user-images.githubusercontent.com/45556620/127130990-d8ef5b4f-f142-4f24-b0d1-e9b1f919562b.png)

**Comment by Denis-Asipenko** [comment]
![image](https://user-images.githubusercontent.com/45556620/127133079-f90c65ba-f5c2-46a0-bd41-97ba731005c0.png)

**Comment by Denis-Asipenko** [comment]
Not fixed
> 
> "more details " button doesn't work
> 
> ![image](https://user-images.githubusercontent.com/45556620/126493302-7e1e281d-1890-44d4-86b3-6867fe5eab08.png)
>

**Comment by Denis-Asipenko** [comment]
The wallet screen displays an asset with a zero balance, and it does not display at all on the assets screen. It is worth noting that the balance of this asset is 65. Repeated scanning does not help. Perhaps this behavior is related to obtaining this asset with the help of max privacy transaction
![image](https://user-images.githubusercontent.com/45556620/127328895-8119f528-dabe-4ce5-9685-2f3e4376c3f6.png)
![image](https://user-images.githubusercontent.com/45556620/127328948-1db5464e-5801-4b4f-a1d3-2de88a9262c6.png)
![image](https://user-images.githubusercontent.com/45556620/127334498-f6866732-6c06-400d-94ee-a577741ecca2.png)

**Comment by kazaryan-t** [comment]
The locked funds shouldn't be summed to a total available amount.

![Screenshot_20210804-105747_Beam Wallet Masternet](https://user-images.githubusercontent.com/68247034/128146476-dd2ead9c-9b28-4846-8e2d-fd2cbbee097f.jpg)

![Beam Wallet Masternet 2021-08-04 11 00 25](https://user-images.githubusercontent.com/68247034/128146249-cb81fa72-a53a-45c1-93fa-1c2d72cd54f1.png)

**Comment by kazaryan-t** [comment]
Checked.
