### ISSUE TITLE
Assets colors palette

### ISSUE THREAD

**Issue by dariatarakanova** [BeamMW/android-wallet#549]
The color palette here: https://zpl.io/V4gl8Zy

For the first 20 assets, you can use these colors.
![image](https://user-images.githubusercontent.com/47353570/122907923-48659180-d35c-11eb-8f85-03746ce6c20a.png)

**Comment by kazaryan-t** [comment]
There are some color cards that do not have an asset icon.

![Screenshot_20210804-134733_Beam Wallet Masternet](https://user-images.githubusercontent.com/68247034/128169151-d648bd3e-6596-434f-bddb-2671b7048393.jpg)

**Comment by kazaryan-t** [comment]
Every card should end with the color #00458f (dark blue).

![Assets-colors - 01 Desktop Wallet - Zeplin - Googl](https://user-images.githubusercontent.com/68247034/128509210-dc43f300-36ca-4d66-a1b2-c5c5861d7337.png)

Current implementation:

![Screenshot_20210806-145834_Beam Wallet Masternet](https://user-images.githubusercontent.com/68247034/128509664-9dd0a216-f4da-4340-aea6-7bc9e9e54184.jpg)

**Comment by kazaryan-t** [comment]
Tested on masternet and several assets on testnet.
