### ISSUE TITLE
Update design of input fields

### ISSUE THREAD

**Issue by dariatarakanova** [BeamMW/android-wallet#550]
Please update the design of all input fields in the app. Please work only with fields design, no need to change any titles, comments etc.

1) All the states for input fields are here https://zpl.io/V4nxKBJ
![image](https://user-images.githubusercontent.com/47353570/134238507-3dc2849d-1b59-40ef-97d8-f5aebb5a7914.png)

2) Login/authorization https://zpl.io/brllDmr
![image](https://user-images.githubusercontent.com/47353570/134238646-6633a48c-3df8-4fcd-8542-4a138ef6ddae.png)

2.1) Error https://zpl.io/boZK6Zg
![image](https://user-images.githubusercontent.com/47353570/134238620-437b98e0-a5ce-4357-943e-b51397214c5d.png)

3) Seed phrase confirmation https://zpl.io/aREN9nz
![image](https://user-images.githubusercontent.com/47353570/134238765-e95662a8-cc5b-4695-a8d3-0a8b6806320f.png)

4) Restore wallet. Seed phrase https://zpl.io/2jYERmA
![image](https://user-images.githubusercontent.com/47353570/134238854-7ee8f492-b20b-4370-a47b-d77ae21f1bdf.png)

4.1) Restore wallet. ID:port error. https://zpl.io/VkeNz85
![image](https://user-images.githubusercontent.com/47353570/134239425-a335bf69-9c8c-4f4b-8b0c-819e67089e7e.png)

5) Send screens empty https://zpl.io/2jdx1Aq
![image](https://user-images.githubusercontent.com/47353570/134239551-bea686ef-6fd0-44a5-90ca-7c8cf14a9de6.png)

5.1) Send screens filled https://zpl.io/VK98mXW
![image](https://user-images.githubusercontent.com/47353570/134239631-257057ea-a7e4-481f-b802-e45985f4f8f7.png)

6) Receive screen empty https://zpl.io/bloEzB1
![image](https://user-images.githubusercontent.com/47353570/134240242-3842557d-653a-465e-9d95-47c7eda9dd89.png)

6.1) Receive screen. Focused https://zpl.io/a77NqDR
![image](https://user-images.githubusercontent.com/47353570/134240348-dbb31d71-be0f-477e-8d85-7c5c0ffff86b.png)

7) Address. Edit https://zpl.io/bPgORAl
![image](https://user-images.githubusercontent.com/47353570/134240489-e6238f96-d5ce-405d-992f-403ef0daadac.png)

8) Settings. Payment proof. https://zpl.io/aNzL1PD
![image](https://user-images.githubusercontent.com/47353570/134240611-146b4551-47ba-42ba-9174-a5e27a7c8521.png)

8.1) Node selection https://zpl.io/2j3lr3q and connected node https://zpl.io/2j3mpW4
![image](https://user-images.githubusercontent.com/47353570/134240712-82da37ea-d078-4228-a253-4f9af42950d2.png)

8.2) Seed verification/show owner key https://zpl.io/2j5oElQ
![image](https://user-images.githubusercontent.com/47353570/134240802-52fe4932-a1a3-4ea3-915c-681b8222485a.png)

8.3) Change pass. https://zpl.io/adpOl9L and https://zpl.io/bPPkwXM
![image](https://user-images.githubusercontent.com/47353570/134240904-32a9bb83-3c58-4267-9c39-c03241ed7263.png)

9) Popup dialog with input field https://zpl.io/2yGPW39
![image](https://user-images.githubusercontent.com/47353570/134241000-ab892556-7d51-4894-96d8-3d5afd61b510.png)

**Comment by KatsiarynaV** [comment]
Not fixed: 
Send screen: after inserting an address and taping the 'add max' button the amount field shouldn't be highlighted red

https://user-images.githubusercontent.com/68267190/139664618-11db79db-c962-4cfa-9022-d21bad54a94e.mp4

**Comment by KatsiarynaV** [comment]
Checked
