### ISSUE TITLE
Remove UTXO screen from sidemenu and add it to settings

### ISSUE THREAD

**Issue by dariatarakanova** [BeamMW/android-wallet#551]
1) Please remove UTXO from Menu

2) Add UTXO to Utilities in Settings https://zpl.io/bo6Akov
3) Add Blockchain height to Utilities and remove Remove "Last block hash" https://zpl.io/bo6Akov

![image](https://user-images.githubusercontent.com/47353570/124455043-cdf03500-dd91-11eb-8ce4-9156379b7abf.png)

4) Add asset icon to ITXO list. Available tab https://zpl.io/aRRwe0g

4) In progress tab https://zpl.io/boJAvNG

5) Spent tab https://zpl.io/a3rQLON

6) Unavailable tab https://zpl.io/V4RGLxp

![image](https://user-images.githubusercontent.com/47353570/124454931-abf6b280-dd91-11eb-8ee0-c795ebcb2873.png)

8) UTXO details. Please remove transaction history from this screen  https://zpl.io/VOLyZLQ
![image](https://user-images.githubusercontent.com/47353570/123703811-905d4a80-d86d-11eb-8ffb-0e58911306fe.png)

9) UTXO empty https://zpl.io/bAxKrx8
![image](https://user-images.githubusercontent.com/47353570/123702905-60fa0e00-d86c-11eb-9a0a-e19d8a129ff6.png)

10) Security mode is On https://zpl.io/Vxp9E9R
![image](https://user-images.githubusercontent.com/47353570/123702931-69524900-d86c-11eb-80d5-a41680878eeb.png)

**Comment by KatsiarynaV** [comment]
UTXO details: remove transaction history from this screen. UTXO stasus ("available", "spent", "outgoing", "incoming", "maturing", "unavailable") should start with lowercase letters
![03](https://user-images.githubusercontent.com/68267190/126162557-25eecff7-ac74-44b1-8491-d730c2885a1f.jpg)

**Comment by KatsiarynaV** [comment]
Add text "till block height..." for maturing status
![06](https://user-images.githubusercontent.com/68267190/126497519-7bf1df22-e7ba-4866-bbb6-d0896ffe8b32.jpg)

**Comment by KatsiarynaV** [comment]
Checked
