### ISSUE TITLE
Receive and Send screen: currency selection

### ISSUE THREAD

**Issue by KatsiarynaV** [BeamMW/android-wallet#553]
@dariatarakanova 
On the desctop when there are assets in the wallet there is currency selection on the receive screen . Please provide the design to implement this in the mobile wallet
![14](https://user-images.githubusercontent.com/68267190/125948727-96800883-d78d-43d0-882f-d9b359cce04d.jpg)
![10](https://user-images.githubusercontent.com/68267190/125948873-858c02c1-2ddc-4dbd-a8c4-b34635bf56c1.jpg)
![11](https://user-images.githubusercontent.com/68267190/125948748-9472a55f-5e67-4580-a1a6-546748a14fca.jpg)

**Comment by dariatarakanova** [comment]
Dropdown list with coins is open. Arrow should change rotation (from down to up).  https://zpl.io/aMXK1no
![image](https://user-images.githubusercontent.com/47353570/126495933-d0c7c25f-d2e5-4f54-be85-5a6c0c702624.png)

**Comment by dariatarakanova** [comment]
1) Receive screen. Dropdown is open. The arrow should change rotation (from down to up). https://zpl.io/aMXK1no
![image](https://user-images.githubusercontent.com/47353570/126496340-7635b04e-d219-4856-bad8-966e4671efe3.png)
![image](https://user-images.githubusercontent.com/47353570/126496405-4022b6f6-9037-44c7-8508-e85ebcf4f7ba.png)

2) Send screen/ The same flow. https://zpl.io/aBPyZ0K
![image](https://user-images.githubusercontent.com/47353570/126496513-61662eb2-0f45-4a49-90ac-79e5014b56e7.png)

**Comment by KatsiarynaV** [comment]
1. The dropdown should be square with rounded corners
![09](https://user-images.githubusercontent.com/68267190/126645351-40f3b2d9-001c-4fab-ad35-1d7088dc94b3.jpg)
![10](https://user-images.githubusercontent.com/68267190/126645355-d29dd99b-1ce2-445e-a7a4-063a1f3cffc5.jpg)

2. Selected coin should be highlighted
![21](https://user-images.githubusercontent.com/68267190/126655218-324e7d7c-8c08-462d-9c3d-3ee89c3b8d5e.jpg)

3. On the receive screen when user requests an amount in assets, this amount is displayed in beam on the address details screen. When user insert this address on the send screen the amount is also displayed in Beam
![16](https://user-images.githubusercontent.com/68267190/126655543-78745689-7a04-4554-aabd-366491bf90fb.jpg)

4. When clicking the receive button from the asset screen the selected currency should be displayed in requested amount field
![22](https://user-images.githubusercontent.com/68267190/126655707-3b553e9d-9842-4453-a795-686d9b210721.jpg)

**Comment by KatsiarynaV** [comment]
1. When user inserts an address with requested assets amount the currency is not restored on the send screen. It changes after viewing the address details
![gif01](https://user-images.githubusercontent.com/68267190/126943291-c1a3f3fe-57f5-439f-b89d-a86e136a7b59.gif)

2. In the available block make asset name (except long assets names) fully visible if it fits 
![29](https://user-images.githubusercontent.com/68267190/126943371-b37579f0-1fcf-4fc0-b872-c0d7eda70594.jpg)

**Comment by KatsiarynaV** [comment]
Available block: full assets name appears after inserting an amount.
![gif03](https://user-images.githubusercontent.com/68267190/127113660-3364eefb-ccf7-4234-b400-e03923f8c75d.gif)
![02](https://user-images.githubusercontent.com/68267190/127113968-3ff7dce7-0010-409d-93c0-e3388d542553.jpg)

**Comment by KatsiarynaV** [comment]
Reproduced again:  when clicking the receive button from the asset screen the selected currency should be displayed in requested amount field
![05](https://user-images.githubusercontent.com/68267190/127153134-ee48d527-869c-4ee5-8f11-45e507536126.jpg)

**Comment by KatsiarynaV** [comment]
When going back from confirmation to send screen or minimizing the wallet the currency selection shouldn't be lost
![gif01](https://user-images.githubusercontent.com/68267190/127328347-5d6cf99b-5a54-4f1c-8593-af07485b14bd.gif)

**Comment by KatsiarynaV** [comment]
Checked. 
Additional checks will be done in #562
