### ISSUE TITLE
Transaction details (updated version following desktop changes)

### ISSUE THREAD

**Issue by alexandrashelenkova** [BeamMW/android-wallet#555]
**1. Wallet transactions with payment proof. Show info into 2 separate tabs.**

1.1. General info https://zpl.io/VK944kE

- add coin icons to Amount and Fee
- add copy icon to sending address, receiving address, and transaction ID.
- text next to USD amount  "(calculated with the exchange rate at the time of transaction)" - if the rate was successfully calculated 
- text instead of USD amount  "(exchange rate was not available at the time of transaction)" - if rate was not available. And do not show USD rate https://zpl.io/bAwAAkx
- remove text-link "Open in blockchain Explorer" and leave only the green icon. Place it in one line with Kernel ID.
![image](https://user-images.githubusercontent.com/7249484/131824913-b4a64873-37c6-4abf-ae11-aa6b9b418c9a.png)
![image](https://user-images.githubusercontent.com/7249484/131824923-e924c2b1-aa5d-44bc-942c-93e93d0eb03e.png)

1.2 Details for maximum anonymity transaction https://zpl.io/beG11Bm
![image](https://user-images.githubusercontent.com/7249484/131824948-a0d277fd-21cd-4e49-99dd-af40ba684322.png)

1.3. Payment proof. Works only for sending transactions https://zpl.io/bzOyyBG
- add copy icon to sender's and receivers wallet signature and Code.
- text next to USD amount  "(calculated with the exchange rate at the time of transaction)" - if the rate was successfully calculated 
- text instead of USD amount  "(exchange rate was not available at the time of transaction)" - if rate was not available. And do not show USD rate
- remove text-link "Open in blockchain Explorer" and leave only the green icon. Place it in one line with Kernel ID.

![image](https://user-images.githubusercontent.com/7249484/131791528-37b55b90-1705-4114-8cb4-8f8db8f982a6.png)

**2. Contract transactions (without payment proof)** https://zpl.io/2EGyyOY

- add Confidential asset ID next to CA amounts and "link" icons that lead to the asset in blockchain explorer (example https://explorer.beam.mw/assets/details/2)
- add Dapp name, Application shader, Description (not Comment)
- place a comment about the exchange rate under amounts (title).
- If more than 1 coin - AMOUNTS should be in plural
- text next to USD amount  "(calculated with the exchange rate at the time of transaction)" - if the rate was successfully calculated 
- text instead of USD amount  "(exchange rate was not available at the time of transaction)" - if rate was not available. And do not show USD rate https://zpl.io/bW7BRPj

![image](https://user-images.githubusercontent.com/7249484/131824985-6589acdb-b473-488d-a882-7f8b3f2a1c18.png)
![image](https://user-images.githubusercontent.com/7249484/131824998-45ae417e-7df5-4c68-90be-1db72a5f1475.png)

**Comment by KatsiarynaV** [comment]
Tapping on link should open the asset info in blockchain explorer (example https://master-net.explorer.beam.mw/assets/details/1)

https://user-images.githubusercontent.com/68267190/139648326-03dcf9e6-dff5-468d-ba5e-bea40001f8d1.mp4

**Comment by KatsiarynaV** [comment]
Checked
