### ISSUE TITLE
Send screen- reset the amount to 0 if the user clicks the "add maximum" button on one coin and then selects another coin

### ISSUE THREAD

**Issue by Denis-Asipenko** [BeamMW/android-wallet#559]
Bug description
if the user clicks the "add maximum" button on one coin and then selects another coin then the amount doesn't reset. **This also applies to entering the amount manually,if the user entered the amount,and then changed the asset, the amount is reset to 0.**

To Reproduce

Go to the Send screen. The BEAM coin is selected by default
Tap add max button.
Select another coin.
Current behavior:
the amount doesn't reset.

Expected behavior:

the amount resets to 0.

Note:
the wallet has some assets.

https://user-images.githubusercontent.com/45556620/126651039-7aed33d4-b946-4fa5-8dc8-d23301247fe0.mp4

**Comment by Denis-Asipenko** [comment]
not fixed:

 > **This also applies to entering the amount manually,if the user entered the amount,and then changed the asset, the amount is reset to 0.**

**Comment by KatsiarynaV** [comment]
The same behavior should be on the receive screen: if the user entered an amount and then changed the asset, the amount should resets to 0
![gif02](https://user-images.githubusercontent.com/68267190/127010643-b1f2f43e-66f1-4013-9f1c-c4c35fdb0f5b.gif)

**Comment by Denis-Asipenko** [comment]
checked
