### ISSUE TITLE
Send screen: changes in address flow (with max. anon set)

### ISSUE THREAD

**Issue by dariatarakanova** [BeamMW/android-wallet#560]
Please work only on points mentioned below.

1) If receiver sends to sender regular address (maximum anonymity set OFF)

- Sender can choose the transaction type: Online or Offline  https://zpl.io/aRwxn1v
![image](https://user-images.githubusercontent.com/47353570/126786715-2c1d55ae-b7f5-414f-be6c-b7262e3d4f5b.png)

- Online (name was changed from "regular") transaction - add comment below address "Online address." And comment above "next" button - "The recipient must get online within the next 12 hours and you should get online within 2 hours afterwards."  https://zpl.io/aRwxn1v
![image](https://user-images.githubusercontent.com/47353570/126786901-7028f468-04f9-4ff7-9cb8-415b529a2dcd.png)

- Offline tx - comment "Offline address: Х transactions left." And comment above "next" button -  "Make sure the address is correct as offline transactions cannot be canceled." https://zpl.io/bzxqQNG
![image](https://user-images.githubusercontent.com/47353570/126787096-5f67be42-d189-4201-92b3-0b5e4918b615.png)

- Show warning comment "Ask receiver to come online to support more offline transactions." when 3 or fewer transactions left. https://zpl.io/bAK7gB8
![image](https://user-images.githubusercontent.com/47353570/126787148-364a60cf-33de-49f7-9aa6-3e8525465a28.png)

2) If receiver sends to sender Online address https://zpl.io/ag1QxzZ(receiver can copy SBBS address from address details on receive screen)

- No need block "Transaction Type"
- Add comment "Online address. The recipient must get online within the next 12 hours and you should get online within 2 hours afterwards."
![image](https://user-images.githubusercontent.com/47353570/126787309-b8fbb2fc-eec6-46ec-a589-e18d2b3be7e1.png)

3) If receiver sends to sender Maximum anonymity set address https://zpl.io/awdJz4M

- Add a comment about transaction's amount "Guarantees maximum anonymity set of up to 64K." And comment above "next" button - "Transaction can take up to 72 hours."
![image](https://user-images.githubusercontent.com/47353570/126787419-6a789b22-120d-4ce4-8ba1-c9d67aec0b77.png)

**Comment by KatsiarynaV** [comment]
1. Rename “TRANSACTION INFO” field to “SEND TO”
2. Rename “Regular” transaction type to “Online”
3. Add the second currency under the amount field when amount is not provided (as 0 USD)
![03](https://user-images.githubusercontent.com/68267190/127132425-8b2a49af-536b-443f-a385-2e34e33da578.jpg)
4. On the address details screen the “regular” transaction type is displayed when user chooses the offline transaction type 
![06](https://user-images.githubusercontent.com/68267190/127132475-d22ed87e-24f0-4b00-95bb-8e1df94a0c62.jpg)
5. When inserting just generated offline address (from other wallet) the text says that “0 transactions left”. Should be “1 transaction left”
![09](https://user-images.githubusercontent.com/68267190/127132573-34ec381a-b569-4c9e-82d4-7c28ad570e80.jpg)
6. Remove one dot from the text when max privacy address is pasted
![12](https://user-images.githubusercontent.com/68267190/127132623-0cf22d73-6b19-4d11-b0c6-a5c01bde3450.jpg)

**Comment by KatsiarynaV** [comment]
The offline transactions counter doesn't work. It always displays "1 transaction left" 
![11](https://user-images.githubusercontent.com/68267190/127158230-871ccda2-323a-44fa-8c37-39640d1ff2d5.jpg)

**Comment by KatsiarynaV** [comment]
Now reproduced again : when inserting just generated offline address (from other wallet) the text says that “0 transactions left”. Should be “1 transaction left”
![04](https://user-images.githubusercontent.com/68267190/127438663-0b46d0e1-71f7-4279-a3b8-154f02f28b33.jpg)

**Comment by KatsiarynaV** [comment]
Checked
