### ISSUE TITLE
Receive screen: changes in address flow (with max. anon set)

### ISSUE THREAD

**Issue by dariatarakanova** [BeamMW/android-wallet#561]
Please work only on points mentioned below. 

1) Add block "Advanced" (minimized by default) and place there Maximum anonymity switcher. https://zpl.io/VKBDOZR
![image](https://user-images.githubusercontent.com/47353570/126784018-177d4629-5740-47dc-bde1-82e854971ae2.png)

2) Switcher default position is OFF.
Off = tx will be Regular (it is combined address - online + offline addresses)
On = tx will be Maximum anonymity set

3) When Switcher is OFF. The comment was also updated. https://zpl.io/VKBDOZR
![image](https://user-images.githubusercontent.com/47353570/126784054-7ffb5b20-ee0b-4ab3-8cc1-772631172273.png)

4) When Switcher is ON - place the comment "Transaction can last at most 72 hours. Min transaction fee to send maximum anonymity coins is 0.01 BEAM." 
Add "(Maximum anonymity)" next to the ADDRESS https://zpl.io/V4Gegpp
![image](https://user-images.githubusercontent.com/47353570/126784102-199907a3-d8ee-49dc-a9ba-7b4cfebe0b63.png)

5) When Switcher is ON - place the comment "Transaction can last indefinitely. Min transaction fee to send maximum anonymity coins is 0.01 BEAM." Comment was updated a bit. https://zpl.io/VOyx6wL
"Can last indefinitely" -  depends on Lock time setting in Utilities (https://zpl.io/VxNBE5g)  
![image](https://user-images.githubusercontent.com/47353570/126784144-8c9bfd5b-0d14-4ad2-b37d-23630616cbb9.png)

6) Regular address details. Show full only address itself. Online (SBBS) address - always show begin and end of the address. https://zpl.io/aMXW6Jo
![image](https://user-images.githubusercontent.com/47353570/126784223-b0d0a957-ffce-4a0e-a971-033ed7f705cb.png)

7) Address details with max anonymity set https://zpl.io/amRdjAQ
![image](https://user-images.githubusercontent.com/47353570/126784261-88e8277f-6de4-40f2-afff-bf7632ff4227.png)

8) QR regular. Comment was updated. https://zpl.io/a8D75oX
![image](https://user-images.githubusercontent.com/47353570/126784364-4452767a-a8cd-483b-b577-73b59413f4e6.png)

9) QR max anonymity. https://zpl.io/VqQvdj7
![image](https://user-images.githubusercontent.com/47353570/126784379-da88a96f-8f40-4f93-897a-0dc601204b74.png)

**Comment by kazaryan-t** [comment]
1. Put in uppercase letter M in Maximum anonymity.

![Screenshot_20210726-172921_Beam Wallet Masternet](https://user-images.githubusercontent.com/68247034/127119305-c0ca6a25-917c-4a2c-8e9b-c8286e662a32.jpg)
![6 1_receive-max-anon - 03 Android Wallet - Zeplin ](https://user-images.githubusercontent.com/68247034/127119285-5c582e0d-6a82-45d4-822e-df1dcaee528a.png)

2. Put the text **Min transaction fee to send maximum anonymity coins is 0.01 BEAM** as in the design.

![Screenshot_20210727-110837_Beam Wallet Masternet](https://user-images.githubusercontent.com/68247034/127119752-3597592d-05f8-45ba-93a3-f3cd2db727ca.jpg)
![6 1_receive-max-anon - 03 Android Wallet - Zeplin KJHGF](https://user-images.githubusercontent.com/68247034/127119777-743f913e-b0db-4e4b-92f5-c0e606ccd8f0.png)

3. When the switcher Maximum anonymity set is ON, the address details screen should be named "Max anonymity address".

![Screenshot_20210726-173453_Beam Wallet Masternet](https://user-images.githubusercontent.com/68247034/127120918-cbcfc49c-5032-44bc-847e-2e4f2cfc8c59.jpg)

![6 1_receive-max-anon-address-details - 03 Android ](https://user-images.githubusercontent.com/68247034/127120724-314ac64a-0203-4305-b98c-5c7cb60346ca.png)


4.  №5 not implemented. If Max privacy lock time limit is set as No limit, place the comment "Transaction can last indefinitely. Min transaction fee to send maximum anonymity coins is 0.01 BEAM."

5. Put the text for the share QR popup as in the design (when switcher is off).

![Screenshot_20210727-112254_Beam Wallet Masternet](https://user-images.githubusercontent.com/68247034/127121610-21479c0d-ffec-433e-8743-00288c19bfa4.jpg)
![6 1_receive-regular qr - 03 Android Wallet - Zepli](https://user-images.githubusercontent.com/68247034/127121639-08c7b395-b19a-464d-bd53-d3e5b4c81785.png)

**Comment by kazaryan-t** [comment]
1. №1 the previous comment is not fixed.
Put in uppercase letter M in Maximum anonymity.

![6 1_receive-max-anon - 03 Android Wallet - Zeplin ](https://user-images.githubusercontent.com/68247034/127182854-eb4388ac-b7bc-4578-96a5-2b86cdbdc6b7.png)
![Screenshot_20210726-172921_Beam Wallet Masternet](https://user-images.githubusercontent.com/68247034/127182885-2b4d3f4a-e582-4b6e-b56c-b654d8257422.jpg)

2. Fix the comment to the show QR code popup (Maximum anonymity set).
 
![Screenshot_20210727-183413_Beam Wallet Masternet](https://user-images.githubusercontent.com/68247034/127183649-5631d7dd-c348-477c-9049-548320b26732.jpg)
![6 1_receive-regular-max-anon qr - 03 Android Walle](https://user-images.githubusercontent.com/68247034/127183928-c37ca692-602e-4982-a87a-5fc6d47627be.png)

**Comment by kazaryan-t** [comment]
Checked.
