### ISSUE TITLE
Change "max privacy" to "max anon. set" in status and comments when random node connected

### ISSUE THREAD

**Issue by dariatarakanova** [BeamMW/android-wallet#567]
1) When not own node is connected please display status "online: connected node supports online transactions only" and button "change" that leads to node settings https://zpl.io/2yov8Gp
![image](https://user-images.githubusercontent.com/47353570/128146712-d2752c23-5802-436e-a708-c5012e39db27.png)

2) In Settings update comment to "To support maximum anonymity set and offline transactions please connect to own node configured with your owner key." when user connects to remote node. https://zpl.io/blew8Ez
![image](https://user-images.githubusercontent.com/47353570/128146808-1c24ca39-6f73-454e-b4e1-fd424bdaadc0.png)

3) On Receive screen please disable Max anonymity set switcher. Remove comment "sender will be given a choice.." https://zpl.io/bWyzKEK
![image](https://user-images.githubusercontent.com/47353570/128146853-119e838f-5eee-402c-a4bd-407ac2f8bff7.png)

4) In address details show onIy online address + comment "You are currently connected to the node that supports only online transactions." Make title just "Online Address". https://zpl.io/brG5YQ1
![image](https://user-images.githubusercontent.com/47353570/128146896-f426fd94-3f46-42ea-a313-1b443bc283d6.png)

**Comment by KatsiarynaV** [comment]
1. SBBS address should be generated on the receive screen
![03](https://user-images.githubusercontent.com/68267190/128167951-3a0eab43-2bb2-4e15-815d-2186b12c6c3d.jpg)
![02](https://user-images.githubusercontent.com/68267190/128167959-9c807b97-a952-4d61-a251-22878bede692.jpg)

2. On the node settings screen the text changes position
GIF
![gif01](https://user-images.githubusercontent.com/68267190/128170523-7839675e-4c83-444e-ac6d-fe0b9c246d86.gif)

**Comment by dariatarakanova** [comment]
UPD:

1) Remove button "change" when on Node settings screen https://zpl.io/blew8Ez

2) Update text to "To support maximum anonymity set and offline transactions please connect to mobile node or own node configured with your owner key.".
Mobile node also can be used for max anon transactions.

![image](https://user-images.githubusercontent.com/47353570/128194230-c41fbedd-1291-4e98-8cd3-66ee28fe5315.png)

**Comment by KatsiarynaV** [comment]
1. Update text to "To support maximum anonymity set and offline transactions please connect to mobile node or own node configured with your owner key.".
Mobile node also can be used for max anon transactions.
![05](https://user-images.githubusercontent.com/68267190/128196358-2c2cf4d4-2347-4c64-9b5e-ed154d9ce69a.jpg)

2. The status text changes position
![gif02](https://user-images.githubusercontent.com/68267190/128199934-a5d03457-99a6-4042-a09c-9299ce48702b.gif)

**Comment by KatsiarynaV** [comment]
1. QR code should use sbbs address
Remove comment "sender will be given a choice.."
![06](https://user-images.githubusercontent.com/68267190/128325596-9cd97f34-d7c5-47c5-86d3-166c4d1b9d07.jpg)

2. After opening address details screen the address changes format on the receive screen
![gif03](https://user-images.githubusercontent.com/68267190/128326530-4990ae1e-b312-42da-8c5b-758f74bce813.gif)
![09](https://user-images.githubusercontent.com/68267190/128326512-59220447-8352-4bda-9fa4-f036b2bfe7ec.jpg)

**Comment by KatsiarynaV** [comment]
When scanning QR code the address in full format is pasted on the send screen
![06](https://user-images.githubusercontent.com/68267190/129332639-d97884bc-8cea-4c46-8cf1-fa876fac2406.jpg)

**Comment by KatsiarynaV** [comment]
Checked
