### ISSUE TITLE
Automatic restore doesn't work

### ISSUE THREAD

**Issue by KatsiarynaV** [BeamMW/android-wallet#568]
Automatic restore doesn't work. 
When choosing automatic restore after "Downloading blockchain info" screen the creation wallet screen is opened. Wallet isn't restored
![restore](https://user-images.githubusercontent.com/68267190/128826627-b1e47ce4-fd39-4d91-98d9-7aea77e57f62.gif)

**Comment by Denis-Asipenko** [comment]
checked
