### ISSUE TITLE
Add ability to copy address from the transaction

### ISSUE THREAD

**Issue by kaminskyelina** [BeamMW/android-wallet#57]
Same as in desktop Wallet

**Comment by vain-onnellinen** [comment]
@sasha-abramovich @alexandrashelenkova 
if yes - we need to add copy button in menu in toolbar at that screen:
https://app.zeplin.io/project/5ba9be48f029d520c456f395/screen/5bbb21e623bfd05fb66ebcb1

**Comment by vain-onnellinen** [comment]
@alexandrashelenkova I just was thinking about how it was done at desktop, but maybe your idea is better.

**Comment by Denis-Asipenko** [comment]
checked
