### ISSUE TITLE
Fix the spelling

### ISSUE THREAD

**Issue by dariatarakanova** [BeamMW/android-wallet#574]
Please fix the spelling of "synchronized".

**Correct: synchronized not sycnrhonized**
![image](https://user-images.githubusercontent.com/47353570/129352970-66f2d221-1e2b-4930-b6ce-9387ab9c7a37.png)

**Comment by Denis-Asipenko** [comment]
This task applies to the iOS wallet because a different text is used in the Android wallet. checked on the IOS wallet
