### ISSUE TITLE
Sync time implementation for Mobile node

### ISSUE THREAD

**Issue by dariatarakanova** [BeamMW/android-wallet#576]
1) Please implement calculating the synchronization time with the blockchain for Mobile node.

2) Remove the additional header line "Loading wallet", leave only secondary text. (see the lowest screenshot with current implementation)

3) Secondary Text: "Syncing with the blockchain: calculating estimated time"
"Syncing with the blockchain: X mins to completion"
"Syncing with the blockchain: less than a minute to completion"
Important: percents should be displayed only in whole numbers (5%, no 5.5%)

New design 
https://zpl.io/aXygZ6M
https://zpl.io/a3QpZAd

![image](https://user-images.githubusercontent.com/7249484/131184635-0ecd6136-348b-4c09-bf55-25762905c433.png)
![image](https://user-images.githubusercontent.com/7249484/131184644-b1ea3845-d03b-4b62-b77b-ad0b3790ff18.png)

The current implementation (for iOS, just as an example, cuz I do not have an android)
![image](https://user-images.githubusercontent.com/47353570/134405548-c2da8513-aa29-484d-9342-7dd292bdb989.png)

4) Please use such text suggestions for all node types connection

**Comment by gingervik** [comment]
@Denis-Asipenko please, add examples how it works now

**Comment by Denis-Asipenko** [comment]
At this stage, we cannot calculate the synchronization time with the blockchain if we use a mobile node. The fact is that there is no logic implemented for the mobile node that allows us to return information to the mobile application(our wallet) about how many blocks there will be in total in sync.

**Comment by sasha-abramovich** [comment]
@Denis-Asipenko Thanks for the helpful explanation, I guess the functionality will be fairly usable, but it's not a small task (as assumed early). We'll rename the task and re-submit. I guess a complementary technical/internal task is required to add the functionality in the infrastructure code. Let me know whether we need to open it.

**Comment by dariatarakanova** [comment]
The task body was updated with new info

**Comment by KatsiarynaV** [comment]
1. When wallet is connected to own node it doesn’t open when node isn’t running
![01](https://user-images.githubusercontent.com/68267190/158997216-cf12b691-d56e-48c8-95b5-6b0e542df831.jpg)

2. Text should be "Syncing with **the** blockchain"
![10](https://user-images.githubusercontent.com/68267190/158997403-44aac562-487f-4c4a-8f0d-17997e56b5ec.jpg)

3. "less than a minute to completion" -  "to completion" is duplicated
![11](https://user-images.githubusercontent.com/68267190/158997636-47ac3825-f0c4-4de8-8080-e1fa26402d6f.jpg)
![15](https://user-images.githubusercontent.com/68267190/158997642-aeabd5dd-6823-4955-8bab-6d87906049ae.jpg)

**Comment by KatsiarynaV** [comment]
1. Cannot create a wallet using mobile node

https://user-images.githubusercontent.com/68267190/159661953-fd952dad-e335-4d8e-a7a9-cbf68a54cb38.mp4

2. After wallet is created when we go to the node settings screen and then tap the 'back' button the password screen is opened instead of the main wallet screen

https://user-images.githubusercontent.com/68267190/159662178-c380bde0-937a-4395-a912-6dae2b4dfe63.mp4

**Comment by KatsiarynaV** [comment]
Checked
