### ISSUE TITLE
Change comment about exchange rate to USD

### ISSUE THREAD

**Issue by alexandrashelenkova** [BeamMW/android-wallet#584]
In CA transaction details add secondary currency name in the comment about exchange rate to "USD exchange rate..." (or "BTC/ETH rate" depending on selected secondary currency).
The full text should be:
"(USD exchange rate was not available at the time of transaction)" or "(USD rate calculated with the exchange rate at the time of transaction)"
https://zpl.io/bW7BRPj
https://zpl.io/2EGyyOY

![image](https://user-images.githubusercontent.com/7249484/132647832-39328b33-6e66-4456-839f-38ae4c533bed.png)

**Comment by kazaryan-t** [comment]
Checked.
P.S. Was decided to leave the comment above the currency amount and name.
