### ISSUE TITLE
Add search to Settings

### ISSUE THREAD

**Issue by dariatarakanova** [BeamMW/android-wallet#599]
1) Add Search field only to main Settings screen https://zpl.io/bzjKoJ8 
<img width="618" alt="image" src="https://user-images.githubusercontent.com/47353570/160473319-a495c557-a504-4b08-9a2b-81d47a97de80.png">

2) Search result highlight with blue color https://zpl.io/40y08A8
<img width="694" alt="image" src="https://user-images.githubusercontent.com/47353570/160473381-a76088be-b272-480a-a017-f0e8c5242258.png">

3) Search by ...

3.1) setting title (notifications, privacy, utilities,. etc - I guess this is relevant only for node.. but if a user wants to search "privacy" let's show it as result also)
<img width="370" alt="image" src="https://user-images.githubusercontent.com/47353570/160473580-7f791b54-ec6d-4acd-9740-a16f70459101.png">

3.2) parameters titles (show amounts in, minimum confirmations, ask for password, show utxo etc)
<img width="449" alt="image" src="https://user-images.githubusercontent.com/47353570/160473855-d4817164-0634-4500-b36a-ff4625435cdb.png">

3.3) parameters value that set
<img width="471" alt="image" src="https://user-images.githubusercontent.com/47353570/160473795-c40ef530-e025-470d-85f0-5a33f5c247ac.png">

4) Search by setting title and parameter https://zpl.io/EmEmrKy
<img width="495" alt="image" src="https://user-images.githubusercontent.com/47353570/160473917-45aad605-87a3-4db6-be62-7f54e8d404d0.png">

5. Search by parameter https://zpl.io/40y08A8
<img width="436" alt="image" src="https://user-images.githubusercontent.com/47353570/160474005-3d1719d5-9ffa-4c45-9042-bb6a0536f0ba.png">

6. Search by parameter value https://zpl.io/mDKDQ99
<img width="492" alt="image" src="https://user-images.githubusercontent.com/47353570/160474084-ae28d597-75d1-464a-a419-8735ca6c3abc.png">

7. No results. If user search by parameter value that not set https://zpl.io/B1o1rRQ
<img width="499" alt="image" src="https://user-images.githubusercontent.com/47353570/160474175-7ba2d31f-88cb-48af-ae75-bc4cf0af02aa.png">

8. From the search results screen user go to the inner screen (in this case it is a node). Then when he wants to get back and click the arrow it goes to the search results screen back. 
<img width="612" alt="image" src="https://user-images.githubusercontent.com/47353570/160474697-11868bb0-93d5-4fbb-94d5-d32ca2010dbe.png">

**Comment by KatsiarynaV** [comment]
Please make the text italic

![03](https://user-images.githubusercontent.com/68267190/161723520-9531a21c-96ce-4602-b105-bc0b929de4cd.jpg)

**Comment by KatsiarynaV** [comment]
Checked
