### ISSUE TITLE
Add button "Change" to status if Mobile node connection takes too long

### ISSUE THREAD

**Issue by dariatarakanova** [BeamMW/android-wallet#600]
1) Remove word "online"
2) Add "lock" icon to mobile and own node.
3) leave "circle" icon for random node.
4) Add "arrow" icon that leads to Node sittings
![image](https://user-images.githubusercontent.com/47353570/136009073-ac2b8ca6-ba32-4f2e-8478-4aecc54ecd5a.png)

5) Mobile node

5.1) Connected https://zpl.io/bLo9peM
![image](https://user-images.githubusercontent.com/47353570/136009126-dd9c6c86-c833-4bf0-8da5-6f86f86c15fd.png)

5.2) Updating https://zpl.io/bAwR0M8
![image](https://user-images.githubusercontent.com/47353570/136009185-59362771-7c20-46e7-b3e3-5527fc4a4fee.png)

5.3) Cannot connect https://zpl.io/aBAze4k
![image](https://user-images.githubusercontent.com/47353570/136009323-f48a8b6f-e14f-4869-b56d-b6269caeca6c.png)

6) Own node 

6.1) Connected https://zpl.io/bW78PpK
 ![image](https://user-images.githubusercontent.com/47353570/136009715-a5d80d2e-2fcf-4bdb-972a-efd93d7264c6.png)

6.2) Cannot connect https://zpl.io/a3PE7Zl
![image](https://user-images.githubusercontent.com/47353570/136009761-b3349e66-78aa-48d8-adbc-faf5b070e389.png)

7) Random node

7.1) Connected https://zpl.io/2EGQz6v
![image](https://user-images.githubusercontent.com/47353570/136009844-e3bda6a2-b24e-4577-96ac-f8dc0c2f35eb.png)

7.2) Reconnecting to another random node https://zpl.io/aNvxdd9
![image](https://user-images.githubusercontent.com/47353570/136009908-50fb164a-6802-49af-bebc-d21f539c7a42.png)

7.3) Cannot connect https://zpl.io/VOEv9g8
![image](https://user-images.githubusercontent.com/47353570/136010024-192b11a4-1dd8-4be9-afcd-95afad7d3e50.png)

**Comment by Denis-Asipenko** [comment]
https://github.com/BeamMW/ios-wallet/issues/531#issuecomment-933507731

**Comment by dariatarakanova** [comment]
@DenisDemyanko please make the following changes in text for connected nodes (green status)
@Denis-Asipenko FYI

1) "online: mobile node" should be just "online"
2) "online: own node xxx.xxx.xxx:xxxx" should be just "online"
3) "online: random node supports online transactions only" leave as it is

![image](https://user-images.githubusercontent.com/47353570/136980586-ea67eb15-d530-4077-b279-ca6efacbd72f.png)

**Comment by KatsiarynaV** [comment]
Checked

**Comment by KatsiarynaV** [comment]
For random node change status to "online: random node supports online transactions only"
![02](https://user-images.githubusercontent.com/68267190/140037443-a37b01d6-eddf-4420-a18f-3bb36e55ab1b.jpg)
![03](https://user-images.githubusercontent.com/68267190/140037449-7ae30f1c-768c-42ca-bbea-612b36816251.jpg)

**Comment by KatsiarynaV** [comment]
Checked
