### ISSUE TITLE
Add possibility to change a node without disconnection another node

### ISSUE THREAD

**Issue by dariatarakanova** [BeamMW/android-wallet#601]
1) Remove "disconnect" button https://zpl.io/2Gjz6jj
2) Make all node types "active" while one of is connected. User can switch the node without disconnecting https://zpl.io/2jKqYqq
![image](https://user-images.githubusercontent.com/47353570/143920803-d5e6addd-8ef1-4102-8d31-cd964abc73a2.png)

3) Add background under "connected" node https://zpl.io/2jKqYqq
![image](https://user-images.githubusercontent.com/47353570/143920873-c2cf7645-6f07-4750-af7e-dfab5485d8c5.png)

4) Own node view. Button 'proceed' is needed only here. After button display popup with confirmation. https://zpl.io/2j3lr3q
![image](https://user-images.githubusercontent.com/47353570/143920921-4f01b92b-c486-4cb0-8880-a9344124a036.png)

5) Place icon closer to text (see screenshot below)

6) Make text-comment with left-align
![image](https://user-images.githubusercontent.com/47353570/143921023-86b3ea1d-144f-4250-b698-4123e6b57df9.png)

7) Always display confirmation popup after user switch node.

From mobile to own https://zpl.io/bzzd7x4
![image](https://user-images.githubusercontent.com/47353570/143921082-85ad9c0d-64b8-4fc8-bf77-4ec0d8928615.png)

From mobile to random https://zpl.io/VD3NWm3
![image](https://user-images.githubusercontent.com/47353570/143921154-2e0fbce0-4e7f-49d6-ba54-7c9c175c150b.png)

From mobile to random (with active transactions) https://zpl.io/VqMzL46
![image](https://user-images.githubusercontent.com/47353570/143921248-03caacd9-f017-4bc0-8392-d4dcc8bcb02d.png)

From own to mobile https://zpl.io/aN3Oz39
![image](https://user-images.githubusercontent.com/47353570/143921303-29d4a39d-5ea8-4fc7-84c2-99237cf6e4cb.png)

From own to random https://zpl.io/aB3vW30
![image](https://user-images.githubusercontent.com/47353570/143921368-9437999a-7d29-4127-a8af-476c72e6c7f8.png)

From own to random (with active transactions) https://zpl.io/VkPMePL
![image](https://user-images.githubusercontent.com/47353570/143921424-62e35217-927e-48cb-8773-1b5aa284a458.png)

From random to mobile https://zpl.io/adoKNnR
![image](https://user-images.githubusercontent.com/47353570/143921475-1f30f9fc-f590-44f1-99c3-15a9e5e4c031.png)

From random to own https://zpl.io/V4XRzjQ
![image](https://user-images.githubusercontent.com/47353570/143921526-7fede98b-5583-4467-97be-e916775b5dc4.png)

**Comment by KatsiarynaV** [comment]
1. When trying to change a node connection to own node the wallet is stuck while syncing
![to own](https://user-images.githubusercontent.com/68267190/159644864-3fddc273-5aee-4e64-b1cf-cc72a37ee3e4.jpg)

2. When we select another node connection and tap 'cancel' button the node type remains selected

https://user-images.githubusercontent.com/68267190/159645732-a647085a-0744-40a3-9e5d-670f65e1da1a.mp4

https://user-images.githubusercontent.com/68267190/159646239-186da957-5839-44e5-a2e3-5400c9e9ddbc.mp4

**Comment by KatsiarynaV** [comment]
When opening the node settings screen the random node checkbox flashes for a moment


https://user-images.githubusercontent.com/68267190/159922057-ce654e6c-db15-4ed7-be32-ed52c11a4123.mp4

![photo_2022-03-24_16-00-32](https://user-images.githubusercontent.com/68267190/159922094-0ef6eb55-3c48-45a5-9482-bf934be957b8.jpg)

**Comment by KatsiarynaV** [comment]
Checked
