### ISSUE TITLE
Addresses - display addresses in a new format

### ISSUE THREAD

**Issue by Denis-Asipenko** [BeamMW/android-wallet#608]
Сurrently SBBS addresses are displayed in the address book in the address field. We need to display addresses in a new format like it is in a desktop wallet.
- **Addresses of the new format are used and saved if the user is connected to own node or mobile node.**
- **If the user is connected to a remote node, then only the SBBS address is used, respectively, the SBBS address will be stored in the Addresses.**
- Addresses in the new format should be displayed on the **"my active","my expired",and "contacts"** tabs.
- When a user shares an address, the address must be in a new format.
- SBBS address should only be displayed on the receive screen in "address details"
- In the address details, change the " signature" to " wallet signature".

Сurrent:
![image](https://user-images.githubusercontent.com/45556620/135300133-ee759885-c349-4736-9bd1-b71b3fa03111.png)

**Comment by KatsiarynaV** [comment]
1. Rename "signature" to "wallet signature"
![06](https://user-images.githubusercontent.com/68267190/137304066-28cc3fd3-a7ef-4eaf-b5e4-da9117290488.jpg)

2. If there are some addresses saved in the new format in address book, when user switch to the randome node 
these addresses should be automatically changed to SBBS. And if user switch back to the mobile or own node - SBBS addresses should be automatically changed to addresses in the new format. 
**Notes** - Default address should always be SBBS
         
How it  works on the desktop
![01](https://user-images.githubusercontent.com/68267190/137307330-d132e60a-5f6b-4e84-9411-8d2d364ccafd.gif)

3. When user send transaction and **doesn't** save contact the contact is saved as SBBS address. The contact shouldn't be saved

https://user-images.githubusercontent.com/68267190/137308508-3c5ed1f5-f900-4700-b615-0bdc479b7359.mp4

**Comment by KatsiarynaV** [comment]
When wallet is connected to the random node there is no address on address details screen
![address](https://user-images.githubusercontent.com/68267190/139633845-df3aabf4-b6da-4b0e-9dc3-b5e774955953.jpg)

**Comment by KatsiarynaV** [comment]
When wallet is connected to the random node, the address details screen is empty if we open receive screen from address book for SBBS address that was saved as the maximum anonymity address when wallet was connected to mobile/own node

https://user-images.githubusercontent.com/68267190/139835229-67982f3c-9baa-46e5-a411-e83b9b95f8df.mp4

**Comment by KatsiarynaV** [comment]
1. When contacts address contains amount, amount is not restored when choosing saved contact on the send screen
 
https://user-images.githubusercontent.com/68267190/140054771-9e6857f4-4605-4d08-8907-e54b1e99348a.mp4

2. Remove amount field from address details 
![01](https://user-images.githubusercontent.com/68267190/140056225-a2072dfb-79a2-437f-9976-9c12f051cf09.jpg)

**Comment by KatsiarynaV** [comment]
Checked
