### ISSUE TITLE
Change highlight color for search results from green to blue

### ISSUE THREAD

**Issue by dariatarakanova** [BeamMW/android-wallet#611]
To align with the desktop design (search on settings screen) please update the color for search highlights. Make it blue with glowing, not green (as now). https://zpl.io/bJGNzO3
![image](https://user-images.githubusercontent.com/47353570/136453632-d5ee060c-7eed-4321-837c-dcf3774ca9c7.png)

**Comment by KatsiarynaV** [comment]
Checked
