### ISSUE TITLE
Need ability to send logs from the client

### ISSUE THREAD

**Issue by kaminskyelina** [BeamMW/android-wallet#62]
**Description:**
It is not user friendly way in android to collect application logs 
Sometimes USB or PC might not be available 

There is a need to allow user to send logs
Can be done via Help menu or is Settings screen

**Comment by sasha-abramovich** [comment]
@alexandrashelenkova please help to design that functionality (similar or alltogether to desktop)

**Comment by alexandrashelenkova** [comment]
@sasha-abramovich we have report a problem button on settings screen. As soon as in the app everything's gonna happen automatically (getting the logs, putting in in mail app, typing in email address), I guess "report a problem" would be enough? No need to copy that long description from desktop app?

**Comment by alexandrashelenkova** [comment]
@sasha-abramovich I don't know that for sure but @vain-onnellinen told me that user wouldn't be able to see logs on his device even if he want to.

**Comment by vain-onnellinen** [comment]
@sasha-abramovich yes, logs (both mine and wallet's) are hidden from user. there is no way to get it by yourself, only send to me by pressing special button.

I can add possibility to see logs for user (via windows, file manager etc.) but 1. it requires much more time 2. we need to add special files permission request from user (and if user choose forbid - I won't be able to write any log). As for me too much job and too little profit.

better to make everything closed and automatic

**Comment by Denis-Asipenko** [comment]
checked
