### ISSUE TITLE
Display how much funds receiver gets via online and offline transactions

### ISSUE THREAD

**Issue by dariatarakanova** [BeamMW/android-wallet#623]
1) For **online** transactions add info how much funds will get the recipient (after fees). https://zpl.io/aB3PdY0
![image](https://user-images.githubusercontent.com/47353570/144096580-3f8dc4f6-d344-42fe-8265-76fe98ea5d76.png)

2) For **offline** transactions add info how much funds will get the recipient (after fees). https://zpl.io/2pqg7rM
![image](https://user-images.githubusercontent.com/47353570/144096665-2a153449-86c8-414a-b8cf-5d31df99b803.png)

3) For **Max anonymity** transaction add info how much funds will get the recipient (after fees). https://zpl.io/blnekJX
![image](https://user-images.githubusercontent.com/47353570/144096741-d7c86f5b-54f6-4c9c-b2a4-67b2744a0c70.png)

4) For **Public offline** transaction add info how much funds will get the recipient (after fees). https://zpl.io/awldgBn
![image](https://user-images.githubusercontent.com/47353570/144096854-85032ab7-66cc-46dc-a221-dd0547f7ec28.png)

5) Please add separator lines after "transaction type" and before "recipient will receive" https://zpl.io/awldgBn
![image](https://user-images.githubusercontent.com/47353570/144096932-f1eb0588-bf94-4189-afed-9358cfe75acf.png)

**Comment by Denis-Asipenko** [comment]
irrelevant as receiver will get all amount. fee is taken from sender's
