### ISSUE TITLE
To develop a functionality for the QR code payments within the mobile wallet 

### ISSUE THREAD

**Issue by ya-shy** [BeamMW/android-wallet#630]
It is requested to develop a functionality for the payments issued with a QR code (including the amount, address, comment (optional)). 

Process: scan the QR code -> receive an offer/notification to the phone to continue in the Beam app -> open the app -> get the page/form with all the pre-filled data there (amount, address, comment).

**Comment by Denis-Asipenko** [comment]
Hello
Thank you for your suggestion and we will take it into consideration. However, next time , if you have a suggestion, we ask you to write to us by email support@beam.mw and not to create a task independently and assign it to someone.
