### ISSUE TITLE
STD completion for Android wallet

### ISSUE THREAD

**Issue by kaminskyelina** [BeamMW/android-wallet#72]
**To write and perform additional tests**
1 - Install/Uninstall/Upgrade - test transactions and UTXO from old to newer versions and back
2 - Network connection - Test 3G connection, wifi, network disconnected, move from wifi to 3g while using the application
3 - Interruptions - Receive call while using the applications, different notifications (like SMS) etc
4 - Screen lock, off, power off, charging, flight mode, restart on device and how the wallet will recovery/wake up etc , what happens to transactions
5 - UI on all standard screen resolutions: 640 × 480, 800 × 600, 1024 × 768, 1280 × 800, 1366 × 768, 1400 × 900, 1680 × 1050.
6 - RTL system language
7 - Logs - to verify everything is printed (what we need)
8 - Restore on different wallets
9 - Work on two wallets with same seed 

limitation - Inconsistent transaction statuses when running two or more wallets that use the same wallet.db file, cloned manually. Once limitation will be resolved, need to add and perform those tests also

**Comment by Denis-Asipenko** [comment]
Done
