### ISSUE TITLE
Android wallet - Next button overlapping recovery phrase 

### ISSUE THREAD

**Issue by kaminskyelina** [BeamMW/android-wallet#82]
Android 1.0.0.?
Device OUKITEL K-10
Android 7.1.1
Screen resolution 2160x1080

- See attached screen
![image 2019-01-28 10 21 43](https://user-images.githubusercontent.com/45590119/51822962-89b9fa00-22e6-11e9-8453-7c50f7e756d7.jpg)

**Comment by Denis-Asipenko** [comment]
checked
