### ISSUE TITLE
Testnet android design

### ISSUE THREAD

**Issue by alexandrashelenkova** [BeamMW/android-wallet#83]
zpl.io/a75gYZK

**Comment by sasha-abramovich** [comment]
please change the style to match the testnet palette
@vain-onnellinen @kaminskyelina

**Comment by alexandrashelenkova** [comment]
App icons: https://drive.google.com/open?id=1xc6aeMVhqx0AfTD760FFoUrowJtyxXqn

**Comment by Denis-Asipenko** [comment]
checked
