### ISSUE TITLE
Make changes to the "Receive" screen .

### ISSUE THREAD

**Issue by Denis-Asipenko** [BeamMW/android-wallet#89]
Change field name from "Your transaction token" to "My address"
![screenshot_3](https://user-images.githubusercontent.com/45556620/52047041-3a2f3480-2559-11e9-89b5-6a15d001aad1.png)

Change text  from  "Send this token to the sender over secure channel" to "Send this address to the sender over **an external** secure channel"
![screenshot_2](https://user-images.githubusercontent.com/45556620/52046985-1d92fc80-2559-11e9-829a-89c9caaf469a.png)

**Comment by alexandrashelenkova** [comment]
Done :)

**Comment by kaminskyelina** [comment]
Verified on build 1.0.0.?  (from 31/01)
