### ISSUE TITLE
UI - change "Start address" and "End address" to "Sending address" and "Receiving address" 

### ISSUE THREAD

**Issue by kaminskyelina** [BeamMW/android-wallet#94]
**Describe the bug**
I Wallet main screen -> transaction details "Start address" and "End address" should be renamed to "Sending address" and "Receiving address" - same as in Desktop wallet

**To Reproduce**
Steps to reproduce the behaviour:
1. Login to the Android wallet that has any balance and Transactions history
2. Open one of the transactions details
3. Check the fields names and data correctness

**Expected behaviour**
Transaction details "Start address" and "End address" should be renamed to "Sending address" and "Receiving address" - same as in Desktop wallet

**Setup**
Device model: any
OS: any

**Comment by Denis-Asipenko** [comment]
checked
